### ISSUE TITLE
Allow gofumports as goimports alternative

### ISSUE THREAD

**Issue by powerman** [fatih/vim-go#2993] opened 2020-09-01 18:54 UTC
https://github.com/mvdan/gofumpt was added to golangci-lint, and it looks reasonable.
Please allow to set `let g:go_fmt_command = 'gofumports'`.
Also it may be a good idea to include it into list of installed/updated binaries.

**Comment by bhcleek** [comment] 2020-09-01 19:11
Have you tried setting `g:go_fmt_command` to `gofumpt`? I think it might just work, but I don't intend to add a fourth option for formatting.

**Comment by powerman** [comment] 2020-09-01 19:14
No, because I do need goimports functionality in addition to gofmt/gofumpt.
I've tried to set it to gofumports (just as shows in first comment) and noticed it doesn't work. Checked the docs, and noticed this:

> Valid options are `gofmt`, `goimports`, and `gopls`.

So it looks like other values are not supported and does not work.

**Comment by stamblerre** [comment] 2020-09-01 19:18
`gopls` currently supports `gofumpt` as an opt-in setting (`gofumpt: true` in gopls settings).

**Comment by bhcleek** [comment] 2020-09-01 19:22
Ah, thanks, @stamblerre ! I'll add proper support for that.

**Comment by powerman** [comment] 2020-09-01 19:23
@stamblerre Cool! Is `gopls` can use gofumports too?

**Comment by stamblerre** [comment] 2020-09-01 19:28
`gofumports` is just a wrapper that runs both `goimports` and `gofumpt`, and `gopls` already runs import organization separately, so you will still get the behavior of `goimports` and `gofumpt` when you enable `gofumpt` in `gopls`.

**Comment by bhcleek** [comment] 2020-09-01 19:32
> I've tried to set it to gofumports (just as shown in first comment) and noticed it doesn't work

What happens when you try? Although setting `g:go_fmt_command` to `gofumpt` isn't officially support, I believe it will work and testing on my local machine confirms that it does.

There are now separate options to configure `goimports` to be rearranged on save, too. See `:help g:go_imports_autosave` and `:help g:go_imports_mode`.

**Comment by powerman** [comment] 2020-09-04 08:08
> What happens when you try? Although setting `g:go_fmt_command` to `gofumpt` isn't officially supported, I believe it will work and testing on my local machine confirms that it does.

Well, actually it works, thanks! Even setting it to `gofumports` works as expected. Not sure why it didn't work when I tried for the first time, before opening the issue, sorry.

I've also tried to use `gopls` to get goimports functionality, and while it works it reformat `import ()` section is unusual way (without surrounding empty lines), e.g.:
```go
// before:
package ...

type ...

// after:
package ...
import (
	...
)
type ...
```
(@stamblerre Should I report this as separate issue for gopls?)

**Comment by stamblerre** [comment] 2020-09-04 16:08
> (@stamblerre Should I report this as separate issue for gopls?)

I haven't heard reports of this issue before, but you can easily check if it's caused by `gopls` (without `gofumpt`) by running `gopls imports /path/to/file.go` on the command line. If it is indeed `gopls`, please file a new issue [here](https://github.com/golang/go/issues/new) with an example of the code that reproduces the problem.

**Comment by powerman** [comment] 2020-09-04 16:21
At a glance it looks like there is both an issue with vim-go and gopls (a different ones).

Relevant part of vim-go setup:
```vim
let g:go_fmt_command = 'gopls'
let g:go_imports_autosave = 1
let g:go_imports_mode = 'gopls'
```

```sh
$ gopls version
golang.org/x/tools/gopls 0.4.4
    golang.org/x/tools/gopls@v0.4.4 h1:8djGYsaZ0ByP0vaXg4T+mnyfDcHpWKSZ+tpQSGv9ahk=
$ cat fmt.go 
package main
func F(*testing.T, time.Time) {}
$ gopls imports fmt.go 
package main

import (
	"testing"
	"time"
)
func F(*testing.T, time.Time) {}
$ goimports fmt.go 
package main

import (
	"testing"
	"time"
)

func F(*testing.T, time.Time) {}
$ gofumports fmt.go 
package main

import (
	"testing"
	"time"
)

func F(*testing.T, time.Time) {}
$ vi fmt.go # :wq
$ cat fmt.go 
package main
import (
	"testing"
	"time"
)
func F(*testing.T, time.Time) {}
```

**Comment by powerman** [comment] 2020-09-04 16:31
@bhcleek Sorry for moving discussion from one issue to another here. Should I close this one and open another about described above `gopls imports` issue or just change title of this one?

**Comment by bhcleek** [comment] 2020-09-04 16:41
This isn't the place to talk about gopls bugs generally.

I'm leaving this open until #2994 is merged.

**Comment by powerman** [comment] 2020-09-04 16:44
@bhcleek I was talking not about gopls issue (I've already opened https://github.com/golang/go/issues/41225), but about vim-go behaviour for using gopls as fmt/imports, which produces different output to `gopls imports` - see above.

**Comment by bhcleek** [comment] 2020-09-04 17:30
Feel free to open a separate issue about using `gopls` for adjusting imports when `let g:go_imports_mode='gopls'` if you want; that's a separate issue from your original description, and it's much easier to keep track of things when GitHub issues are focused on a single topic.

**Closed** 2020-09-06 17:38 UTC
