### ISSUE TITLE
GoAddTags does not work with anonymous struct

### ISSUE THREAD

**Issue by rcorre** [fatih/vim-go#1973] opened 2018-09-14 17:48 UTC
### What did you do? (required. The issue will be **closed** when not provided.)

```
package main

import (
	"encoding/json"
	"fmt"
)

func main() {
	data := []byte(`{"foo": "bar"}`)
	var out struct {
		Foo string
	}

	if err := json.Unmarshal(data, &out); err != nil {
		panic(err)
	}

	fmt.Println(out)
}
```

With the cursor on the line defining the `Foo` field, run `GoAddTags`.

### What did you expect to happen?

Tags are added to the struct.

### What happened instead?
`vim-go: offset is not inside a struct`

### Configuration (**MUST** fill this out):

* vim-go version: '8df48b2'

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

```
call plug#begin('~/.config/nvim/plugged')
Plug 'fatih/vim-go'
call plug#end()
```

* Vim version (first three lines from `:version`):

```
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5
```

* Go version (`go version`):

```
go version go1.11 linux/amd64
```

* Go environment (`go env`):

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/rodencor/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/rodencor/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build941480703=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by bhcleek** [comment] 2018-09-14 17:57
@fatih do you know if this is an outstanding issue with https://github.com/fatih/gomodifytags ?

**Comment by fatih** [comment] 2018-09-14 18:52
he `offset` mode of gomodifytags doesn't work for this particular issue. If you do a visual select for that line, the `line` mode will kick in and it'll work. Here is the output for the two modes separately: 

```
$ cat demo.go
package main

import (
        "encoding/json"
        "fmt"
)

func main() {
        data := []byte(`{"foo": "bar"}`)
        var out struct {
                Foo string
        }

        if err := json.Unmarshal(data, &out); err != nil {
                panic(err)
        }

        fmt.Println(out)
}
$ gomodifytags -file demo.go -offset 117 -add-tags foo
offset is not inside a struct
$ gomodifytags -file demo.go -line 11 -add-tags json                                                                        package main

import (
        "encoding/json"
        "fmt"
)

func main() {
        data := []byte(`{"foo": "bar"}`)
        var out struct {
                Foo string `json:"foo"`
        }

        if err := json.Unmarshal(data, &out); err != nil {
                panic(err)
        }

        fmt.Println(out)
}
```

You'll see it works for `line` mode but not `offset` mode. The offset mode is used by vim-go when you don't select anything. If you select anything, then it's the `line` mode.

This is also a duplicate of: https://github.com/fatih/vim-go/issues/1793 

There is an open issue in gomodifytags as well: https://github.com/fatih/gomodifytags/issues/34 But I couldn't prioritize it. I'll try to fix it.

**Comment by fatih** [comment] 2018-09-14 19:20
This is fixed now with: https://github.com/fatih/gomodifytags/pull/37 Please run `:GoUpdateBinaries` go get the latest gomodifytags. Thanks for the feedback.

**Closed by fatih** 2018-09-14 19:20 UTC

**Comment by rcorre** [comment] 2018-09-14 20:49
Confirmed it works. Thanks!
