### ISSUE TITLE
AutoComplete unimport failed

### ISSUE THREAD

**Issue by hungrybirder** [fatih/vim-go#2694] opened 2020-02-04 15:11 UTC
Hi @fatih 
I just upgrade vim-go `commit 9b34b29fccf0ee1fb44ffa20439e1739cb140c6c`, and vim-go upgrades gopls
```
cd ~/go/bin
md5sum gopls
04aeefccd940a136496a385c0889b108 
```
By using deoplete+supertab+vim-go, then
```
package main

import "fmt"

func main() {
	fmt.Println("vim-go")
        time.<tab>
}
```
Insert mode: `time.` and type tab, then I got no auto complete list...such as time.Tick or time.Second.... 
I don't know why.  
Before I upgraded vim-go, it worked well.

Some Info
```
go version go1.13.7 darwin/amd64
NVIM v0.4.3
macOS 10.15.3
```

From my init.vim
```
" supertab && snippets {{{
let g:SuperTabDefaultCompletionType = "context"
let g:SuperTabContextTextOmniPrecedence = ['&omnifunc', '&completefunc']
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<s-tab>"
" supertab && snippets }}}

```

**Comment by hungrybirder** [comment] 2020-02-04 15:18
I found https://github.com/fatih/vim-go/commit/891f391c5857ba6c83a25d1a395604c22356092e.

I rollback gopls to v0.2.2, then it works well.

**Comment by bhcleek** [comment] 2020-02-04 16:00
What you're describing doesn't work in either gopls v0.2.2 or v0.3.0 AFAIK.

/cc @stamblerre

**Comment by stamblerre** [comment] 2020-02-04 17:00
`gopls` does support unimported completions - they were behind a flag in `v0.2.2`, but are now on by default in `gopls/v0.3.0`. I'm not sure why they wouldn't be working in this case. Is it possible to get a `gopls` log from `vim-go`?

**Comment by bhcleek** [comment] 2020-02-04 18:27
vim-go uses `g:go_gpls_complete_unimported`, which defaults to 0, to control the respective gopls flag.

@stamblerre  I thought that only controlled completion of package names themselves, not completion of identifiers within unimported packages :thinking: 

And yes, a gopls log will be generated by executing `:let g:go_debug=['lsp']`

**Comment by stamblerre** [comment] 2020-02-04 18:40
Oh I see, that means that `vim-go` is disabling this by default. Can we switch the flag to on by default? And we are able to give completions for the exports of unimported packages--they are just not as rich as the imported ones.

**Comment by bhcleek** [comment] 2020-02-04 18:40
I confirmed that I get completion for unimported identifiers when `g:go_gopls_complete_unimported` is set. I'll create a PR to make that the default today to be in sync with gopls.

**Comment by bhcleek** [comment] 2020-02-04 19:08
I'm closing this, because it seems to be working as expected.

**Closed** 2020-02-05 05:05 UTC
