### ISSUE TITLE
GoDef colliding with coc.nvim

### ISSUE THREAD

**Issue by adrianforsius** [fatih/vim-go#3153] opened 2021-02-09 22:44 UTC
### What did you do? (required: The issue will be **closed** when not provided)

Install latest vim-go together with https://github.com/neoclide/coc.nvim and then running `:GoDef`

coc.vim version: https://github.com/neoclide/coc.nvim/pull/2864/commits/710c808ee17c8bef8944f38ddd8e319090f53da8

### What did you expect to happen?

Jumping to definition without seeing any error

### What happened instead?

Error was shown:
```
Error detected while processing function 88[13]..90[37]..function 88[13]..90[26]..<SNR>75_definitionHandler[8]..<SNR>89_jump_to_declartion_cb[5]..go#def#jump_to_declaration:
line 92:
E474: Invalid argument
Error detected while processing function 88:
line 13:
E171: Missing :endif
```

### Configuration (**MUST** fill this out):

Installed coc.nvim and latest vim-go

#### vim-go version:

Commit: `007d9bc7786d703dc778de7b69895b8c1907dde7`

####  `vimrc` you used to reproduce:
```
filetype off
call plug#begin('~/.vim/plugged')
        Plug 'neoclide/coc.nvim', {'branch': 'master', 'do': 'yarn install --frozen-lockfile'}
        Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
call plug#end()
```

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 14 2021 18:17:04)
Included patches: 1-2347
Compiled by Arch Linux

#### Go version (`go version`):

go version go1.15.8 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/adrianforsius/.cache/go-build"
GOENV="/home/adrianforsius/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/adrianforsius/code/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/adrianforsius/code/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/adrianforsius/code/goroot"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/adrianforsius/code/goroot/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build298429881=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.6.5
    golang.org/x/tools/gopls@v0.6.5 h1:kLt9rD/dWtVdvc8LmdcxagDFih6zxYXREpKSYYZu5KE=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_auto_type_info = 1
g:go_list_type = 'quickfix'
g:go_loaded_gosnippets = 1
g:go_addtags_transform = 'camelcase'
g:go_jump_to_error = 1
g:go_loaded_install = 1
g:go_def_mode = 'gopls'
g:go_fmt_command = 'goimports'
g:go_info_mode = 'gopls'
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment] 2021-02-10 05:33
Duplicate of #3137, #3138, and #3145.

coc.nvim plays no role in this issue

**Closed by bhcleek** 2021-02-10 05:33 UTC
Labels: duplicate
