### ISSUE TITLE
Get guru errors spewed into vim session

### ISSUE THREAD

**Issue by kojustin** [fatih/vim-go#1057] opened 2016-09-21 21:05 UTC
### Actual behavior

I get a bunch of output from guru while editing. It shows up at the bottom of vim like this...

```
193     //                                                                                              
Error detected while processing function <SNR>20_auto_sameids[3]..go#guru#SameIds:                                                  
line   41:
E28: No such highlight group name: goSameId
Press ENTER or type command to continue
Error detected while processing function <SNR>20_auto_sameids[3]..go#guru#SameIds:
line   41:
E28: No such highlight group name: goSameId
Press ENTER or type command to continue
```

If I hit enter a bunch of times it goes away.

It appears to happen randomly and not based on any particular inputs I make. I'll be using vim and then it will popup as I'm actively editing. It will pop up as I am in the browser looking up some information. 

### Expected behavior

No random guru errors should show up in my vim session.

### Configuration

Add here your current configuration and additional information that might be
useful, such as:

```
$ cat ~/.vimrc 
:set nocompatible
:set incsearch
:set hlsearch
:set smartindent
:set expandtab
:set nu
:syntax on
:set sts=4
:set sw=4
:set ruler

filetype plugin indent on " vundle: required to let vundle do its thing.

" Use space as leader.
let mapleader = "\<Space>"

"let g:ackprg="/usr/local/bin/ack -H --nocolor --nogroup --column"
nmap <Leader>a :Ack <cword><CR>

map <c-n> :cnext<cr>
map <c-p> :cprevious<cr>

" Set temporary file directory
set directory=~/tmp/vim
set guifont=Monaco:h14

" Save file contents if "make" is called.
set autowrite

" vim-go plugin commands
autocmd FileType go nmap <leader>i <Plug>(go-info)
autocmd FileType go nmap <leader>b <Plug>(go-build)
autocmd FileType go nmap <leader>n <Plug>(go-alternate-edit)
autocmd Filetype go setlocal ts=4 sts=4 sw=4
let g:go_auto_sameids = 1
let g:go_fmt_command = "goimports"
```

* vim version:

```
$ vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 19 2016 20:38:47)
MacOS X (unix) version
```
* vim-go version

commit d9fa1bc aka v1.9

* go version

```
$ go version
go version go1.6.2 darwin/amd64
```

**Comment by fatih** [comment] 2016-09-27 12:29
Hi @kojustin 

The error messages shows that it might be `go_auto_sameids` related. However I couldn't reproduce it. Can you please provide a case where it's possible to reproduce ? Otherwise I can't help much.

**Comment by fatih** [comment] 2016-10-23 11:09
I'm closing this as guru was refactored with the vim-8.0 branch dramatically. Feel free to open again with a reproducible case

**Closed by fatih** 2016-10-23 11:09 UTC

**Comment by brendanjerwin** [comment] 2017-09-28 14:57
FWIW I just started getting this:
```
Error detected while processing function <SNR>112_auto_sameids[3]..go#guru#SameIds[24]..<SNR>181_run_guru[6]..<SNR>181_sync_guru[2
7]..<SNR>181_same_ids_highlight:
line   40:
E28: No such highlight group name: goSameId
```

`:PlugUpdate` says I'm up to date, so probably vim-go: dcd3e3b  

I think I started seeing it after updating all my plugins...

**Comment by Carpetsmoker** [comment] 2017-09-28 15:03
Seems to work for me @brendanjerwin. `goSameId` is always set in `syntax/go.vim`, not sure why it's not set for you.

Could you try using a minimal vimrc with just vim-go and basic settings (e.g. `set nocompatible`, `filetype plugin on`, `syntax on`)?

**Comment by brendanjerwin** [comment] 2017-09-28 15:05
Yeah, I just went back to v1.14 and get the same behavior. I bet I have a conflict from something else...

**Comment by brendanjerwin** [comment] 2017-09-28 15:07
`vim-polyglot` was messing it up. If I remember correctly there is a way to disable languages in that. I'll do that.

**Comment by Carpetsmoker** [comment] 2017-09-28 15:10
Looks like that plugin comes with its own `syntax/go.vim`: https://github.com/sheerun/vim-polyglot/blob/master/syntax/go.vim

That one *also* sets `goSameId`though, and it seems like it's up-to-date with what vim-go uses, so not sure why it's not working ... Make sure it's up to date too?

**Comment by brendanjerwin** [comment] 2017-09-28 15:10
https://github.com/sheerun/vim-polyglot/issues/237
