### ISSUE TITLE
Vim-go seems to turn off when I save files...

### ISSUE THREAD

**Issue by ayjayt** [fatih/vim-go#2364] opened 2019-06-20 19:45 UTC
### What did you do? (required. The issue will be **closed** when not provided.)

Saved the file (`:w`)

### What did you expect to happen?

Vim-go to warn me about any issues

### What happened instead?

Syntax highlighting turned off and it seems like it doesn't run the checker (since I had obvious errors)

### Configuration (**MUST** fill this out):

(I've tried this on two systems and installed it freshly to do it too)

* vim-go version:

This has been happening with v1.20 and master

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

https://termbin.com/g2m6

* Vim version (first three lines from `:version`):
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 16 2019 17:06:40)
Included patches: 1-197, 322, 377-378, 550, 649, 651, 703, 706-707
Extra patches: 8.1.1401, 8.1.1382, 8.1.1368, 8.1.1367, 8.1.1366, 8.1.1365, 8.1.1046, 8.1.0613, 8.1.0547, 8.1.0546, 8.1.0544, 8.1.0540, 8.1.0539, 8.1.0538, 8.1.0506, 8.1.0208, 8.1.0206, 8.1.0205, 8.1.0189, 8.1.0177, 8.1.0066

* Go version (`go version`):
go version go1.12 linux/amd64

* Go environment (`go env`):
GOARCH="amd64"
GOBIN="/home/ajp/go/bin/"
GOCACHE="/home/ajp/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ajp/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/ajp/go/src/github.com/acst/codelitt/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
G:OGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803560247=/tmp/go-build -gno-record-gcc-switches"

**Comment by ayjayt** [comment] 2019-06-20 20:03
Here's a verbose=9 for just opening and writing and leaving a go file, https://termbin.com/foay

**Comment by ayjayt** [comment] 2019-06-20 21:04
I was ultimately able to resolve this by downgrading the debian package. I wish I had seen the closed issue first, but I don't normally check closed issues.

**Comment by bhcleek** [comment] 2019-06-24 13:49
duplicate of https://github.com/fatih/vim-go/issues/2363

**Closed by bhcleek** 2019-06-24 13:49 UTC
