### ISSUE TITLE
:GoBuild fails for cgo project with separate header file

### ISSUE THREAD

**Issue by amsibamsi** [fatih/vim-go#639] opened 2015-12-01 19:18 UTC
If I use `:GoBuild` command in a project like https://github.com/amsibamsi/opengles-examples/tree/master/window i get the error:
```
# command-line-arguments
/tmp/go-build986793141/command-line-arguments/_obj/main.cgo2.o: In function `_cgo_2a811b4822f2_Cfunc_setGlfwErrorCallback':
./main.go:155: undefined reference to `setGlfwErrorCallback'
collect2: error: ld returned 1 exit status
```

A normal `go build` in the project directory works. Should `:GoBuild` not work the same as `go build`?

If I remove the header file and put the function definition into the comment section before the C import it works. Could it have something to do with the `go#tools#Files()` function that uses `go list` to find all source files and somehow misses the header file? Or the build does not compile the C part so it is not there when linking?

**Comment by fatih** [comment] 2015-12-02 21:15
@amsibamsi they should work the same, expect we don't use `go build`. `:GoBuild` doesn't create a binary. To avoid it we're appending a fake package (in our case `errors`). So the actual command is something like: `go build . errors`. What happens if you execute it that way?

cgo support is not so good in vim-go, as I don't work with any cgo related projects (which means that I'm not able it to improve it much, like I do for other commands).  It might due `go#tools#Files()`, because it only lists `GoFiles`  but not `CgoFiles`:

```
        GoFiles        []string // .go source files (excluding CgoFiles, TestGoFiles, XTestGoFiles)
        CgoFiles       []string // .go sources files that import "C"
```

**Comment by amsibamsi** [comment] 2015-12-03 20:28
`go build . errors` works fine. If is set the `let gofiles` line to `= '.'` inside the `go#cmd#Build()` function in `cmd.vim` it works okay. I guess this only works in case the current directory is the package I am editing and want to build. I'm confused what the `go#tool#Files()` in `tool.vim` does. Should it find the package of the currently edited file so only that package can be built?

**Comment by fatih** [comment] 2015-12-04 14:11
>  I'm confused what the go#tool#Files() in tool.vim does. Should it find the package of the currently edited file so only that package can be built?

That's the case right, it returns the list of dependencies we're passing to go build (actually we're using it also for `go run` too, because `go run` doesn't accept the `.` argument)

**Comment by amsibamsi** [comment] 2015-12-10 10:21
So coming back to this. Obviously cgo projects build a bit differently. Would it be a good idea to have a command that builds the whole package of the file being edited?

**Comment by fatih** [comment] 2016-05-15 10:55
I'm closing this based on my comment here: https://github.com/fatih/vim-go/issues/211#issuecomment-219278089 I also couldn't check out the given file as it doesn't exists anymore. If it's a really big problem for a daily Go workflow, please reopen a new issue with the new Template and provide a reproducible test case. Thanks.

**Closed by fatih** 2016-05-15 10:55 UTC
