### ISSUE TITLE
How to show output of GoRun in preview window?

### ISSUE THREAD

**Issue by euoia** [fatih/vim-go#1902] opened 2018-07-28 12:05 UTC
This is a question / feature request and not a bug.

I would like to be able to show the output of GoRun in a preview window, that way repeated invocations of GoRun does not keep creating new windows but instead reuses the existing preview window.

### What did you do? (required. The issue will be **closed** when not provided.)
:GoRun

### What did you expect to happen?
Output to be shown in the preview window.

### What happened instead?
Output was shown in a normal vsplit window.

### Configuration (**MUST** fill this out):

* vim-go version: 765aff6cf

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc): n/a

* Vim version (first three lines from `:version`): NVIM v0.2.2

* Go version (`go version`): n/a

* Go environment (`go env`): n/a

**Comment by fatih** [comment] 2018-09-03 06:44
This might be something you would be able to do with https://github.com/fatih/vim-go/pull/1388

**Comment by viralkamdar** [comment] 2018-11-16 10:38
Any update on this?

**Comment by preslavmihaylov** [comment] 2019-04-28 11:49
I'm also interested in this feature

**Comment by skanehira** [comment] 2019-08-09 19:05
How about use popup window or terminal on vim8?

**Comment by skanehira** [comment] 2019-08-09 19:32
Example popup window.
```
call popup_menu(systemlist("go run " . expand("%")), {"filter":"popup_filter_menu"})
```
![image](https://user-images.githubusercontent.com/7888591/62804241-a651ad00-bb27-11e9-938b-4b21282f36d9.png)

Example terminal.
```
term go run %
```
![image](https://user-images.githubusercontent.com/7888591/62804280-c5e8d580-bb27-11e9-80e3-1f6bc9841b71.png)

**Comment by ZaynJarvis** [comment] 2020-01-08 07:55
You may want to check out this solution. [https://github.com/fatih/vim-go/issues/2510#issuecomment-571932106](url)

**Comment by bhcleek** [comment] 2020-06-22 03:54
Closing; this is effectively a duplicate of #2510

**Closed by bhcleek** 2020-06-22 03:54 UTC
Labels: improvement
