### ISSUE TITLE
Goto declaration doesn't update the location stack correctly anymore

### ISSUE THREAD

**Issue by rboyer** [fatih/vim-go#1028] opened 2016-08-26 14:15 UTC
### Actual behavior

In a normal go source file I use the `gd` command to go to the definition of a symbol.  This works fine, but when I attempt to go back using `Ctrl-O` it takes me to other places that make no sense.

### Expected behavior

`gd` + `Ctrl-O` should cancel out.  This used to work, but I can't tell you how far back it used to work.

### Steps to reproduce:

Minimal vimrc (in neovim):
```
call plug#begin('~/.vim/plugged')
Plug 'fatih/vim-go'
call plug#end()
```

Minimal go source file to see the problem:
```
package main

import "fmt"

const iso = "blah"

func main() {
	fmt.Printf("iso=%q", iso)
}
```

1. Manually navigate to the `Printf` line with your cursor on the `iso` variable.
2. Press `gd` to go to the definition of the constant.
3. Press `Ctrl-O` and the cursor returns to the first line of the file.

### Configuration

Add here your current configuration and additional information that might be
useful, such as:

* vim version: `NVIM 0.1.6-dev` (ubuntu 16.04 + neovim PPA)
* vim-go version `63bdcdf65b10a2080d2a534879177bc254e2761e`
* go version `1.7`

**Comment by nhooyr** [comment] 2016-08-26 16:09
Duplicate of #1026

**Closed** 2016-08-27 10:40 UTC
