### ISSUE TITLE
Second call to :GoDoc warns without reason

### ISSUE THREAD

**Issue by oblitum** [fatih/vim-go#364] opened 2015-03-23 21:17 UTC
Steps:

- Open any go file so that `:GoDoc` gets available.
- run `:GoDoc io`. It goes to `io` docs without warning.
- now run `:GoDoc os`. It warns: "can't load package: package .: no buildable Go source files in \<current $PWD\>", and then proceeds to open `os` docs.

I'm on OS X.

**Comment by fatih** [comment] 2015-03-24 09:35
I couldn't reproduce it :/ I've tried exactly what you did and there were no errors on my side. Any chance you can give me more detail ?

**Comment by oblitum** [comment] 2015-03-27 20:15
@fatih Are you on OS X? Don't recall whether it happens on Linux, will check later. Notice that, for this warning to should up the second `:GoDoc os` should be called with the last active window being the GoDoc window for `io`.

**Comment by oblitum** [comment] 2015-03-27 20:15
I've I change focus to another window it doesn't show up.

**Comment by fatih** [comment] 2015-04-30 07:18
Can you try again please. I don't see any errors? Is it related to this issue: https://github.com/fatih/vim-go/issues/332

**Comment by fatih** [comment] 2015-06-25 15:25
Closing this as ~ 2 months has been passed.

**Closed by fatih** 2015-06-25 15:25 UTC

**Comment by arechsteiner** [comment] 2015-08-16 18:38
I can reproduce this on Ubuntu 14.04. It happens when I use the command `:GoDoc fmt` (with fmt or any other package) when my cursor is either in NERDTree or in the window previously opened by GoDoc. So to reproduce try:

`:GoDoc fmt`

then, *without switching the cursor* to another window, leaving it in the window that GoDoc opened

`:GoDoc io`

Result is the error:

`can't load package: package .: no buildable Go source files in /home/alex`
