### ISSUE TITLE
feature request: GoBuildAll

### ISSUE THREAD

**Issue by vort3x** [fatih/vim-go#874] opened 2016-05-27 17:14 UTC
Would be nice to add **:GoBuildAll** command which will recursively build all underlying packages.

**Comment by tsne** [comment] 2016-06-04 11:32
Can't we use `:GoBuild ./...` here?

**Comment by vort3x** [comment] 2016-06-06 07:39
If you run :GoBuild ./... from main package - then yes, but if you want to run :GoBuild ./... from sub-package (helpers) and have problem in main.go file, it won't catch it.

**Comment by fatih** [comment] 2016-06-06 21:52
@tsne I think the problem is that `:GoBuild ./...` is not working. I'm checking it now.

**Comment by fatih** [comment] 2016-06-06 21:54
Just tested it and `:GoBuild ./...` with latest vim does indeed work. I'm closing this. @vort3x feel free to comment on this if you think it's wrong. But the command works fine. Thanks!

**Closed by fatih** 2016-06-06 21:54 UTC
Labels: feature

**Comment by vort3x** [comment] 2016-06-07 09:05
Ok, so it looks we have a misunderstanding here.

Steps to reproduce:
1. Prepare structure:
helpers/
   helpers.go
main.go

2. Write anything into main.go (shouldn't compile)
3. Go to helpers.go
4. Run :GoBuild ./... from helpers.go file

Expected result:
Build error in main.go.

Actual result:
Build success.

**Comment by fatih** [comment] 2016-06-11 09:57
@vort3x this is not possible and I don't think it's intended. You can change your `cd` into the folder of `main.go` and then execute `:GoBuild ./...`.

**Comment by vort3x** [comment] 2016-06-12 18:07
@fatih ok, still thanks!
