### ISSUE TITLE
GoRename fails:  with could not import / cannot find package

### ISSUE THREAD

**Issue by sgetmanring** [fatih/vim-go#2693] opened 2020-02-04 10:40 UTC
### What did you do? (required: The issue will be **closed** when not provided)
`:GoRename`

Trying to rename var with vim-go
execute `:GoRename`

with `let g:go_gorename_command = 'gopls'` in ~/.vimrs
export GO111MODULE=on
### What did you expect to happen?
Succefully rename
### What happened instead?
```
/Users/me/go/pkg/mod/github.com/mailru/easyjson@v0.0.0-20190614124828-94de47d64c    63/jwriter/writer.go|9 col 2| could not import github.com/mailru/easyjson/buffer (cannot f    ind package "github.com/mailru/easyjson/buffer" in any of: /usr/local/go/src/github.com/ma    ilru/easyjson/buffer (from $GOROOT) /Users/me/go/src/github.com/mailru/easyjson/    buffer (from $GOPATH))
```
#### vim-go version:
commit 311ea9dbbe91186afc8262cb2a2e52b406a32dbd (HEAD -> master, origin/master, origin/HEAD)
Merge: 804c8db 184a888
Author: Billie Cleek <bhcleek@users.noreply.github.com>
Date:   Thu Jan 30 21:13:18 2020 -0800

    Merge pull request #2688 from abeltay/update-readme

    Update README to new GoMetaLinter
####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
filetype plugin indent on
"set omnifunc=syntaxcomplete#Complete
set autowrite
set number
syntax on
"setlocal omnifunc=go#complete#Complete
set tags+=/usr/share/vim/vim81/doc/tags
autocmd CompleteDone * pclose
" set clipboard=unnamed
set background=dark
colorscheme solarized8

map <C-n> :cnext<CR>
map <C-m> :cprevious<CR>
nnoremap <leader>a :cclose<CR>
map <C-k> :.w !pbcopy<CR><CR>
map <C-p> :r !pbpaste<CR>

" run :GoBuild or :GoTestCompile based on the go file
function! s:build_go_files()
  let l:file = expand('%')
  if l:file =~# '^\f\+_test\.go$'
    call go#test#Test(0, 1)
  elseif l:file =~# '^\f\+\.go$'
    call go#cmd#Build(0)
  endif
endfunction
autocmd Filetype go command! -bang A call go#alternate#Switch(<bang>0, 'edit')
autocmd Filetype go command! -bang AV call go#alternate#Switch(<bang>0, 'vsplit')
autocmd Filetype go command! -bang AS call go#alternate#Switch(<bang>0, 'split')
autocmd Filetype go command! -bang AT call go#alternate#Switch(<bang>0, 'tabe')

let g:go_fmt_command = "goimports"
let mapleader = ","
let g:go_highlight_types = 1

let g:go_metalinter_autosave_enabled = ['vet', 'golint', 'errcheck']
let g:go_list_type = "quickfix"
let g:go_gorename_command = 'gopls'
</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb  3 2020 01:40:55)
macOS version
Included patches: 1-200
Compiled by Homebrew
<details><summary><code>details</code> Output:</summary><br><pre>
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_old_static
+arabic            +file_in_path      +mouse_urxvt       -tag_any_white
+autocmd           +find_in_path      +mouse_xterm       -tcl
+autochdir         +float             +multi_byte        +termguicolors
-autoservername    +folding           +multi_lang        +terminal
-balloon_eval      -footer            -mzscheme          +terminfo
+balloon_eval_term +fork()            +netbeans_intg     +termresponse
-browse            +gettext           +num64             +textobjects
++builtin_terms    -hangul_input      +packages          +textprop
+byte_offset       +iconv             +path_extra        +timers
+channel           +insert_expand     +perl              +title
+cindent           +job               +persistent_undo   -toolbar
-clientserver      +jumplist          +popupwin          +user_commands
+clipboard         +keymap            +postscript        +vartabs
+cmdline_compl     +lambda            +printer           +vertsplit
+cmdline_hist      +langmap           +profile           +virtualedit
+cmdline_info      +libcall           -python            +visual
+comments          +linebreak         +python3           +visualextra
+conceal           +lispindent        +quickfix          +viminfo
+cryptv            +listcmds          +reltime           +vreplace
+cscope            +localmap          +rightleft         +wildignore
+cursorbind        +lua               +ruby              +wildmenu
+cursorshape       +menu              +scrollbind        +windows
+dialog_con        +mksession         +signs             +writebackup
+diff              +modify_fname      +smartindent       -X11
+digraphs          +mouse             -sound             -xfontset
-dnd               -mouseshape        +spell             -xim
-ebcdic            +mouse_dec         +startuptime       -xpm
+emacs_tags        -mouse_gpm         +statusline        -xsmp
+eval              -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -lintl -framework AppKit  -L/usr/local/opt/lua/lib -llua5.3 -mmacosx-version-min=10.15 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.30.1/lib/perl5/5.30.1/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc  -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin -lpython3.7m -framework CoreFoundation  -lruby.2.6
</pre></details>
#### Go version (`go version`):

go version go1.12.7 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GOARCH="amd64"
GOBIN="/Users/sergiigetman/go/bin"
GOCACHE="/Users/sergiigetman/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/sergiigetman/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/sergiigetman/go/src/github.com/EdisonJunior/object_matching_api/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vj/jqm1qtdj5718h0lx8z0c7qn00000gn/T/go-build923982704=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.3.0
    golang.org/x/tools/gopls@v0.3.0 h1:l9KKK1/n6CIbfgaUvHBWAvCfOxcl1N+KSOK79OlPIao=
</pre></details>

**Comment by bhcleek** [comment] 2020-02-04 19:09
duplicate of https://github.com/fatih/vim-go/issues/2691

**Closed by bhcleek** 2020-02-04 19:09 UTC
