### ISSUE TITLE
No updating autocompletion when changes in local package

### ISSUE THREAD

**Issue by jlupox** [fatih/vim-go#3107] opened 2020-12-07 10:13 UTC
### What did you do? (required: The issue will be **closed** when not provided)
When adding a new function in a local package (imported as "./namePackage"). C-x C-o not shows the new func.
I have to close and reopen main.go file to see the new function in C-x C-o autocompletion
Invers, if I delete a func in local package, the main.go autocompletion is still showing the deleted func in local package.

#### vim-go version:
1.24
e3d6ada0530190300a5227bb0b417ee71b994cc2

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
let g:go_highlight_structs = 1
let g:go_highlight_methods = 1
let g:go_highlight_functions = 1
let g:go_highlight_operators = 1
let g:go_fmt_command = "goimports"
let g:go_highlight_function_calls = 1

let g:go_def_mode='gopls'
let g:go_info_mode='gopls'
let g:go_gocode_propose_source = 1
autocmd BufWritePost *.go silent! :GoBuild -i
</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.0
Included patches: 1-1453

#### Go version (`go version`):

go version go1.15.6 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jlperez/.cache/go-build"
GOENV="/home/jlperez/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/jlperez/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/jlperez/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"                                                                                                                                
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build226028234=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.5.4
    golang.org/x/tools/gopls@v0.5.4 h1:PkQWDfzw8CxoseHDQniF2GhzmndN8KnQL6gcG2gnF3Y=
</pre></details>

**Comment by bhcleek** [comment] 2020-12-07 18:41
I'm not sure if `gopls` fully supports local packages like this. @stamblerre do you know?

@jlupox I suspect that if you use modules instead of trying to use local packages, that you'll have a better experience.

**Comment by stamblerre** [comment] 2020-12-07 20:39
I believe this should work, but it's certainly untested. I agree that avoiding local imports is probably a good choice.

**Comment by jlupox** [comment] 2020-12-07 23:17
Only to comment,

With VSCode, local packages and autocompletion works fine.

**Comment by bhcleek** [comment] 2020-12-08 00:04
@jlupox I just confirmed that this works for me. I'm using gopls v0.5.5. If you're still having problems, a small script to create a directory structure that I could use to test with may be helpful to figure out what's different on your box.

**Comment by jlupox** [comment] 2020-12-09 16:21
I found it. I think.
If I open all the files with the same editor works fine.
If I work in two terminals with two editors, when I update the local package, the file importing the package does not notice the changes in packages.

**Comment by bhcleek** [comment] 2020-12-09 17:17
That's not necessarily unexpected; two editors may be using different `gopls` instances and `gopls` doesn't generally watch files on disk as far as I know.

**Comment by bhcleek** [comment] 2020-12-11 18:56
@jlupox was that the source of your problem? If so, shall we close this?

**Comment by jlupox** [comment] 2020-12-13 10:23
sorry @bhcleek if this is the behavior of gpls, it is what it is. Thanks!

**Comment by bhcleek** [comment] 2020-12-13 18:38
Yeah, it generally doesn't watch all files, so if you want to edit files and have a Vim session pick up those changes, use the same Vim session to edit the files. You may find Vim's tabs useful to keep your logical workspaces separate. https://stackoverflow.com/a/26710166 provide a good explanation of buffers, windows, and tabs if you're unfamiliar with them.

**Closed by bhcleek** 2020-12-13 18:38 UTC
