### ISSUE TITLE
Neovim: GoRename is slow even for small programs

### ISSUE THREAD

**Issue by Flygrounder** [fatih/vim-go#3385] opened 2022-03-31 17:05 UTC
### What did you do? (required: The issue will be **closed** when not provided)
Run `:GoRename message` when cursor is on `msg` variable.

```go
package main
                                                                           
import "fmt"
 
func main() {
    msg := "Hello world!"
    fmt.Println(msg)
} 
```

### What did you expect to happen?
Rename will happen in reasonable time. When I run `gopls rename main.go:6:5 message`, it outputs instantly, so I believe the problem is not with `gopls`. 

### What happened instead?
Plugin immediately prints `SUCCESS`, then the editor freezes for ~10 seconds and only after that becomes responsive again.

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim
let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin()
  Plug 'fatih/vim-go'
call plug#end()
```
</details>

#### Vim version (first three lines from `:version`):

NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3

#### Go version (`go version`):

go version go1.18 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/flygrounder/.cache/go-build"
GOENV="/home/flygrounder/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/flygrounder/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/flygrounder/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/flygrounder/Projects/random/test/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build863470501=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.8.1
    golang.org/x/tools/gopls@v0.8.1 h1:q5nDpRopYrnF4DN/1o8ZQ7Oar4Yd4I5OtGMx5RyV2/8=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_loaded_install = 1
g:go_jump_to_error = 1
g:go_loaded_gosnippets = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment] 2022-03-31 18:21
What version of vim-go are you using?

When does the rename happen? Do you see it at all? Only after the ~10 seconds elapses? At the time `SUCCESS` is printed?


It's nearly instantaneous for me. The fact that it's waiting about 10 seconds implies that there is a problem getting the response from `gopls`.


Can you execute `:let g:go_debug=['lsp', 'shell-commands']`, execute the rename, and then provide the complete logs from the `__GOLSP_LOG__` window and the output of `:messages` for me?

**Comment by Flygrounder** [comment] 2022-03-31 18:49
I've found out an interesting thing. This problem occurs in neovim, but not in regular vim

**Comment by bhcleek** [comment] 2022-03-31 20:24
Thanks. I can duplicate with Neovim. They probably changed how socket communication happens again. I'll take a look.

**Comment by bhcleek** [comment] 2022-03-31 21:51
It doesn't seem to be related to a change in socket communication. Other async message w/ gopls work very quickly. I'm not  yet sure what's going on that would cause this behavior only in Neovim and only with `:GoRename`.

**Comment by smlx** [comment] 2022-03-31 23:42
Hmm I've always had this problem (for at least the last three years) but always assumed it was just how `gorename` worked!

Also on neovim here, currently 0.6.1.

**Comment by smlx** [comment] 2022-04-01 04:37
hi @bhcleek just wondering.. did this issue get resolved?

**Comment by bhcleek** [comment] 2022-04-01 15:22
No. I closed the wrong issue.

**Comment by manishrjain** [comment] 2022-04-01 17:27
I have this exact issue as well. Can we please address this?

**Comment by findleyr** [comment] 2022-04-01 18:39
@manishrjain (or others who can easily reproduce): I'm curious about the `...` in your example. Is there a lot of RPC chatter? Is there an intermediate request that hangs?

Just speculating as to whether this is a server-side or client-side timeout. It's possible that vim-go hangs waiting on a _separate_ request to gopls, though I'm not aware of any suspicious 10s timeouts in gopls' codebase.

**Comment by bhcleek** [comment] 2022-04-01 21:47
@findleyr this is almost certainly not due to any problems with `gopls`. It doesn't occur at all in Vim; it's limited only to Neovim, and I've logged the request and response times in both Vim and Neovim. `gopls` provides the responses very quickly.

**Comment by manishrjain** [comment] 2022-04-02 02:40
@findleyr In between is just the `textDocument/definition` sends and receives. I tried it again, and this time even they didn't happen. Just the 10s lag, and then the `textDocument/didChange`

```
[Trace - 19:37:25.949 PM] Sending request 'textDocument/rename - (6)'.
Params: {"newName": "handleUpdate", "textDocument": {"uri": "<filepath>"}, "position": {"character": 5, "line": 497}}


[Trace - 19:37:25.953 PM] Received response 'textDocument/rename - (6)' in 4ms.
Result: {"documentChanges":[{"textDocument":{"version":4,"uri":"<filepath>"},"edits":[{"range":{"start":{"line":497,"character":5},"end":{"line":497,"character":14}},"newText":"handleUpdate"},{"range":{"start":{"line":660,"character":9},"end":{"line":660,"character":18}},"newText":"handleUpdate"}]}]}


[Trace - 19:37:35.974 PM] Sending notification 'textDocument/didChange'.
```

The file only gets updated when `textDocument/didChange` notification is received. Until then, everything freezes.

**Comment by manishrjain** [comment] 2022-04-02 17:31
> I've logged the request and response times in both Vim and Neovim. gopls provides the responses very quickly.

Are you saying that `textDocument/didChange` happens really quickly on Vim? As per my logs, the actual rename happens quickly even for Neovim + gopls (within 4-5ms).

**Comment by bhcleek** [comment] 2022-04-02 17:46
It's not the `didChange` that's taking so long. Vim-go isn't _sending_ that request until the rename completes. For some reason in Neovim, the second response in the rename process, the actual `rename` response, doesn't get processed until a the vim-go promise timeout expires. I can pretty easily affect this locally by adjusting the promise timeout value. There are a few likely culprits, but ultimately it seems like something in Neovim behaves differently than it does in Vim and it's not clear what or why yet.

**Comment by bhcleek** [comment] 2022-04-02 19:48
I think the problem here is the Neovim's timers don't work the same as Vim's timers. There are few issues in Neovim that are relevant. The issue [this comment](https://github.com/neovim/neovim/issues/10018#issuecomment-493574850) is on and the issues that the comment links to give some context.

For a variety of reasons, I'm not sure if I'll be able to provide a fix for this in vim-go.

**Comment by bhcleek** [comment] 2022-04-02 20:02
I figured out an acceptable solution. I'll put up a PR to address this later today.

**Closed** 2022-04-03 04:00 UTC
Labels: neovim

**Comment by manishrjain** [comment] 2022-04-04 15:58
Thanks a LOT, @bhcleek . Rename is so fast now, that it feels like sorcery!

```
[Trace - 08:57:31.856 AM] Sending request 'textDocument/rename - (5)'.
[Trace - 08:57:31.861 AM] Received response 'textDocument/rename - (5)' in 5ms.
[Trace - 08:57:31.876 AM] Sending notification 'textDocument/didChange'.
```
