### ISSUE TITLE
GoRename "can't find package"

### ISSUE THREAD

**Issue by markbates** [fatih/vim-go#221] opened 2014-11-05 18:56 UTC
When trying to use GoRename from `vim-go` I consistently get the following error:

```text
vim-go: Error: can't find package containing <$GOPATH>/github.com/myapp/mypackage/myfile.go.
```

On the command line `gorename` works just fine like this:

```text
gorename -from '"github.com/myapp/mypackages".MyThing' -to MyOtherThing
```

But with `vim-go` I keep getting the above error saying it can't find the package, which is actually the current file I'm on.

I'm sure there's some fairly simple setting, ENV variable, etc... that just needs tweaking, but I can't seem to figure it out.

Thanks.

**Comment by termie** [comment] 2015-01-05 22:38
weighing in on this as I've run into the same issue, we have a setup very similar to coreos/etcd: 

https://github.com/coreos/etcd/blob/master/build

As evidenced there, their usual workflow uses a symlink to put their library in the correct directory while allowing them develop from a more usable root. I agree a bit with @campadrenalin that there are a variety of go tools that do not support symlinks for this, but the ``go build`` tool itself certainly seems to and it seems like it would have the final say in the matter.

**Comment by termie** [comment] 2015-01-05 22:40
(again, the gorename tool on the commandline works)

**Comment by termie** [comment] 2015-01-05 23:05
digging around a bit, it seems the issue has to do with gorename trying to guess the package identifier and failing, when run on the command-line we're specifying the package identifier in the ``-from`` field, but in the text editor version of the command (``-offset``) it tries to guess it from the file and fails to deal with the symlink even if you cd into the symlink such that pwd shows a path under GOPATH

**Comment by termie** [comment] 2015-01-05 23:41
just to see whether gorename would do the right thing if given a full path to the symlink directory, I tried changing autoload/go/rename.vim to use ``pwd -L`` (as it seems Vim won't give you the logical path: http://stackoverflow.com/questions/708700/getting-the-logical-path-in-vim-when-theres-a-symlink )

  22:  let fname = printf('%s/%s', substitute(system('pwd -L'), '\n$', '', ''), expand('%:t'))

and that works if I run it from the package under the gopath (it passes the entire logical dir to gorename which short-circuits gorename's own path resolution based on buildutil.ContainingPackage), but there is no clear way to get my package dir from the root.

there is some precedence of people using a .godir file, I think this started with heroku but a variety of other projects have supported it at some point, though the movement is towards using Godep instead (not sure how they overlap yet). The CoreOS etcd project linked above still has that file as do many others, but I feel like using it is a bit of a hack.

This sort of thing is a bit of a continual annoyance in golang, unfortunately, it seems clear that many, many projects are trying to develop in what they think is a normal way and being bitten by golang's desire for them to live three subdirectories deep.

**Comment by jeffling** [comment] 2015-02-22 01:51
I've been having this problem too. Is there any solution?

**Comment by hraban** [comment] 2015-03-10 04:52
Had this problem, solved it by using symlinks.

My GOPATH = /home/hraban/go3d

my package named foo was in /home/hraban/foo/gosrc

```sh
cd ~/go3d/src/
ln -s ~/foo/gosrc/ foo
cd foo
vim *.go
```

From there I can use :GoRename.

**Comment by jeffling** [comment] 2015-03-30 09:07
I fixed my issue. Since I installed go through homebrew, the GOROOT was GOROOT="/usr/local/Cellar/go/1.4.1/libexec". Setting it in vim fixed it.

**Comment by yanpozka** [comment] 2015-04-13 03:32
Hello, I am having the same problem and I just have a little file with package main. Any solution ??

**Comment by jeffling** [comment] 2015-04-13 06:13
@yanpozka looks like there are a lot of different reasons this problem might prop up and a lot of solutions as well. What are the specifics of your problem?

**Comment by yanpozka** [comment] 2015-04-13 14:07
Hi, thanks for answer @jeffling . Well I just have a simple file with package main and I am trying to use :GoRename, this is my go env output:
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/yan/.golangcode"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

**Comment by hraban** [comment] 2015-04-13 14:10
where's the code?

**Comment by yanpozka** [comment] 2015-04-13 14:12
my code is in: /home/yan/example/main.go

**Comment by hraban** [comment] 2015-04-13 14:17
put it under $GOPATH/src

**Comment by yanpozka** [comment] 2015-04-13 14:28
So for every project/package that I'll create I have to create a link under $GOPATH/src ?? Hmm :(

**Comment by hraban** [comment] 2015-04-13 14:48
No comment :P

**Comment by termie** [comment] 2015-04-20 18:34
a link under GOPATH won't just work either, you have to literally be sitting in your package under the GOPATH for the tool to figure out who you are

**Comment by yanpozka** [comment] 2015-04-20 19:14
I don't like the idea of create a link for every project/package that I'll use

**Comment by termie** [comment] 2015-04-20 19:57
@yanpozka most people don't, it's a go-ism that is very unfriendly to new users, you can mostly get around this stuff with tools like godeps and glide (we use glide currently), it re-writes your GOPATH and puts your dependencies in a _vendor dir, unfortunately the tools underlying gorename don't really understand that a whole lot better either

**Comment by termie** [comment] 2015-04-20 19:58
i've been pushing for something like a .gopath or whatever file that will say "interpret this directory as existing at X path" i.e. github.com/yanpozka/myproject, but the language developers are a somewhat surly bunch

**Comment by hraban** [comment] 2015-04-20 20:02
@termie a link under GOPATH will work, as long as your cwd is through that link and not the original dir.

**Comment by termie** [comment] 2015-04-20 20:11
@hraban right, the point is that people tend to not want to work a bunch of directories deep unless they are a) java developers or b) work at google

**Comment by hraban** [comment] 2015-04-20 20:24
@termie: Sorry I guess I still don't understand. My reply was to this:

<blockquote>a link under GOPATH won't just work either, you have to literally be sitting in your package under the GOPATH for the tool to figure out who you are</blockquote>

What I'm trying to say is: a link under GOPATH does work. You don't have to move the contents of your package under GOPATH---just a symlink.

But perhaps that's what you meant?

**Comment by fatih** [comment] 2015-04-29 22:21
I've just learned that Vim doesn't follow the symlinks by default. If you start it with `vim -u NONE symlinkedFile.go`, you'll see it. 

I've changed now the file name to resolve to full path, which causes GoRename to bypass resolving at all too (according to @termie). 

So the problem is still not solved, because Vim is following the symlinks. Either something in vim-go is causing it or one of the well known vim plugins is causing it (side effects). 

I'm going to create a minimal Vim environment, without a single vimrc setting and only vim-go. If I find something I'll let you know.

**Comment by fatih** [comment] 2015-04-29 22:39
Tried again and now it shows the symlinked file. So confused now. I think I need to dig in more deeper.

**Comment by fatih** [comment] 2016-04-10 19:01
I'll close this as this issue is just an dead end with no solutions and it's a very special case (files being outside of GOPATH but a symlink to GOPATH). I don't have any specific answer nor do I know how to solve it in near term. We didn't had any reply to this issue for ~1 year, which seems like everyone found a way of fixing/changing their workflow. Thanks for all the comments. As always please open an issue for specific questions or needs. Thanks!

**Closed by fatih** 2016-04-10 19:01 UTC
Labels: bug

**Comment by ashb** [comment] 2016-04-25 09:50
Is it worth tidying up the error message? `package "-1"` is sort of confusing at least.

**Comment by fatih** [comment] 2016-04-25 09:51
@ashb of course, mind opening an issue on when it appears `package -1`? I'll fix it.

**Comment by ashb** [comment] 2016-05-20 21:04
My vim-go was previously ~9 months out of date -- I can't reproduce this one anymore. :+1:

**Comment by blitzprog** [comment] 2016-11-12 13:37
Ran into the same issue and my projects are under `~/projects` while the tree structure GOPATH (which I absolutely do not want to work with) is in `~/workspace/` with symlinks to the real projects.

"Can't find package containing ..."

**Comment by ifraixedes** [comment] 2017-01-30 15:15
I got this issue having a GOPATH with several directories, e.g. `GOPATH=/home/x/workspace/go/src:home/x/go/src`

I wanted to just report it, no idea if this can help you with anything.

**Comment by miguelmota** [comment] 2018-02-23 19:57
Adding the following to `~/.vimrc` fixed the "can't find package containing" error for me

```vimrc
let g:go_bin_path = "/usr/local/bin/go"
let $GOPATH = $HOME."/go"
```

**Comment by wsc1** [comment] 2018-11-17 20:08
This is happening for me again after a fresh install of everything :(

**Comment by Duologic** [comment] 2020-12-30 10:24
Sorry for bumping this issue, this is a top search result on DuckDuckGo, so adding a quick ref to the solution: https://github.com/fatih/vim-go/issues/2366#issuecomment-583033166:

```
let g:go_rename_command = 'gopls'
```
