### ISSUE TITLE
Key not present in dictionary

### ISSUE THREAD

**Issue by trstringer** [fatih/vim-go#2757] opened 2020-03-03 17:15 UTC
### What did you do? (required: The issue will be **closed** when not provided)

I opened up a *.go file.

I also tried updating gopls as per #2710 with `:GoUpdateBinaries gopls` but I still get the error.

### What did you expect to happen?

No errors.

### What happened instead?

I received the error:

vim-go: initializing gopls
vim-go: initialized gopls
vim-go: function 287[10]..290[3]..291[2]..292, line 52: Vim(if):E716: Key not present in Dictionary: version == l:version

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
Plugin 'fatih/vim-go'
" vim-go
let g:go_def_mapping_enabled = 0
" let g:go_fold_enable = []
let g:go_fmt_experimental = 1
</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 19 2020 21:48:46)
Included patches: 1-2269
#### Go version (`go version`):

go version go1.13.6 linux/amd64
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/trstringer/.cache/go-build"
GOENV="/home/trstringer/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/trstringer/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build861566960=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.3.3
    golang.org/x/tools/gopls@v0.3.3 h1:mTFqRDJQmpSsgDDWvbtGnSva1z9uX2XcDszSWa6DhBQ=
</pre></details>

**Comment by juztin** [comment] 2020-03-03 18:09
I also get this on current `master` _(`23a33e4013a59c9e9133099cd39ed01b34e05001`)_.
Once I switch over to `1.22`, the issue goes away.

**Comment by trstringer** [comment] 2020-03-03 18:13
Nice! That stopped the error for me! Thanks, @juztin!

**Comment by bhcleek** [comment] 2020-03-03 19:05
duplicate of https://github.com/fatih/vim-go/issues/2748.

The solution, if you want to use master is to run `:GoUpdateBinaries gopls`.

**Comment by trstringer** [comment] 2020-03-03 19:33
@bhcleek unfortunately that's not the case for me. Using master and running `:GoUpdateBinaries gopls` did not fix it for me.

**Comment by bhcleek** [comment] 2020-03-03 19:37
Can you run Vim with `let g:go_debug=['lsp']` in your vimrc, duplicate the problem, and provide the contents of gopls debug window?

**Comment by trstringer** [comment] 2020-03-03 19:54
How do I get the content of gopls debug window?

**Comment by bhcleek** [comment] 2020-03-03 21:23
It will come up automatically; just use the usual yank to  get its contents.

**Comment by bhcleek** [comment] 2020-03-04 08:07
I may have figured out what's going on here.

Can you clarify the steps to reproduce the problem you're seeing: I'm wondering if you only see this problem when you open a file on the commandline (e.g. `vim foo.go`), but don't see this problem when you open a file by starting vim without any arguments and then execute `:edit` (e.g. `:edit foo.go`)?

**Comment by trstringer** [comment] 2020-03-04 13:02
Sorry for the delay. Unfortunately that didn't fix it. Here's the gopls output:

```
sent: Content-Length: 489^M^@^M^@{"method":"initialize","jsonrpc":"2.0","id":1,"params":{"rootUri":"file:///home/trstringer/go/src/sqlaadtest","capabilities":{"workspace":{"workspaceFolders":true,"configuration":true,"didChangeConfiguration":{"dynamicRegistration":true}},"textDocument":{"completion":{"completionItem":{"snippetSupport":false}},"hover":{"contentFormat":["plaintext"]}}},"processId":6059,"workspaceFolders":[{"uri":"file:///home/trstringer/go/src/sqlaadtest","name":"/home/trstringer/go/src/sqlaadtest"}]}}
stderr: 2020/03/04 08:01:02 debug server listening on port 34255
sent: Content-Length: 307^M^@^M^@{"method":"textDocument/didOpen","jsonrpc":"2.0","params":{"textDocument":{"uri":"file:///home/trstringer/go/src/sqlaadtest/sqlaad.go","version":1,"languageId":"go","text":"package main\n\nimport \"fmt\"\nimport mssql \"github.com/denisenkom/go-mssqldb\"\n\nfunc main() {\n\tfmt.Println(\"vim-go\")\n}\n"}}}
sent: Content-Length: 52^M^@^M^@{"method":"initialized","jsonrpc":"2.0","params":{}}
received: Content-Length: 870^M^@^M^@{"jsonrpc":"2.0","result":{"capabilities":{"textDocumentSync":{"openClose":true,"change":2,"save":{}},"completionProvider":{"triggerCharacters":["."]},"hoverProvider":true,"signatureHelpProvider":{"triggerCharacters":["(",","]},"definitionProvider":true,"typeDefinitionProvider":true,"implementationProvider":true,"referencesProvider":true,"documentHighlightProvider":true,"documentSymbolProvider":true,"codeActionProvider":true,"codeLensProvider":{},"documentLinkProvider":{},"workspaceSymbolProvider":true,"documentFormattingProvider":true,"documentOnTypeFormattingProvider":{"firstTriggerCharacter":""},"renameProvider":true,"foldingRangeProvider":true,"executeCommandProvider":{"commands":["tidy","upgrade.dependency"]},"workspace":{"workspaceFolders":{"supported":true,"changeNotifications":"workspace/didChangeWorkspaceFolders"}}},"serverInfo":{"name":""}},"id":1}
sent: Content-Length: 38^M^@^M^@{"id":1,"jsonrpc":"2.0","result":null}
received: Content-Length: 268^M^@^M^@{"jsonrpc":"2.0","method":"client/registerCapability","params":{"registrations":[{"id":"workspace/didChangeConfiguration","method":"workspace/didChangeConfiguration"},{"id":"workspace/didChangeWorkspaceFolders","method":"workspace/didChangeWorkspaceFolders"}]},"id":1}
received: Content-Length: 109^M^@^M^@{"jsonrpc":"2.0","method":"window/showMessage","params":{"type":1,"message":"unexpected config tempModFile"}}
received: Content-Length: 109^M^@^M^@{"jsonrpc":"2.0","method":"window/showMessage","params":{"type":1,"message":"unexpected config tempModFile"}}
sent: Content-Length: 169^M^@^M^@{"id":2,"jsonrpc":"2.0","result":[{"buildFlags":[],"hoverKind":"NoDocumentation","tempModFile":true},{"buildFlags":[],"hoverKind":"NoDocumentation","tempModFile":true}]}
```

**Comment by bhcleek** [comment] 2020-03-04 17:15
@trstringer did you see the problem during the session where got that gopls log from? I'd expect to see a `textDocument/publishDiagnostics` message in the gopls log, but it's not there 🤔

**Comment by trstringer** [comment] 2020-03-04 17:29
@bhcleek correct, same session.

**Comment by bhcleek** [comment] 2020-03-04 17:48
Can you try #2758 and see if it resolves the problem you're seeing?

**Closed** 2020-03-04 19:17 UTC
Labels: duplicate
