### ISSUE TITLE
Installation issue with `gopls`

### ISSUE THREAD

**Issue by burhan** [fatih/vim-go#2252] opened 2019-04-30 19:56 UTC
### What did you do? (required. The issue will be **closed** when not provided.)

Installing dependencies after installing the plugin using the Vim 8 package method.

Steps:

1. `git clone https://github.com/fatih/vim-go.git ~/.vim/pack/plugins/start/vim-go`

2. `vim`

3. `:GoInstallBinaries`

Got the following error:

```
vim-go: gopls not found. Installing golang.org/x/tools/cmd/gopls to folder /home/burhan/go/bin/
Error installing golang.org/x/tools/cmd/gopls: # golang.org/x/tools/internal/lsp/source^@go/src/golang.org/x/tools/internal/lsp/source/symbols.go:226:18: ti.EmbeddedType undefined (type *types.Interface has no field or method EmbeddedType)^@
```
### Configuration (**MUST** fill this out):

* vim-go version:

Still installing it, so I assume the latest production version based on the installation instructions in the repository.

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

Not sure this is relevant, but I am using pathogen and the lightline plugin.

* Vim version (first three lines from `:version`):

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2018 21:31:58)
Included patches: 1-1453
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
```
* Go version (`go version`):

`go version go1.10.4 linux/amd64`

* Go environment (`go env`):

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/burhan/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/burhan/go"
GORACE=""
GOROOT="/usr/lib/go-1.10"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.10/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build181020905=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by stamblerre** [comment] 2019-04-30 20:09
Duplicate of https://github.com/fatih/vim-go/issues/2246

**Closed** 2019-04-30 22:00 UTC
