### ISSUE TITLE
"vim-go: no matches" is shown after every keypress in some projects

### ISSUE THREAD

**Issue by powerman** [fatih/vim-go#3201] opened 2021-04-19 15:22 UTC
### What did you do? (required: The issue will be **closed** when not provided)

Just typing something in .go files, no matter is it comment or code. Example:
[![asciicast](https://asciinema.org/a/lY2unxkxfWLfpYC1e1JBdKMpA.svg)](https://asciinema.org/a/lY2unxkxfWLfpYC1e1JBdKMpA)

### What did you expect to happen?

No "vim-go: no matches" messages jumping on me after every keypress.

### What happened instead?

In some projects I get "vim-go: no matches" message after every keypress. Screencast above shows two small projects: https://github.com/powerman/must have this issue, https://github.com/powerman/check doesn't have this issue.

The workaround is to replace `'go#complete#Complete'` with `'SilentGoComplete'` in vimrc listed below, but it's just a dirty hack and I'd like to find out the root reason why it happens and have it fixed in vim-go instead.

#### vim-go version:
ce95699efa82921f80fdc0984d002ff81584c6e6 (yesterday's master)

####  `vimrc` you used to reproduce:

As auto-complete is triggered by deoplete plugin I'll include setup for both plugins.

```vim
let g:python3_host_prog = '/usr/bin/python3'
let g:deoplete#enable_at_startup = 1
call deoplete#custom#source('_',
    \ 'matchers', ['matcher_head'])
call deoplete#custom#option({
    \ 'auto_complete_popup': 'manual',
    \ })

let s:in_complete = v:false " Like pumvisible() when auto_complete_popup=manual.

autocmd CompleteDone * let s:in_complete = v:false

inoremap <expr> <Down>  pumvisible() ? "\<C-n>" : "\<Down>"
inoremap <expr> <Up>    pumvisible() ? "\<C-p>" : "\<Up>"

inoremap <silent><expr> <TAB>
    \ <SID>check_back_space() ? <SID>smart_tab() :
    \ <SID>is_in_complete() ? "\<C-n>" :
    \ deoplete#can_complete() ? <SID>complete_deoplete() : <SID>complete_generic()

inoremap <silent><expr> <CR>
    \ <SID>is_in_complete() ? <SID>fix_cr_indent() : "\<CR>"

function! s:check_back_space() abort
    let col = col('.') - 1
    return !col || getline('.')[col - 1] =~# '\s'
endfunction

function! s:smart_tab()
    let col = col('.') - 1
    if &expandtab || !col || getline('.')[:col-1] =~# '^\s*$'
        return "\<Tab>"
    endif
    return ' '
endfunction

function! s:is_in_complete() abort
    return pumvisible() || s:in_complete
endfunction

function! s:complete_deoplete()
    let s:in_complete = v:true
    return deoplete#complete()
endfunction

function! s:complete_generic()
    let s:in_complete = v:true
    return "\<C-n>"
endfunction

function! s:fix_cr_indent()
    call timer_start(1, {-> feedkeys("\<CR>", 'in')})
    return " \<BS>" " Stop completion to fix autoindent on following <CR>.
endfunction

" Prevent showing "vim-go: no matches" after every keypress (this happens only sometimes).
function! SilentGoComplete(findstart, base) abort
    silent! return go#complete#Complete(a:findstart, a:base)
endfunction

call deoplete#custom#var('omni', 'functions', {
    \ 'go':          ['go#complete#Complete'],
    \ })
call deoplete#custom#var('omni', 'input_patterns', {
    \ 'go':          '[^. *\t]\.\w*|^\w+|\s\w+',
    \ })

let g:go_metalinter_command = 'golangci-lint'
let g:go_fmt_fail_silently = 1
let g:go_gopls_gofumpt = v:true
let g:go_gopls_local = {}
autocmd FileType go call s:setlocal()
let g:go_doc_keywordprg_enabled = 0
let g:go_template_use_pkg = 1
let g:go_list_type = 'quickfix'
let g:go_highlight_array_whitespace_error = 1
let g:go_highlight_chan_whitespace_error = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_operators = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_parameters = 0
let g:go_highlight_function_calls = 1
let g:go_highlight_types = 1
let g:go_highlight_fields = 0
let g:go_highlight_build_constraints = 1
let g:go_highlight_generate_tags = 1
let g:go_highlight_string_spellcheck = 1
let g:go_highlight_format_strings = 1
let g:go_highlight_variable_declarations = 0
let g:go_highlight_variable_assignments = 0
let g:go_build_tags = 'integration'
let g:go_gopls_matcher = 'caseSensitive'
let g:go_gopls_deep_completion = 0
let g:go_gopls_temp_modfile = 1
let g:go_gopls_use_placeholders = 0
autocmd FileType go nmap <buffer> <nowait> <Leader>r     <Plug>(go-run)
autocmd FileType go nmap <buffer> <nowait> <Leader>b     <Plug>(go-build)
autocmd FileType go nmap <buffer> <nowait> <Leader>t     <Plug>(go-test)
autocmd FileType go nmap <buffer> <nowait> <Leader>T     <Plug>(go-test-func)
autocmd FileType go nmap <buffer> <nowait> <Leader>c     <Plug>(go-coverage-toggle)
autocmd FileType go nmap <buffer> <nowait> <Leader>gd    <Plug>(go-def-tab)
autocmd FileType go nmap <buffer> <nowait> <Leader>gb    <Plug>(go-doc-browser)
autocmd FileType go nmap <buffer> <nowait> <Leader>s     <Plug>(go-implements)
autocmd FileType go nmap <buffer> <nowait> <Leader>i     <Plug>(go-info)
autocmd FileType go nmap <buffer> <nowait> <Leader>e     <Plug>(go-rename)

function! s:setlocal()
    try
        let l:olddir = chdir(expand('%:p:h'))
        let l:dir = trim(system('go list -m -f {{.Dir}}'))
        if !has_key(g:go_gopls_local, l:dir)
            let g:go_gopls_local[l:dir] = trim(system('go list -m'))
        endif
    finally
        call chdir(l:olddir)
    endtry
endfunction
```

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.2 (2019 Dec 12, собрано Jan 23 2021 14:04:15)
Заплатки: 1-814
С изменениями, внесёнными Gentoo-8.2.0814-r100

#### Go version (`go version`):

go version go1.16.3 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/powerman/.cache/go-build"
GOENV="/home/powerman/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/powerman/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/powerman/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="x86_64-pc-linux-gnu-gcc"
CXX="x86_64-pc-linux-gnu-g++"
CGO_ENABLED="1"
GOMOD="/home/powerman/tmp/go/no-matches/must/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build584304205=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.6.10
    golang.org/x/tools/gopls@v0.6.10 h1:8Ebz8PymS2umcuCFhoz67unyJfWsipjTIrkBUF9kypg=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_fmt_fail_silently = 1
g:go_list_type = 'quickfix'
g:go_highlight_extra_types = 1
g:go_highlight_operators = 1
g:go_gopls_matcher = 'caseSensitive'
g:go_highlight_function_calls = 1
g:go_highlight_function_parameters = 0
g:go_highlight_fields = 0
g:go_highlight_generate_tags = 1
g:go_gopls_deep_completion = 0
g:go_highlight_variable_declarations = 0
g:go_highlight_string_spellcheck = 1
g:go_loaded_gosnippets = 1
g:go_gotags_bin = 'gotags'
g:go_metalinter_command = 'golangci-lint'
g:go_doc_keywordprg_enabled = 0
g:go_highlight_variable_assignments = 0
g:go_highlight_format_strings = 1
g:go_gopls_local = {'/home/powerman/tmp/go/no-matches/must': 'github.com/powerman/must'}
g:go_highlight_chan_whitespace_error = 1
g:go_highlight_functions = 1
g:go_template_use_pkg = 1
g:go_gopls_use_placeholders = 0
g:go_highlight_types = 1
g:go_jump_to_error = 1
g:go_gopls_gofumpt = v:true
g:go_build_tags = 'integration'
g:go_highlight_build_constraints = 1
g:go_loaded_install = 1
g:go_gopls_temp_modfile = 1
g:go_highlight_array_whitespace_error = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:OFF
</pre></details>

**Comment by bhcleek** [comment] 2021-04-19 15:49
I think this is happening because of deoplete and is probably happening because of the triggering characters:
```
call deoplete#custom#var('omni', 'input_patterns', {
    \ 'go':          '[^. *\t]\.\w*|^\w+|\s\w+',
    \ })
```

That regex looks very aggressive and is going to attempt completion on nearly every character, and of course not every string will have completion candidates.

**Comment by powerman** [comment] 2021-04-19 16:01
The main question is why this happens only in some projects. In other projects, both very small and huge, this doesn't happens.

**Comment by bhcleek** [comment] 2021-04-19 16:22
I'm not sure, but I suspect that with your `check` repository, `gopls` isn't fully initialized and so hasn't responded to the completion requests yet. We could tell for sure by examining the `gopls` logs (e.g. start vim with `--cmd let g:go_debug=['lsp']` ).

**Comment by powerman** [comment] 2021-04-19 17:29
At a glance I don't see any noticeable difference in logs (but there are a lot of output, so I may miss something). Also, omni completion works in both repos. So, it doesn't looks like gopls doesn't work in one of them.

**Comment by bhcleek** [comment] 2021-04-19 19:24
We'd want to look at the `textDocument/completion` requests and see if they have responses in the repository where you're not seeing the `vim-go: no matches` messages.

**Comment by powerman** [comment] 2021-04-20 06:08
There are no differences in logs while typing "Qwe":
<details><summary>check: typing "Qwe"</summary><p>

```json
===== sent =====
Content-Length: 196

{"method":"textDocument/didChange","jsonrpc":"2.0","params":{"contentChanges":[{"text":"package check\n\n// Q\n"}],"textDocument":{"uri":"file:///home/powerman/tmp/go/check/tmp.go","version":11}}}
===== sent =====
Content-Length: 173

{"method":"textDocument/completion","jsonrpc":"2.0","id":2,"params":{"textDocument":{"uri":"file:///home/powerman/tmp/go/check/tmp.go"},"position":{"character":4,"line":2}}}
===== received =====
Content-Length: 66

{"jsonrpc":"2.0","result":{"isIncomplete":true,"items":[]},"id":2}
===== sent =====
Content-Length: 197

{"method":"textDocument/didChange","jsonrpc":"2.0","params":{"contentChanges":[{"text":"package check\n\n// Qw\n"}],"textDocument":{"uri":"file:///home/powerman/tmp/go/check/tmp.go","version":12}}}
===== sent =====
Content-Length: 173

{"method":"textDocument/completion","jsonrpc":"2.0","id":3,"params":{"textDocument":{"uri":"file:///home/powerman/tmp/go/check/tmp.go"},"position":{"character":5,"line":2}}}
===== received =====
Content-Length: 66

{"jsonrpc":"2.0","result":{"isIncomplete":true,"items":[]},"id":3}
===== sent =====
Content-Length: 198

{"method":"textDocument/didChange","jsonrpc":"2.0","params":{"contentChanges":[{"text":"package check\n\n// Qwe\n"}],"textDocument":{"uri":"file:///home/powerman/tmp/go/check/tmp.go","version":13}}}
===== sent =====
Content-Length: 173

{"method":"textDocument/completion","jsonrpc":"2.0","id":4,"params":{"textDocument":{"uri":"file:///home/powerman/tmp/go/check/tmp.go"},"position":{"character":6,"line":2}}}
===== received =====
Content-Length: 66

{"jsonrpc":"2.0","result":{"isIncomplete":true,"items":[]},"id":4}
```
</p></details>

<details><summary>must: typing "Qwe"</summary><p>

```json
===== sent =====
Content-Length: 194

{"method":"textDocument/didChange","jsonrpc":"2.0","params":{"contentChanges":[{"text":"package must\n\n// Q\n"}],"textDocument":{"uri":"file:///home/powerman/tmp/go/must/tmp.go","version":11}}}
===== sent =====
Content-Length: 172

{"method":"textDocument/completion","jsonrpc":"2.0","id":2,"params":{"textDocument":{"uri":"file:///home/powerman/tmp/go/must/tmp.go"},"position":{"character":4,"line":2}}}
===== received =====
Content-Length: 66

{"jsonrpc":"2.0","result":{"isIncomplete":true,"items":[]},"id":2}
===== sent =====
Content-Length: 195

{"method":"textDocument/didChange","jsonrpc":"2.0","params":{"contentChanges":[{"text":"package must\n\n// Qw\n"}],"textDocument":{"uri":"file:///home/powerman/tmp/go/must/tmp.go","version":12}}}
===== sent =====
Content-Length: 172

{"method":"textDocument/completion","jsonrpc":"2.0","id":3,"params":{"textDocument":{"uri":"file:///home/powerman/tmp/go/must/tmp.go"},"position":{"character":5,"line":2}}}
===== received =====
Content-Length: 66

{"jsonrpc":"2.0","result":{"isIncomplete":true,"items":[]},"id":3}
===== sent =====
Content-Length: 196

{"method":"textDocument/didChange","jsonrpc":"2.0","params":{"contentChanges":[{"text":"package must\n\n// Qwe\n"}],"textDocument":{"uri":"file:///home/powerman/tmp/go/must/tmp.go","version":13}}}
===== sent =====
Content-Length: 172

{"method":"textDocument/completion","jsonrpc":"2.0","id":4,"params":{"textDocument":{"uri":"file:///home/powerman/tmp/go/must/tmp.go"},"position":{"character":6,"line":2}}}
===== received =====
Content-Length: 66

{"jsonrpc":"2.0","result":{"isIncomplete":true,"items":[]},"id":4}
```

</p></details>

**Comment by bhcleek** [comment] 2021-04-20 20:47
I'm not quite sure why the timing is the way it is, but I'm pretty sure I'm seeing the `no matches` message in your `check` repository in the screen recording, too, but it's flashing quickly and being replaced with the mode. Can you run `:messages` after trying completion in your `check` repository and not seeing the `no matches` to confirm?

Try running Vim with `set noshowmode` to verify.

**Comment by powerman** [comment] 2021-04-21 05:39
Yes, you are right. There are same messages in both repos.

But why in one repo these messages wasn't actually shown for long enough time to make them noticeable while in another they are shown for 4 seconds (and because of this it feels like message "steal" visual cursor - it kinda disappears from the line where I'm typing until message will disappear or I'll type next symbol).

**Comment by bhcleek** [comment] 2021-04-22 16:24
It's hard to know what might be affecting those timings

**Comment by bhcleek** [comment] 2021-04-25 15:26
Given that vim-go is displaying the message correctly in both instances, that the message itself is caused by sending completion requests on every key press, that vim-go cannot affect when the mode message is shown, and that you could likely resolve this by using `no showmode`, I'm going to close this.

Thank you for a well-written issue report.

**Closed by bhcleek** 2021-04-25 15:26 UTC
