### ISSUE TITLE
go.mod file is mixed when using vim-go in multiple projects

### ISSUE THREAD

**Issue by itchyny** [fatih/vim-go#2383] opened 2019-07-04 10:45 UTC
### What did you do? (required: The issue will be **closed** when not provided)

```
 $ export GO111MODULE=on
 $ killall gopls
 $ go get -u golang.org/x/tools/cmd/gopls
 $ mkdir a b
 $ echo 'package main\n\nimport "golang.org/x/xerrors"\n\nfunc main() {\n  xerrors.New("")\n}\n' > a/main.go
 $ echo 'package main\n\nimport "golang.org/x/sys/unix"\n\nfunc main() {\n  unix.SysctlRaw("kern.boottime")\n}\n\n' > b/main.go
 $ (cd a && go mod init a && go run main.go)
go: creating new go.mod: module a
go: finding golang.org/x/xerrors latest
 $ (cd b && go mod init b && go run main.go)
go: creating new go.mod: module b
go: finding golang.org/x/sys/unix latest
go: finding golang.org/x/sys latest
 $ cat a/go.mod b/go.mod
module a

go 1.12

require golang.org/x/xerrors v0.0.0-20190513163551-3ee3066db522 // indirect
module b

go 1.12

require golang.org/x/sys v0.0.0-20190626221950-04f50cda93cb // indirect
```
Now, module a depends only on xerrors, module b depends on only on sys.

```
 $ git clone git@github.com:fatih/vim-go.git /tmp/vim-go
 $ echo 'set rtp+=/tmp/vim-go\nfiletype plugin on' > vim-go-vimrc
 $ vim -u ./vim-go-vimrc -N
```
And in Vim
```
:e a/main.go
:e b/main.go
:qall
```
Now check the module files.
```
 $ cat a/go.mod b/go.mod
module a

go 1.12

require (
        golang.org/x/sys v0.0.0-20190626221950-04f50cda93cb // indirect
        golang.org/x/xerrors v0.0.0-20190513163551-3ee3066db522
)
module b

go 1.12

require golang.org/x/sys v0.0.0-20190626221950-04f50cda93cb // indirect
```
Now I see unexpected update in go.mod where the sys module is included in the mod file of package a, while it only depends on the xerrors module.

### What did you expect to happen?
The module files are not updated and no unexpected package will be listed.

### What happened instead?
A package which is not used (including indirect) is listed. Note that xerrors does not depend on sys ([go.mod](https://github.com/golang/xerrors/blob/master/go.mod)).
I doubt something is wrong with the current working directory update in this plugin on invoking go something command.
### Configuration (**MUST** fill this out):
See the above reproducing steps.

#### vim-go version:
The latest version (1f7e3de081b213635315538623a707c81011150c).

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
See the above reproducing steps, including only set rtp and plugin commands.
```
set rtp+=/tmp/vim-go
filetype plugin on
```
#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 26 2019 04:36:15)
macOS version
Included patches: 1-1600

#### Go version (`go version`):

go version go1.12.6 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/itchyny/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/itchyny/.go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.6/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.6/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/mg/nqgjy_l53n15b3_dfrjw9_600000gn/T/go-build367172096=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

**Comment by bhcleek** [comment] 2019-07-04 15:26
Thank you for a great bug report!

I've compiled your steps into a reproduction script:
```
#!/bin/sh

export GO111MODULE=on
cd $(mktemp -d)
echo $PWD

go get -u golang.org/x/tools/cmd/gopls

mkdir a b
echo 'package main\n\nimport "golang.org/x/xerrors"\n\nfunc main() {\n  xerrors.New("")\n}\n' > a/main.go
echo 'package main\n\nimport "golang.org/x/sys/unix"\n\nfunc main() {\n  unix.SysctlRaw("kern.boottime")\n}\n\n' > b/main.go
(cd a && go mod init a && go run main.go)
(cd b && go mod init b && go run main.go)

vimdir=$(mktemp -d)
git clone git@github.com:fatih/vim-go.git $vimdir/vim-go
echo "set rtp+=/tmp/vim-go\nfiletype plugin on" > vim-go-vimrc
vim -u ./vim-go-vimrc -N

# edit a/go.mod and b/go.mod in Vim and then quit.

cat a/go.mod b/go.mod
```

But I am unable to reproduce the behavior you're seeing.

FWIW, all that vim-go really does here is to run `go mod edit --fmt` on go.mod file; there is like a bug in `go mod` that's causing what you're seeing, _but_ we can probably work around it by changing the `go#util##Exec` call at https://github.com/fatih/vim-go/blob/master/autoload/go/mod.vim#L37 to `go#util#ExecInDir` if we can figure out a set of reproduction steps that works for both of us.

**Comment by itchyny** [comment] 2019-07-05 00:08
It seems that my command (echo) depends on zsh so changing the echo to printf and  changing `rtp+=/tmp/vim-go` to `rtp+=$vimdir/vim-go` should work. Thanks.

```sh
#!/bin/sh

export GO111MODULE=on
cd $(mktemp -d)
echo $PWD

GO111MODULE=off go get -u golang.org/x/tools/cmd/gopls

mkdir a b
printf 'package main\n\nimport "golang.org/x/xerrors"\n\nfunc main() {\n  xerrors.New("")\n}\n' > a/main.go
printf 'package main\n\nimport "golang.org/x/sys/unix"\n\nfunc main() {\n  unix.SysctlRaw("kern.boottime")\n}\n\n' > b/main.go
(cd a && go mod init a && go run main.go)
(cd b && go mod init b && go run main.go)

vimdir=$(mktemp -d)
git clone git@github.com:fatih/vim-go.git $vimdir/vim-go
echo "set rtp+=$vimdir/vim-go\nfiletype plugin on" > vim-go-vimrc

echo === before ===
cat a/go.mod b/go.mod

vim -u ./vim-go-vimrc -N

# edit a/go.mod and b/go.mod in Vim and then quit.

echo === after ===
cat a/go.mod b/go.mod
```

**Comment by bhcleek** [comment] 2019-07-05 03:56
Ah yes, you're right about the `$vimdir/vim-go` change. I've tried both your script and a slightly modified version of the one I'd provided previously, but I still can't duplicate the problem you've described.

**Comment by stamblerre** [comment] 2019-07-08 19:01
This is likely an instance of https://github.com/golang/go/issues/32499. We will investigate this issue soon. It may need to be fixed inside of `gopls`. The current workaround is just remembering to run `go mod tidy`, which I know isn't a very good solution.

**Closed** 2019-08-09 17:22 UTC
