### ISSUE TITLE
:GoInstall doesn't close the quickfix window when succesful

### ISSUE THREAD

**Issue by vdemario** [fatih/vim-go#526] opened 2015-08-31 15:43 UTC
I used to rely a lot on `:GoBuild`, and the quickfix window with the errors closes itself when there are no more build errors.

`:GoInstall` gives me the exact same quickfix window with compilation errors, but once it succeeds with no errors, the errors for the last unsuccessful build stay open. Am I missing something, can this be closed automatically already somehow?

I'm using the v1.1 tag.

**Comment by fatih** [comment] 2015-09-01 12:18
Hi @vdemario. This might be true, I've just quick checked it and it seems we don't close it for `:GoInstall`. Maybe I'm wrong but I'll mark this as bug until I check it out in more detail. Thanks for bringing this up.

**Comment by vdemario** [comment] 2015-09-01 12:49
Thanks.

I tried moving the `:GoBuild` code to the `:GoInstall` function and just changing `build` to `install`. It worked but I couldn't get the original message from the `:GoInstall` command to stick, my VimL skills are pretty much non-existent. ¯\_(ツ)_/¯

If I manage to do it I'll send a PR.

**Comment by fatih** [comment] 2015-09-01 15:42
I know where the problem is, I'll look into it ;)

**Closed** 2015-09-02 15:33 UTC
Labels: bug
