### ISSUE TITLE
type info bug

### ISSUE THREAD

**Issue by gertcuykens** [fatih/vim-go#585] opened 2015-10-25 22:42 UTC
type info for own functions is adding `()` characters depending on cursor position, see screenshot
![image](https://cloud.githubusercontent.com/assets/863731/10718377/874efa56-7b71-11e5-9de0-a6642c801df9.png)

**Comment by fatih** [comment] 2015-11-15 18:49
Hi @gertcuykens 

Can you please add a test case which I can use to reproduce the error? Otherwise it's really hard.

**Comment by gertcuykens** [comment] 2015-11-15 19:10
Just type a function and move cursor over it in terimal os x, the cursor get replaced by ( in type info

**Comment by fatih** [comment] 2015-11-15 21:38
It's not the case for me as I couldn't reproduce it. A fully reproducible test case would be helpful for me.

**Comment by gertcuykens** [comment] 2015-11-15 22:01
vim version 7.4.889
vim test.go
```go
package main

import "fmt"

func main() {
        fmt.Printf("Hello world")
}
```
![image](https://cloud.githubusercontent.com/assets/863731/11171273/7674281a-8bec-11e5-91fb-c07ab267aa71.png)

**Comment by gertcuykens** [comment] 2015-11-15 22:03
```vim
call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-sensible'
Plug 'fatih/vim-go'
Plug 'tpope/vim-unimpaired'
Plug 'terryma/vim-multiple-cursors'
call plug#end()
set number
set nowrap
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
let g:go_fmt_command = "goimports"
let g:go_fmt_fail_silently = 1
let g:go_auto_type_info = 1
let g:netrw_liststyle = 3
```

**Comment by fatih** [comment] 2015-11-15 22:07
@gertcuykens this doesn't happen for me. Can you please disable all other plugins and try again? Also can you please update [gocode](https://github.com/nsf/gocode) too?

**Comment by gertcuykens** [comment] 2015-11-15 22:19
disbaled plugins
go get github.com/nsf/gocode
stil the same result
are you using vim in terminal mac os x?

**Comment by fatih** [comment] 2015-11-15 22:20
No I'm not, but this is a fundamental command. I think something special is going on with your problem, otherwise I would get tons of complaints (which I've didn't received for months)

**Comment by gertcuykens** [comment] 2015-11-15 22:23
do you know somebody else with a mac?

**Comment by fatih** [comment] 2015-11-15 22:27
I'm using Mac with MacVim. I've tried it with Terminal with no issues.

**Comment by gertcuykens** [comment] 2015-11-15 22:28
using self compiled vim from source

**Comment by gertcuykens** [comment] 2015-11-15 22:30
```log
 vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Oct  6 2015 04:28:02)
MacOS X (unix) version
Included patches: 1-889
Compiled by gert@mpb
Normal version without GUI.  Features included (+) or not (-):
+acl             -farsi           -mouse_netterm   +syntax
-arabic          +file_in_path    -mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           -mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
+builtin_terms   -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         -gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   -perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    -keymap          +postscript      +virtualedit
+comments        -langmap         +printer         +visual
-conceal         +libcall         -profile         +visualextra
+cryptv          +linebreak       -python          +viminfo
-cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             -rightleft       +windows
+diff            +menu            -ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
-emacs_tags      -mouseshape      -sniff           -xsmp
+eval            -mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L/usr/local/lib -o vim        -lm -lncurses  -liconv -framework Cocoa   
```

**Comment by fatih** [comment] 2016-01-21 03:36
I'm closing this as invalid. Don't think this is vim-go related as it would affect anyone. normal completion, `c-x c-o` works without any problem. Thanks.

**Closed by fatih** 2016-01-21 03:36 UTC
