### ISSUE TITLE
:GoTest replaces current window with an empty buffer

### ISSUE THREAD

**Issue by payneio** [fatih/vim-go#367] opened 2015-03-30 17:05 UTC
:GoTest runs tests. When they FAIL, the current window is replaced with a new buffer. This causes me to need to re-open the file I was working on.

**Comment by fatih** [comment] 2015-03-30 17:10
Can you provide a test case please? It should do it, it opens a quick windows rather than replacing a buffer.

**Comment by nowk** [comment] 2015-04-14 13:25
@payneio are you using an assertion package, eg. bmizerany/assert or other? I have experienced this issue when using those + the auto jump feature since the path of the error returned is through the assertion package and not directly relative to the `_test.go`.

    let g:go_jump_to_error = 0

You may want to try to disable the auto jump to see if that helps.

**Comment by ox** [comment] 2015-04-24 19:40
I was having the same problem and setting `g:go_jump_to_error` to 0 helped. I don't know what else it may have affected but I'm happy to get some test output in my vim.

**Comment by mlafeldt** [comment] 2015-04-29 16:11
@fatih I'm experiencing the same problem myself: running a test with `GoTest` or `GoTestFunc` results in an empty buffer.

By looking at `%` in vim, I found out that the problem is caused by a wrong file path where the package path is missing. As a result, jumping to the source location in question only works with files in the current folder.

Another way to reproduce the issue is to use an external testing library like [testify](github.com/stretchr/testify/assert). With it, all jumps from the quickfix buffer fail because vim-go tries to open `assertions.go` in the current folder instead of the actual location (`$GOPATH/src/github.com/stretchr/testify/assert/assertions.go`).

**Comment by fatih** [comment] 2015-04-29 16:29
This is clearly only happening for certain things. I need more info so I can reproduce it on my localhost. Eventuall I would like to get the following information:

1. Two files, one main and one main_test.go that fails
2. Go version
3. Operating system

**Comment by mlafeldt** [comment] 2015-04-29 16:37
Sure.

```go
// main.go
package main

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestDoSomething(t *testing.T) {
	assert.False(t, doSomething())
}
```

```go
// main_test.go
package main

func doSomething() bool {
	return true
}

func main() {
	doSomething()
}
```

```
[vimgo]$ pwd
/Users/mlafeldt/devel/go/src/github.com/mlafeldt/vimgo
[vimgo]$ go env
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mlafeldt/devel/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.4.2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.4.2/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

**Comment by mlafeldt** [comment] 2015-04-29 16:39
Also, the output looks really weird. Might be related to my Terminal (iTerm 2.1)?

![screenshot 2015-04-29 18 38 24](https://cloud.githubusercontent.com/assets/158074/7396131/f32d0048-ee9e-11e4-840d-3be75d21a49a.png)

**Comment by fatih** [comment] 2015-04-29 16:47
@mlafeldt last question, what happens if you set: 

```viml
let g:go_jump_to_error = 0
```

in your vimrc?

**Comment by mlafeldt** [comment] 2015-04-29 16:51
Then I get this output:

![screenshot 2015-04-29 18 50 44](https://cloud.githubusercontent.com/assets/158074/7396354/a9ff18aa-eea0-11e4-9e14-bc6295b7941f.png)

Note that this time the filename was expanded, although it's still wrong.

**Comment by fatih** [comment] 2015-04-29 16:53
Thanks @mlafeldt for the logs and quick response. I'm on it and will look at it today (if not tomorrow).

**Comment by fatih** [comment] 2015-04-29 21:06
@mlafeldt this is because it's not using standard testing library :/ You are using `testify` and it's output is totally different than what go test outputs:

Should be : 

```
--- FAIL: TestExample (0.00s)
	demo_test.go:10: error message
```

Have:

```
--- FAIL: TestDoSomething (0.00s)
        Location:       demo_test.go:10
	Error:		Should be false
```

As @nowk has stated, this is due to third party libraries. And unfortunately vim-go doesn't have support for third party packages. What we can do in the future is, to let people define their own custom syntax for testing. Currently it's in the form of : 

```viml
let tokens = matchlist(line, '^\s*\(.\{-}\):\(\d\+\):\s*\(.*\)')
```

Here the matching line matches exactly what the default testing package outputs:

```
fileName:lineNumber:text
```

For `testify`, we need multiline parsing. It's possible in Vim, though it needs some work. And as said previously, it should be a setting parameter where one can provide their own syntax. I'll close this Issue as there is not much I can do here. To prevent having an empty buffer just add this:

```viml
let g:go_jump_to_error = 0
```

**Comment by mlafeldt** [comment] 2015-04-30 08:09
@fatih You're right as far as `testify` is concerned.

Unfortunately, the other case I reported is still a problem:

> By looking at `%` in vim, I found out that the problem is caused by a wrong file path where the package path is missing. As a result, jumping to the source location in question only works with files in the current folder.

To trigger the bug, I moved the test to a subfolder and removed the `testify` dependency:

```go
// subfolder/main_test.go
package main

import "testing"

func TestDoSomething(t *testing.T) {
	if doSomething() == true {
		t.Fatal("something went wrong")
	}
}
```

The result:

![screenshot 2015-04-30 10 04 55](https://cloud.githubusercontent.com/assets/158074/7408764/71766f6c-ef20-11e4-846c-993aad7de119.png)

As you can see, vim-go tries to open `main_test.go` in the directory I've started vim from instead of the actual package path (`subfolder/`).

**Comment by fatih** [comment] 2015-04-30 08:16
From where are you calling the test? I suppose you opened the main_test.go and called `:GoTestFunc` right? Also if you change the package, how is main suppose to find `doSomething`? I'm confused about the layout right now. This is how the code is layout, and when It's totally fine. Is it wrong ?

![image](https://cloud.githubusercontent.com/assets/438920/7408890/57cdcc72-ef2a-11e4-9c6e-efee34ea0537.png)

**Comment by mlafeldt** [comment] 2015-04-30 08:23
That's the testing layout:

```
$ tree
.
└── subfolder
    ├── main.go
    └── main_test.go

1 directory, 2 files
```

I run vim in the project root and then open `subfolder/main_test.go`.

**Comment by fatih** [comment] 2015-04-30 08:42
Ok can confirm now. The issue is I couldn't reproduce it myself because I have `BufEnter` that changes the current directory to the opened buffer's directory. I've disabled it and I could reproduce it, which is a good thing.

The problem is caused by this: 

https://github.com/fatih/vim-go/commit/0d1e8c945481128ec7e17b51780a85af5046224d

Now if you are not in the same directory, this causes `fnamemodify(tokens[1], ':p')` to create the path `/Users/demo/demo_test.go`, however the previous expression `expand("%:p:h:") . "/" . tokens[1]` had the reference to the buffer content (via `%`), therefore it would generate `/Users/demo/subfolder/demo_test.go`. 

Even if you don't use `BufEnter` as I do, because the previous had a reference to the current buffer file it would produce correct lines. I think this i also why https://github.com/fatih/vim-go/issues/404 fails too.

I'm looking into a solution now.

**Comment by fatih** [comment] 2015-04-30 09:11
@mlafeldt can you test https://github.com/fatih/vim-go/pull/405 please ?

**Comment by mlafeldt** [comment] 2015-04-30 10:56
That one works for me. :)

**Comment by fatih** [comment] 2015-05-03 07:59
Closing as this is fixed with #405.

**Closed by fatih** 2015-05-03 07:59 UTC
Labels: bug

**Comment by sashaweiss** [comment] 2018-01-03 19:40
Hey all - should `let g:go_jump_to_error = 0` still be a working solution to this? I'm running into the first issue described above, and adding that line to my .vimrc doesn't seem to change anything.

Thanks!

**Comment by bhcleek** [comment] 2018-01-03 19:44
@sashaweiss Can you open a new issue with replication steps for what you're seeing?
