### ISSUE TITLE
Disable Location List Errors

### ISSUE THREAD

**Issue by ddelnano** [fatih/vim-go#989] opened 2016-08-02 12:00 UTC
When using vim-go, I find it very distracting that the location list pops open like in the following screenshot.

<img width="1095" alt="screen shot 2016-08-02 at 7 55 25 am" src="https://cloud.githubusercontent.com/assets/5855593/17327520/8749bdd2-5886-11e6-9fe3-6fe741e2b64a.png">

It works fine most of the time, however, when I am moving between tmux panes or vim splits just as a location list is about to open up it causes issues.

I am trying to disable the location list or close it upon opening.  I have tried adding autocommands for `BufWritePost` and `QuickFixCmdPost` to execute `:lcl` and the autocommands must be running before in the case of `BufWritePost` and not at all for `QuickFixCmdPost` (since it is the location list and not quick fix).  In addition to that, I tried to set the location list height to 0 with the following with no luck.
```vim
let g:go_list_height = 0
```

Is there an easy way to configure this?  I have had problems trying to search around for solutions and need to dig into the code but was wondering if anyone had an easy solution.

Thanks in advance.

**Comment by fatih** [comment] 2016-08-02 14:37
Hi @ddelnano 

You need to give more info. How does this happens? What do you doo? We have a `issue` template with some questions but you didn't follow it and filled. Those questions are important, please don't remove them as I am not able to help you. I'm closing this, please open another issue with the questions filled so I can see what the problem is. Thanks.

**Closed by fatih** 2016-08-02 14:37 UTC

**Comment by oryband** [comment] 2016-08-03 08:50
:+1: I too would like the locationlist and quickfix lists to be populated on autosave, but not having them pop up automatically. This is possible in syntastic by setting `let g:syntastic_auto_loc_list = 2`.

**Comment by ddelnano** [comment] 2016-08-03 11:05
@oryband unfortunately I am using Neomake now and have removed syntastic.  I am not sure if some Neomake setting will allow for this or not.  I was just hoping there was some autocmd event I could hook into to execute `:lcl` close (since doing that manually after it opens closes it), but I have been unable to find that.

**Comment by oryband** [comment] 2016-08-11 11:03
@fatih ping
