### ISSUE TITLE
GoRun says go run: no go files listed 

### ISSUE THREAD

**Issue by poxu** [fatih/vim-go#537] opened 2015-09-12 20:30 UTC
I'm trying to launch simple hello world. But when I type :GoRun the result is go run: no go files listed.
Writing go run hello.go it a console works just fine. Writing !go run hello.go from within vim is just fine also. GoFmt works, GoBuild works.

What can be wrong?

**Comment by poxu** [comment] 2015-09-13 15:00
I tried to use vim-go in console version of vim, shipped with msys2. It seems it doesn't pass the path to current file to GoRun. I tried a pure windows installation and it works.

**Comment by fatih** [comment] 2015-09-14 11:49
Hi @poxu. Can you give more detail please? There is no problem on my side. What happens when you call it? I don't know what msys2 is, vim should work with pure Vim installations. It seems you fixed it so I'm closing this issue, however If you still see an error please open with a detailed reproducible test case so I know how to get the error. Thanks.

**Closed by fatih** 2015-09-14 11:49 UTC

**Comment by poxu** [comment] 2015-09-14 20:31
msys2 is a fork of cygwin. Unix environment for windows. From user perspective it is a collection of unix programs, working on top of windows. It has a package manager, ported from Arch.

Among other unix software it has vim, which has problem with GoRun . The problem is that GoRun thinks that file to run isn't supplied.

If I try windows version of vim, downloaded and installed from official site, everything is fine, but I mostly use version of vim, shipped with msys2.

Maybe the problem is that current file name is not passed properly to the command. I'm not good with vimscript, but maybe you could write a short script, which detects current file name like GoRun does? I could use it to check if the problem is passing current file name.

**Comment by shawnbon206** [comment] 2015-10-15 20:59
":!go run %" works

":GoRun" doesn't
":GoRun" doesn't

I am using the same as poxu, cygwin installed vim. this is because making native gvim for windows play nice with a unix shell is a nightmare.

**Comment by shoulinwang** [comment] 2015-12-19 08:09
check the &ssl in vim

```vim
echo &ssl
```
&ssl=1 will lead to this issue

you can try unset it 

```vim
set nossh
```
