### ISSUE TITLE
vim-go: Updating gometalinter error

### ISSUE THREAD

**Issue by lukatendai** [fatih/vim-go#2251] opened 2019-04-29 16:57 UTC
### What did you do? (required. The issue will be **closed** when not provided.)
GoUpdateBinaries

### What did you expect to happen?
update all binaries

### What happened instead?
vim-go: Updating gometalinter. Reinstalling github.com/alecthomas/gometalinter to folder /home/luke/go/bin/
Error installing github.com/alecthomas/gometalinter: # github.com/alecthomas/gometalinter^@../../../../pkg/mod/github.com/alecthomas/gometalinter@v3.0.0+incompatible/main.go:36:94: cannot use loadConfig (type func(*kingpin.Application, *kingpin.ParseElement, *kingpin.ParseContext) error) as type kingpin.Action in argument to app.cmdMixin.flagGroup.Flag("config", "Load JSON configu
ration from file.").Envar("GOMETALINTER_CONFIG").Action^@../../../../pkg/mod/github.com/alecthomas/gometalinter@v3.0.0+incompatible/main.go:38:100: cannot use disableAction (type func(*kingpin.Application, *kingpin.ParseElement, *kingpin.ParseContext) error) as type kingpin.Action in argument to app.cmdMixin.flagGroup.Flag("disable", "Disable previously enabled linters.").PlaceHol
der("LINTER").Short('D').Action^@../../../../pkg/mod/github.com/alecthomas/gometalinter@v3.0.0+incompatible/main.go:39:99: cannot use enableAction (type func(*kingpin.Application, *kingpin.ParseElement, *kingpin.ParseContext) error) as type kingpin.Action in argument to app.cmdMixin.flagGroup.Flag("enable", "Enable previously disabled linters.").PlaceHolder("LINTER").Short('E').Ac
tion^@../../../../pkg/mod/github.com/alecthomas/gometalinter@v3.0.0+incompatible/main.go:40:83: cannot use cliLinterOverrides (type func(*kingpin.Application, *kingpin.ParseElement, *kingpin.ParseContext) error) as type kingpin.Action in argument to app.cmdMixin.flagGroup.Flag("linter", "Define a linter.").PlaceHolder("NAME:COMMAND:PATTERN").Action^@../../../../pkg/mod/github.com/
alecthomas/gometalinter@v3.0.0+incompatible/main.go:43:56: cannot use disableAllAction (type func(*kingpin.Application, *kingpin.ParseElement, *kingpin.ParseContext) error) as type kingpin.Action in argument to app.cmdMixin.flagGroup.Flag("disable-all", "Disable all linters.").Action^@../../../../pkg/mod/github.com/alecthomas/gometalinter@v3.0.0+incompatible/main.go:44:54: cannot
use enableAllAction (type func(*kingpin.Application, *kingpin.ParseElement, *kingpin.ParseContext) error) as type kingpin.Action in argument to app.cmdMixin.flagGroup.Flag("enable-all", "Enable all linters.").Action^@../../../../pkg/mod/github.com/alecthomas/gometalinter@v3.0.0+incompatible/main.go:200:12: cannot use loadDefaultConfig (type func(*kingpin.Application, *kingpin.Pars
eElement, *kingpin.ParseContext) error) as type kingpin.Action in argument to app.Action^@

### Configuration (**MUST** fill this out):

* vim-go version:
latest
* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

* Vim version (first three lines from `:version`):
NVIM v0.4.0-657-ga0d723db5
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/lu
ke/workspace/neovim/build/config -I/home/luke/workspace/neovim/src -I/home/luke/workspace/neovim/.deps/usr/include -I/usr/include -I/home/luke/workspace/neovim/build/src/nvim/auto -I/home/luke/workspace/neovim/build/include
Compiled by luke@x1-think

* Go version (`go version`):
go version go1.12.4 linux/amd64

* Go environment (`go env`):
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/luke/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/luke/go"
GOPROXY=""
GORACE="log_path=/home/luke/tmp/race/report"
GOROOT="/home/luke/bin/go"
GOTMPDIR=""
GOTOOLDIR="/home/luke/bin/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build542241130=/tmp/go-build -gno-record-gcc-switches"

**Comment by bhcleek** [comment] 2019-04-29 18:04
Duplicate of #2248

**Closed by bhcleek** 2019-04-29 18:04 UTC

**Comment by bhcleek** [comment] 2019-04-29 22:45
In case it's not clear, make sure that your working directory is within `$GOPATH` when you `:GoUpdateBinaries`.

**Comment by lukatendai** [comment] 2019-04-29 23:11
I do... But I think is a good module problem... There is one more package
that has similar bot not the same issue... Already submitted issue there

**Comment by lukatendai** [comment] 2019-04-29 23:12
*go module issue
