### ISSUE TITLE
Splitting buffer vertically shifts cursor.

### ISSUE THREAD

**Issue by turnage** [fatih/vim-go#995] opened 2016-08-05 18:50 UTC
Hi! Thank you for vim-go!

### Actual behavior

When splitting vertical to make another buffer with `:vs`, the current buffer jumps the cursor much lower in the file.

### Expected behavior

The cursor in the first buffer remains where it is when running `:vs`.

### Steps to reproduce:

1. Install vim
2. Install vim-go with [vim-plug](https://github.com/junegunn/vim-plug)
3. Open a file which fills more than the vertical length of your vim buffer and leave scroll space at the bottom.
4. Run `:vs` to split the buffer.

### Configuration

.vimrc:
````
syntax enable
set colorcolumn=81
hi ColorColumn ctermbg=White
set nu
set shiftwidth=8
set softtabstop=8
set linebreak
set tw=80

call plug#begin('~/.vim/plugged')

Plug 'fatih/vim-go'

call plug#end()
````

vim-go is up to date as of this post.
vim version is 7.3
go version is 1.6.2

**Comment by fatih** [comment] 2016-08-08 00:19
Hi @turnage. I couldn't produce it. Can you provide a reproducible case, a test repo maybe or a file. Because I'm not sure why vim-go should affect a simple `:vs` ? We don't touch or anything. This is pure Vim feature.

**Comment by Carpetsmoker** [comment] 2016-08-08 02:46
Note that Vim 7.3 is quite old. You didn't specify a patch level, but the last 7.3.X release was from July 2013.

I suggest you try Vim 7.4 *with the latest patch level* and check if you still has the same problem. Your Linux distribution probably doesn't provide newer packages, but you can maybe find newer binaries for your system, or you can compile Vim from source (which is usually not that hard).

**Comment by fatih** [comment] 2016-09-04 13:50
I'm closing this as there are no replies for ~1 months. I think it's because 7.3.x is used. Please reopen again if it still happens with 7.4.x

**Closed by fatih** 2016-09-04 13:50 UTC
