### ISSUE TITLE
guru: flag provided but not defined: -format

### ISSUE THREAD

**Issue by myitcv** [fatih/vim-go#796] opened 2016-04-13 08:25 UTC
### Actual behavior

A call to `:GoReferrers` (or any other `guru`-based command) should work

### Expected behavior

Error because of incorrect flag usage

### Steps to reproduce:

Please create a reproducible case of your problem. Re produce it 
with a minimal `vimrc` with all plugins disabled and only `vim-go`
enabled:

1. Open a `.go` file
2. Hover over an identifier
3. Invoke `:GoReferrers` (or indeed any command that calls through to `guru`)
4. Observe the following output:

```
vim-go: flag provided but not defined: -format
Run 'guru -help' for more information.
```

### Configuration

Add here your current configuration and additional information that might be
useful, such as:

* `vimrc` you used to reproduce: nothing non-standard
* vim version: NVIM v0.1.4-23-gf47a20a
* `vim-go` version: 3a596f5bf8ed3d37b5fb9dc1f107a49cbd80eae4
* `go version`: 1.6.1
* `guru` version: https://github.com/golang/tools/tree/c3291436fa3bc9d4246ad2434b89496fd7c85089

**Comment by fatih** [comment] 2016-04-13 09:07
Hi @myitcv It's because 1-2 days Guru changed completely again. I'll fix it. Thanks for the reporting

**Comment by myitcv** [comment] 2016-04-13 09:09
@fatih thanks. I suspect as much. Does suggest that `vim-go` should be using vendored binaries....agree?

**Comment by fatih** [comment] 2016-04-13 09:23
CL that breaks this: https://go-review.googlesource.com/#/c/21397/

@myitcv yeah, the problem is that guru doesn't have versions or whatever, so even if it's vendored, it's not sufficient enough, as we don't know in which state the binary was built. I'm thinking of using github.com/vim-go to have vendored source code or binaries, but it would be an overkill for now. That's why I occasionally receive issues like this, which I think is ok.

**Comment by Cymonn** [comment] 2016-04-13 10:22
I think temporarily commenting out following line in file **guru.vim** would be work correctly before updated.

> 22:"    let command .= printf(" -format %s", a:format)

**Comment by fatih** [comment] 2016-04-13 10:48
The fix is in master. Thanks for the opening the issue again.

**Closed** 2016-04-13 10:48 UTC

**Comment by myitcv** [comment] 2016-04-13 11:00
@fatih 

>  guru doesn't have versions or whatever

But there is the concept of commits which is ultimately far stronger. `vim-go` should probably pin itself to specific commits of its dependencies. Whether it vendors the code or not is really neither her nor there - ideally it should in case the dependencies or their repos disappear (etc, the whole vendoring discussion could be replayed here)

This would mean however that `vim-go` would no longer be able to rely on `guru` etc being on a `PATH` (because there is no way of knowing what commit such a binary corresponds to) and instead would need to build its own (or download cross compiled versions at specific commits from a cache etc)

Thanks for the fix in any case
