### ISSUE TITLE
Omni completion does not do fuzzy matching

### ISSUE THREAD

**Issue by mahdix** [fatih/vim-go#2899] opened 2020-05-28 01:47 UTC
### What did you do? (required: The issue will be **closed** when not provided)

I activate auto-complete in a Go source code and part of a method name.
- My vimrc has enabled fuzzy matcher for gopls.

### What did you expect to happen?

I expect to have fuzzy matching. For example when I type `H` and there are two methods in the autocomplete menu (`Html` and `AfterHtml`), I expect to see both of these in the list. 

### What happened instead?

I only see items that start with what I have typed (in above example, only `Html`).

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>

</pre></details>

#### Vim version (first three lines from `:version`):

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 18 2020 18:29:15)
Included patches: 1-1453
Modified by pkg-vim-maintainers@lists.alioth.debian.org

#### Go version (`go version`):

go version go1.14.3 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/docker/.cache/go-build"
GOENV="/home/docker/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/docker/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build699015466=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls 0.4.1
    golang.org/x/tools/gopls@v0.4.1 h1:0e3BPxGV4B3cd0zdMuccwW72SgmHp92lAjOyxX/ScAw=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_auto_type_info = 1
g:go_jump_to_error = 1
g:go_loaded_gosnippets = 1
g:go_gopls_matcher = 'fuzzy'
g:go_loaded_install = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by bhcleek** [comment] 2020-05-28 04:08
Can you do try that matching with `let g:go_gopls=['lsp']` added to your vimrc and provide the lsp debug log here?

/cc @stamblerre

**Comment by bhcleek** [comment] 2020-05-30 16:01
@mahdix Have you isolated the problem you describe to vim-go? Using vim-go's autocompletion, I see the result you expect:
<img width="253" alt="Screen Shot 2020-05-30 at 08 58 33" src="https://user-images.githubusercontent.com/1958864/83333150-0c90f300-a254-11ea-8d54-4168482f84a3.png">

**Comment by mahdix** [comment] 2020-05-31 05:02
@bhcleek 
Thanks for your reply. I have enabled `lsp` option and vim log file is attached. 

Before typing:
![image](https://user-images.githubusercontent.com/9294049/83344832-f5114300-a303-11ea-9950-1bed871e88d4.png)

After typing `Html`:
![image](https://user-images.githubusercontent.com/9294049/83344838-00646e80-a304-11ea-887d-c077f25935cd.png)

As you can see `AfterHtml` is not shown in the list.

[myVim.log](https://github.com/fatih/vim-go/files/4707112/myVim.log)

**Comment by mahdix** [comment] 2020-05-31 05:08
Ok. I emptied my vimrc and allowed only vim-go plugin and now it seems to be working:

![image](https://user-images.githubusercontent.com/9294049/83344916-1a528100-a305-11ea-9c53-29bc766ed3c1.png)

**Comment by mahdix** [comment] 2020-05-31 06:09
And with full vimrc and plugins, still an isolated example does not work as intended:

![image](https://user-images.githubusercontent.com/9294049/83345648-981a8a80-a30d-11ea-8aa4-32dea58f1a7b.png)

**Comment by bhcleek** [comment] 2020-05-31 15:26
You've confirmed that it works with only vim-go; the problem you're seeing is likely _not_ because of vim-go; do you have other plugins that configure your autocompletion? With your full vimrc and a go file active, what does `:set omnifunc?` report?

**Comment by mahdix** [comment] 2020-05-31 15:28
Thanks. Will check that.
The confusing part is that even with a fresh Ubuntu docker image and installing everything (vim, go, vim-go), still I don't have the fuzzy completion. 
![image](https://user-images.githubusercontent.com/9294049/83356119-c2933480-a35b-11ea-8e23-731e0c230059.png)

**Comment by mahdix** [comment] 2020-06-01 08:07
`  omnifunc=go#complete#Complete`
This looks like an issue/bug with gopls. Is there a way to inspect/debug `gopls` output for some input?

**Comment by bhcleek** [comment] 2020-06-01 15:55
https://github.com/fatih/vim-go/issues/2899#issuecomment-635085471

**Comment by bhcleek** [comment] 2020-06-06 19:04
@mahdix can you provide the gopls debug output so we can see what's being sent and further analyze what you're seeing, or should we close this issue?

**Comment by bhcleek** [comment] 2020-06-13 17:27
closing for lack of feedback

**Comment by mahdix** [comment] 2020-06-13 22:50
Sorry for the delay. I thought I had sent the debug logs in response to the original comment (#2899): https://github.com/fatih/vim-go/issues/2899#issuecomment-636422357

**Comment by bhcleek** [comment] 2020-06-13 22:56
Thanks, @mahdix . Those aren't the logs I need. The ones I need can be created by adding `let g:go_debug=['lsp']` to your vimrc and duplicating the problem.

I see now that I originally misspelled the global variable name; I'm correcting that in the original comment, too.

**Comment by mahdix** [comment] 2020-06-13 23:24
Thanks. I re-did the test on my Mac directly (not in a docker).

Looks like I still have the issue (but tbh on my Mac I have some other plugins installed on my vim):
![image](https://user-images.githubusercontent.com/9294049/84580993-75d84080-add4-11ea-95a2-3f2d2aa98416.png)

Debug log:  
[vim_go_lsp_debug_log.txt](https://github.com/fatih/vim-go/files/4775650/vim_go_lsp_debug_log.txt)

But after another try, looks like it worked:
![image](https://user-images.githubusercontent.com/9294049/84581066-21819080-add5-11ea-97a7-4253c1062d89.png)

New log: 
[vim_go_lsp_debug_log_working.txt](https://github.com/fatih/vim-go/files/4775651/vim_go_lsp_debug_log_working.txt)

which is confusing.
My vim-go related settings in vimrc:
```vimrc
au filetype go inoremap <buffer> <Nul> <C-x><C-o>
au filetype go inoremap <buffer> <C-j> <C-n>
au filetype go inoremap <buffer> <C-k> <C-p>
let g:go_auto_type_info = 1           " Automatically get signature/type info for object under cursor
let g:go_gopls_matcher = 'fuzzy'
let g:go_debug=['lsp']
```

**Comment by bhcleek** [comment] 2020-06-14 00:22
I'm still seeing the behavior that you expect and I can't duplicate the problems you're describing.

In the first case you provided above, something seems amiss: I can't think of any reason that `__GOLSP_LOG__` would show up in the completion candidates and strangely it appears that `gopls` didn't return any candidates according to [vim_go_lsp_debug_log.txt](https://github.com/fatih/vim-go/files/4775650/vim_go_lsp_debug_log.txt): 
```
{"jsonrpc":"2.0","result":{"isIncomplete":false,"items":[]},"id":4}
```
So I'm not sure why it would have displayed _any_ completion candidates. 🤔 

In the second case you provided above, it looks like you haven't typed anything after the `.`; so of course all methods of `h` are completion candidates. I'm surprised that `Render` isn't showing up there, though 🤔

In https://github.com/fatih/vim-go/issues/2899#issuecomment-636422778 you said: 
> Ok. I emptied my vimrc and allowed only vim-go plugin and now it seems to be working:

But then in https://github.com/fatih/vim-go/issues/2899#issuecomment-636428109 you said:
> And with full vimrc and plugins, still an isolated example does not work as intended:

And finally in https://github.com/fatih/vim-go/issues/2899#issuecomment-636683922 you said:
> omnifunc=go#complete#Complete
This looks like an issue/bug with gopls. Is there a way to inspect/debug gopls output for some input?

These three things together make me thing that perhaps you have an older version of vim-go  or another plugin loaded. After opening a go file and trying autocompletion can you run `verbose function go#complete#Complete` and provide the full output here?

My last thought is that I wonder if this has something to do with the version of Vim that you're using. In your original report you said you're using 8.0.1453. Is it possible for you to upgrade Vim and see if that affects anything for you? But there's other things to try first. Keep reading 😁

**Comment by mahdix** [comment] 2020-06-14 01:59
Thanks for your reply.

> In the second case you provided above, it looks like you haven't typed anything after the .; so of course all methods of h are completion candidates. I'm surprised that Render isn't showing up there, though

I had types something. I think I typed `Ht` and then pressed C-x C-o but then it deleted what I had typed and showed that list.

**Comment by bhcleek** [comment] 2020-06-23 00:06
@mahdix do you still want help with this? If so, then I can continue to wait for the information that I requested in my previous comment.

**Comment by mahdix** [comment] 2020-06-23 04:02
Hey Billie,

Please close the ticket. I am not sure when I will be able to test this
again and I don't want to keep you waiting.

**Comment by bhcleek** [comment] 2020-06-23 04:33
Ok. I'll close it for now, but if you pick this back up and want to get to the bottom of it, just open a new issue and reference this one; I'll open it back up for you so we can continue the conversation if you're still seeing the same behavior.

**Closed by bhcleek** 2020-06-23 04:33 UTC
