### ISSUE TITLE
Get <SNR>152_on_stdout  error after  file`s saved.

### ISSUE THREAD

**Issue by zk4** [fatih/vim-go#2750] opened 2020-02-28 08:11 UTC
### What did you do? (required: The issue will be **closed** when not provided)
Save the go file in nvim. 

### What did you expect to happen?
Just saved the file with no error.
### What happened instead?
get error info:
vim-go: function <SNR>152_on_stdout[1]..<SNR>152_neocb[58]..296[10]..299[3]..300[2]..301, line 52: Vim(if):E716: Key not present in Dictionary: version == l:version
### Configuration (**MUST** fill this out):
![image](https://user-images.githubusercontent.com/996674/75522317-ae7e2500-5a44-11ea-95db-ccce9154965e.png)

#### vim-go version:
git commit be888d7761a2e6948a220623bf75962bd189bad4

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>

</pre></details>

#### Vim version (first three lines from `:version`):

NVIM v0.5.0-370-g5d5b068d5
Build type: Release
LuaJIT 2.1.0-beta3

#### Go version (`go version`):

go version go1.13.1 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls 0.2.2
    golang.org/x/tools/gopls@v0.2.2 h1:ujGisyytgY1VGcmd66wIJ9+wVAfmodXj6daHM43HRXk=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_list_type = 'quickfix'
g:go_def_mode = 'gopls'
g:go_fmt_command = 'goimports'
g:go_jump_to_error = 1
g:go_loaded_gosnippets = 1
g:go_loaded_install = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by skipcloud** [comment] 2020-02-28 09:27
I'm getting something similar 
```
vim-go: function 273[10]..276[3]..277[2]..278, line 52: Vim(if):E716: Key not present in Dictionary: version == l:version
```

vim version
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 15 2019 16:41:15)
Included patches: 1-875, 878, 884, 948, 1046, 1365-1368, 1382, 1401
```

vim-go commit `be888d7`

**Comment by skipcloud** [comment] 2020-02-28 09:48
git bisect is telling me this commit is when the error was introduced 
`0df29414a4c45ed1f386605e4946cb8bf30a3e3f`

**Comment by zk4** [comment] 2020-02-28 11:02
> git bisect is telling me this commit is when the error was introduced
> `0df29414a4c45ed1f386605e4946cb8bf30a3e3f`

but this commit does not support
```
let g:go_def_mode = 'gopls'
```

**Comment by bhcleek** [comment] 2020-02-28 15:10
Duplicate of #2748

**Closed by bhcleek** 2020-02-28 15:10 UTC
