### ISSUE TITLE
How to get buffer-local g:go_gopls_local effect

### ISSUE THREAD

**Issue by powerman** [fatih/vim-go#3023] opened 2020-09-21 22:46 UTC
Is there a way to get same effect as this (from vim-go docs):
```vim
  autocmd FileType go let b:go_fmt_options = {
    \ 'goimports': '-local ' .
      \ trim(system('{cd '. shellescape(expand('%:h')) .' && go list -m;}')),
    \ }
```
when using `let g:go_imports_mode = 'gopls'`?

This works, but it isn't buffer-local, so when I've opened files from several projects at once it doesn't work correctly:
```vim
let g:go_gopls_local = trim(system('{cd '. shellescape(expand('%:h')) .' && go list -m;}'))
```

I've also tried to move this into `autocmd BufEnter *.go`… which is probably works but in general it feels wrong to change global vars this way and also it result in huge delay on first save in different buffer (I suppose it's because gopls re-initialize for new project specific to current buffer).

**Comment by bhcleek** [comment] 2020-09-22 00:27
It's not possible with vim-go currently to fully replicate what you're doing with goimports.

You can control the local imports using `g:go_gopls_local` (e.g. `let g:go_gopls_local = "do"`), but at present the same value is used for all workspaces.

**Comment by powerman** [comment] 2020-09-22 00:37
If you'll decide to work on improving this it may make sense to add native support for common use case "separate imports related to current module" instead of random prefix, to avoid needs in running `go list -m` from vimrc all of time. Ideally it should be a gopls flag (сс: @stamblerre).

**Comment by bhcleek** [comment] 2020-09-22 00:56
If `gopls` supported that, then it would certainly be possible for vim-go to support it. However, I think that the current `gopls` option is sufficient. It's relatively straightforward to add better support to vim-go for varying settings by workspace/module.

**Comment by bhcleek** [comment] 2020-09-22 15:18
@powerman I realized that it _is_ mostly possible to do this with current features in vim-go. I'll write up some instructions for you later today.

**Comment by bhcleek** [comment] 2020-09-24 01:38
After looking at vim-go's features again, it doesn't support what you're trying to do here in a way that you can rely on.

As I'm considering how to do this, can you explain your workflow a little bit? A `gopls` debug log (`let g:go_debug=['lsp']`) would be helpful, too.

Specifically: 
1. what directory do you start in?
1. do you use `:GoAddWorkspace`?

**Comment by powerman** [comment] 2020-09-24 12:38
I don't use `:GoAddWorkspace` (no idea what's it and when to use it, TBH).
I'm usually run `vim file.go /path/to/other/similar/project/file.go` and do compare and update/sync files (which will open in tabs). Which means I'll modify and change both of them, but they're from different dirs/go modules.

**Comment by bhcleek** [comment] 2020-09-24 15:27
`gopls` works with workspaces, and the local imports prefix is per workspace. If you want to use `let g:go_imports_mode='gopls'` and work with different projects, then you'd need to start using `:GoAddWorkspace` to control your workspaces.

As it currently exists, vim-go applies the same settings to each workspace, but that can be changed relatively easily and I'm working on that in a local branch.

**Comment by bhcleek** [comment] 2020-10-17 18:31
@powerman do you want to give #3053 a try to make sure it provides the behavior you're expecting?

Generally, you'd want to do something like this:
```
let g:go_gopls_local = {}
autocmd FileType go let dir = trim(system('{cd '. shellescape(expand('%:h')) .' && go list -m -f {{.Dir}};}')) | if !has_key(g:go_gopls_local, dir) | let g:go_gopls_local[trim(system('{cd '. shellescape(expand('%:h')) .' && go list -m;}'))] = dir | endif
```

**Comment by powerman** [comment] 2020-10-17 18:43
Yes, thanks, I'll try it now… just need to figure out how to pull commit from non-origin repo using `git subrepo` (which I use to manage vim plugins).

**Comment by bhcleek** [comment] 2020-10-17 18:47
Be aware that I haven't tested that particular incantation, but the concept is right.

**Comment by bhcleek** [comment] 2020-10-17 18:49
If you like git subrepo, you might want to check out git subtree - it ships with git; I find it to be a much better experience than submodules. I use it to manage my vim plugins.

**Comment by bhcleek** [comment] 2020-10-17 18:50
Oh, and you _can_ pull directly from fatih/vim-go: use `refs/pull/3053/head` as the ref

**Comment by powerman** [comment] 2020-10-17 19:10
No, looks like it doesn't work.

I belive key/value in your example above should be swapped, i.e. it should be:
```vim
let g:go_gopls_local = {}
autocmd FileType go let dir = trim(system('{cd '. shellescape(expand('%:h')) .' && go list -m -f {{.Dir}};}')) | if !has_key(g:go_gopls_local, dir) | let g:go_gopls_local[dir] = trim(system('{cd '. shellescape(expand('%:h')) .' && go list -m;}')) | endif
```
But in both cases I found local import prefix doesn't work anymore, even when just a single file is opened.

**Comment by bhcleek** [comment] 2020-10-17 19:15
You're right; the key and value need to be swapped. Try this in your vimrc, it works for me:
```
let g:go_gopls_local = {}

function! s:setlocal() abort
try
  let l:dir = expand('%:p:h')
	let l:olddir = chdir(l:dir)
  if !has_key(g:go_gopls_local, l:dir)
    let g:go_gopls_local[l:dir] = trim(system('go list -m'))
  endif
catch
  echom printf('at %s: %s', v:throwpoint, v:exception)
finally
	call chdir(l:olddir)
endtry
endfunction

autocmd FileType go call s:setlocal()
```

**Comment by powerman** [comment] 2020-10-17 19:21
Nope, this one doesn't work too.

I've just saved the file, so imports should be rearranged into three paragraphs, but this isn't happens. Also I've added output of `echo g:go_gopls_local` on same screen:

![изображение](https://user-images.githubusercontent.com/1354301/96351839-85d39a00-10be-11eb-9b55-b9089d04642d.png)

Vim was started by (starting from go module's root): `cd ms/example/internal/config; vi config.go`.

**Comment by powerman** [comment] 2020-10-17 19:24
Here is my whole vim-go related part of vimrc, just in case:

```vim
let g:go_metalinter_command = 'golangci-lint'
let g:go_fmt_fail_silently = 1
let g:go_fmt_command = 'gopls'
let g:go_imports_autosave = 1
let g:go_imports_mode = 'gopls'
let g:go_gopls_gofumpt = v:true
let g:go_gopls_local = trim(system('{cd '. shellescape(expand('%:h')) .' && go list -m;}'))

let g:go_gopls_local = {}
autocmd FileType go call s:setlocal()

function! s:setlocal() abort
try
  let l:dir = expand('%:p:h')
	let l:olddir = chdir(l:dir)
  if !has_key(g:go_gopls_local, l:dir)
    let g:go_gopls_local[l:dir] = trim(system('go list -m'))
  endif
catch
  echom printf('at %s: %s', v:throwpoint, v:exception)
finally
	call chdir(l:olddir)
endtry
endfunction

let g:go_doc_keywordprg_enabled = 0
let g:go_template_use_pkg = 1
let g:go_list_type = 'quickfix'
let g:go_highlight_array_whitespace_error = 1
let g:go_highlight_chan_whitespace_error = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_operators = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_parameters = 0
let g:go_highlight_function_calls = 1
let g:go_highlight_types = 1
let g:go_highlight_fields = 0
let g:go_highlight_build_constraints = 1
let g:go_highlight_generate_tags = 1
let g:go_highlight_string_spellcheck = 1
let g:go_highlight_format_strings = 1
let g:go_highlight_variable_declarations = 0
let g:go_highlight_variable_assignments = 0
let g:go_build_tags = 'integration'
let g:go_gopls_matcher = 'caseSensitive'
let g:go_gopls_deep_completion = 0
let g:go_gopls_temp_modfile = 1
let g:go_gopls_use_placeholders = 1
autocmd FileType go nmap <buffer> <nowait> <Leader>r     <Plug>(go-run)
autocmd FileType go nmap <buffer> <nowait> <Leader>b     <Plug>(go-build)
autocmd FileType go nmap <buffer> <nowait> <Leader>t     <Plug>(go-test)
autocmd FileType go nmap <buffer> <nowait> <Leader>T     <Plug>(go-test-func)
autocmd FileType go nmap <buffer> <nowait> <Leader>c     <Plug>(go-coverage-toggle)
autocmd FileType go nmap <buffer> <nowait> <Leader>gd    <Plug>(go-def-tab)
autocmd FileType go nmap <buffer> <nowait> <Leader>gb    <Plug>(go-doc-browser)
autocmd FileType go nmap <buffer> <nowait> <Leader>s     <Plug>(go-implements)
autocmd FileType go nmap <buffer> <nowait> <Leader>i     <Plug>(go-info)
autocmd FileType go nmap <buffer> <nowait> <Leader>e     <Plug>(go-rename)
```

**Comment by bhcleek** [comment] 2020-10-17 19:24
Yeah, I think I see what's going on. I'll make a change to #3053 and let you know when I think I have this fixed again. Thank you for your help.

**Comment by bhcleek** [comment] 2020-10-17 20:19
@powerman please give it another try when you have a chance; I was able to find the source of the problem you were encountering and pushed a fix to the PR.

Also, here's a  more correct version of `s:setlocal`:
```
let g:go_gopls_local = {}

function! s:setlocal()
	try
		let l:dir = expand('%:p:h')
		let l:olddir = chdir(l:dir)
		if !has_key(g:go_gopls_local, l:dir)
			let g:go_gopls_local[l:dir] = trim(system('go list -m'))
		endif
	catch
	finally
		call chdir(l:olddir)
	endtry
endfunction
```

**Comment by powerman** [comment] 2020-10-17 20:31
Nope, still doesn't work. This time `echo g:go_gopls_local ` output is `{'/home/powerman/proj/go/go-monolith-example/ms/example/internal/config': 'github.com/powerman/go-mo
nolith-example'}`.

After changing vimrc as shown below, just to make sure, re-running vim and saving the file - imports got reordered into 3 paragraphs, as it should be:
```vim
let g:go_gopls_local = trim(system('{cd '. shellescape(expand('%:h')) .' && go list -m;}'))

" let g:go_gopls_local = {}
" autocmd FileType go call s:setlocal()
```

And yes, I'm using the latest version, e.g.:
```
$ head -n 1110 bundle/go/autoload/go/lsp.vim | tail
  let l:workspaces = []
  for l:dir in a:000
    let l:dir = fnamemodify(l:dir, ':p')
    if len(l:dir) > 1 && l:dir[-1:] == '/'
      let l:dir = l:dir[:-2]
    endif
    if !isdirectory(l:dir)
      continue
    endif

```

**Comment by bhcleek** [comment] 2020-10-17 20:38
I think the code is correct; the problem is the directory key, because I was testing in a file that's at the module root.

Try this:
```
let g:go_gopls_local = {}

function! s:setlocal()
	try
		let l:dir = expand('%:p:h')
		let l:olddir = chdir(l:dir)
		if !has_key(g:go_gopls_local, l:dir)
			let g:go_gopls_local[l:dir] = trim(system('go list -m'))
		endif
	catch
		echom printf('at %s: %s', v:throwpoint, v:exception)
	finally
		call chdir(l:olddir)
	endtry
endfunction
```

**Comment by powerman** [comment] 2020-10-17 20:50
The only difference between these two s:setlocal version is added `echom` line - unlikely it'll change the behaviour… checking… and yes, it doesn't change anything, still doesn't work.

**Comment by bhcleek** [comment] 2020-10-17 21:03
Sorry about that. In a rush, I messed up the copy and paste. I'll give an update later.

In the meantime, you really just need to run `go list -m -f {{.Dir}}` in the buffer directory to get the right key for the dictionary.

**Comment by bhcleek** [comment] 2020-10-17 21:26
```
let g:go_gopls_local = {}

function! s:setlocal()
  try
    let l:olddir = chdir(expand('%:p:h'))
    let l:dir = trim(system('go list -m -f {{.Dir}}'))
    if !has_key(g:go_gopls_local, l:dir)
      let g:go_gopls_local[l:dir] = trim(system('go list -m'))
    endif
  catch
    
  finally
    call chdir(l:olddir)
  endtry
endfunction

autocmd FileType go call s:setlocal()
```

**Comment by powerman** [comment] 2020-10-17 21:38
At a glance - this one works!

I've noticed another one change - before updating to the PR's branch I've updated to latest master and noticed now it'll sometimes freezes for a bit after starting vim and showing opened files and enumerate project's go files in the status/command line for a second, then unfreeze. Looks weird, but it's probably completely unrelated issue to current one.

**Closed** 2020-10-17 22:05 UTC

**Comment by powerman** [comment] 2020-10-18 00:38
Thanks!
