### ISSUE TITLE
Auto-Complete incorrect in function receiver parens

### ISSUE THREAD

**Issue by ldelossa** [fatih/vim-go#2406] opened 2019-07-17 01:01 UTC
### What did you do? (required: The issue will be **closed** when not provided)
Attempted to autocomplete a struct name inside a function receiver like to:

```
func (d *mock<auto complete>) Func1 {}
```

### What did you expect to happen?
A list of existing structs in the code be displayed for selection.

### What happened instead?
List is displayed by first characters are not taken into consideration and selecting from the list does not place the text in the correct spaces

### Configuration (**MUST** fill this out):
https://github.com/ldelossa/dotfiles/blob/master/vimrc#L209-L278

#### vim-go version:
MASTER

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
https://github.com/ldelossa/dotfiles/blob/master/vimrc

#### Vim version (first three lines from `:version`):

NVIM v0.3.8
Build type: Release
LuaJIT 2.0.5

#### Go version (`go version`):

go version go1.12.1 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GOARCH="amd64"
GOBIN="/Users/louis/git/gopath/bin"
GOCACHE="/Users/louis/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/louis/git/gopath"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/louis/git/go/libcscan/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/mc/xwfdd41j1j74xfmcmphbwpgw0000gn/T/go-build775089912=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>
#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_list_type = 'quickfix'
g:go_highlight_operators = 1
g:go_jump_to_error = 1
g:go_term_enabled = 1
g:go_metalinter_deadline = '5s'
g:go_highlight_fields = 1
g:go_metalinter_command = 'golangci-lint'
g:go_def_mode = 'godef'
g:go_disable_autoinstall = 0
g:go_highlight_structs = 1
g:go_highlight_functions = 1
g:go_gotags_bin = 'gotags'
g:go_test_show_name = 1
g:go_test_timeout = '600s'
g:go_highlight_types = 1
g:go_fmt_command = 'goimports'
g:go_highlight_methods = 1
g:go_list_height = 10
g:go_fmt_experimental = 1
g:go_loaded_gosnippets = 1
g:go_term_height = 10
g:go_term_mode = 'split'
g:go_build_tags = 'integration'
g:go_highlight_build_constraints = 1
g:go_loaded_install = 1
g:go_decls_mode = 'fzf'
</pre></details>

**Comment by bhcleek** [comment] 2019-07-17 03:18
Thanks again, @ldelossa.

This is a duplicate of #2405, so I'm closing this one.

**Closed by bhcleek** 2019-07-17 03:18 UTC
