### ISSUE TITLE
Support custom GoFmt command

### ISSUE THREAD

**Issue by sethamclean** [fatih/vim-go#552] opened 2015-09-29 14:05 UTC
gofmt now supports a -s flag that will rewrite map literals (among other things) in the new simplified format. Unfortunately goimports does not support this flag as of yet.

It would be nice to be able to set a gofmt command that could call both, or whatever the user specified.

**Comment by fatih** [comment] 2015-09-29 14:06
Hi @sethamclean , did you read the docs? There is already a command that you can override. Doesn't it work for you?

**Comment by sethamclean** [comment] 2015-09-29 14:15
Maybe I missed something. Are you referring to ```let g:go_fmt_command = "goimports"```? That doesn't seem to pass through command line arguments or support chaining commands. Perhaps I have the syntax wrong.

```vim-go: could not find 'goimports; gofmt -s'. Run :GoInstallBinaries to fix it.```

**Comment by fatih** [comment] 2015-09-29 14:18
Does the following not work for you?

```
let g:go_fmt_command = "gofmt"
let g:go_fmt_options = "-s"
```

**Comment by sethamclean** [comment] 2015-09-29 14:19
Yes that works. Thank you for clarifying. Is there a way to then run goimports on the source file? I know this isn't efficient but goimports doesn't seem to support the -s option at this time.

**Comment by fatih** [comment] 2015-09-29 14:23
No, unfortunately we don't support such feature. It would bring complexity to the code base and it's probably a feature that only certain users would use :) I'm closing this issue as this is now resolved. Feel free to open an issue if you have other problems or if something is not working as intended.

**Closed by fatih** 2015-09-29 14:23 UTC
