### ISSUE TITLE
Default GOPATH not respected in vim-go

### ISSUE THREAD

**Issue by spf13** [fatih/vim-go#1243] opened 2017-03-24 12:19 UTC
This is related to #1208 but I believe the problem is more widespread.

When the environment variable $GOPATH isn't set, Go 1.8 uses $HOME/go as the default. 
In Vim the function :GoPath returns this path as expected however many operations depending on the $GOPATH being set don't work properly.

Vim-go can't identify the "Go binaries" are installed and a message is provided saying they aren't installed.
GoInstallBinaries can't identify existing binaries and re-installs them every time it's run.

GoCode can't be found and many features don't work.

GoFmt can't be found and an error is returned on file save.

I'm sure there are many similar manifestations of this similar issue.

It's easy to reproduce. Simply stop exporting $GOPATH and try to use vim-go.

**Comment by fatih** [comment] 2017-03-28 23:27
Hi @spf13 

I'm working on this. Already fixed :GoPath and :GoInstallBinaries, however the problem is deeper than I've imagined. It needs a serious refactor. I'm now doing it. It'll be included into the next release as well. Thanks for the feedback.

**Comment by fatih** [comment] 2017-03-30 00:12
Fixed with #1248

**Closed** 2017-03-30 00:11 UTC
Labels: bug
