### ISSUE TITLE
`GoDebugStart` in the root of the project

### ISSUE THREAD

**Issue by jaeyeol-moloco** [fatih/vim-go#3443] opened 2022-08-09 16:25 UTC
### What did you do? (required: The issue will be **closed** when not provided)
`:GoDebugStart`

### What did you expect to happen?
I expected the working directory is the directory of starting vim (the root of the project for my case). In the golang project structure like below
```
cmd/
pkg/
go.mod
...
```
there are two or more `main()` functions in `cmd/` which we want debug, but some of them require the working directory is the root of the project. I can do that by opening random go file to autocmd, opening `go.mod` (because it's in the root directory) and `:GoDebugStart module_name/cmd/some_pkg`, but it's inconvenient. So it would be really nice if there is an option to set the debug directory as the root of the project.

### What happened instead?
As the help text describes, the directory of the buffer is used.
```
                                                               *:GoDebugStart*
:GoDebugStart [pkg] [program-args]

    Start the debug mode for [pkg]; this does several things:

      * Setup the debug windows according to |'g:go_debug_windows'|.
      * Make the `:GoDebug*` commands and `(go-debug-*)` mappings available.

    The directory of the current buffer is used if [pkg] is empty. Any other
    arguments will be passed to the program.

    Use |:GoDebugStop| to stop `dlv` and exit debugging mode.
```

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>
I didn't set debug config much. The below is all of GoDebug config which I set.
```vim
let g:go_debug_windows = {
  \ 'vars': 'rightbelow 60vnew',
  \ 'stack': 'rightbelow 18new',
\ }
```
</details>

#### Vim version (first three lines from `:version`):

```bash
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 26 2022 21:11:38)                                                                                                                                                                 
macOS version - x86_64
Included patches: 1-4832
```

#### Go version (`go version`):

`go1.18.3 darwin/amd64`

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/jaeyeolshin/Library/Caches/go-build"
GOENV="/Users/jaeyeolshin/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/jaeyeolshin/go/pkg/mod"
GONOPROXY="github.com/moloco/*"
GONOSUMDB="github.com/moloco/*"
GOOS="darwin"
GOPATH="/Users/jaeyeolshin/go"
GOPRIVATE="github.com/moloco/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.18.3/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.18.3/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/jaeyeolshin/developments/jaeyeolshin/minikube/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/2t/d0fvsnpx30sb3zfg81v5md3c0000gn/T/go-build2952909948=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre>
</details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.9.1
    golang.org/x/tools/gopls@v0.9.1 h1:SigsTL4Hpv3a6b/a7oPCLRv5QUeSM6PZNdta1oKY4B0=

</pre></details>

**Comment by bhcleek** [comment] 2022-08-09 17:26
Closing. This is effectively a duplicate of #3437 and would be resolved by the fix there if we decide to merge it.

**Closed by bhcleek** 2022-08-09 17:26 UTC
Labels: duplicate, debugger
