### ISSUE TITLE
Integrate MetaLinter 

### ISSUE THREAD

**Issue by nightlyone** [fatih/vim-go#505] opened 2015-07-30 10:23 UTC
Integrating https://github.com/alecthomas/gometalinter might be very useful and could speed-up some development flows.

**Comment by fatih** [comment] 2015-07-30 12:16
Hi @nightlyone. This is a duplicate of https://github.com/fatih/vim-go/issues/320 :)

**Closed** 2015-07-30 12:16 UTC
Labels: duplicate
