### ISSUE TITLE
Better template for *_test.go files

### ISSUE THREAD

**Issue by mcandre** [fatih/vim-go#1239] opened 2017-03-17 20:24 UTC
vim-go has a nifty template when creating `*.go` files. Unfortunately, this is a little overreaching.

When users create a new `*_test.go` file, please use a more appropriate template, like

```go
package name_test

import "testing"

func TestMethod(t *testing.T) {
	t.Error("Unimplemented")
}
```

**Comment by thomasheller** [comment] 2017-03-18 13:57
Duplicate of #1216.

**Comment by fatih** [comment] 2017-03-28 01:49
See #1216, thanks

**Closed** 2017-03-28 01:49 UTC
Labels: duplicate
