### ISSUE TITLE
Failed to run GoInstallBinaries after update

### ISSUE THREAD

**Issue by eschao** [fatih/vim-go#2083] opened 2018-12-05 08:20 UTC
### What did you do? (required. The issue will be **closed** when not provided.)
Updated vim-go to latest by vundle and then failed to run :GoInstallBinaries 

### What did you expect to happen?
Run successfully without error

### What happened instead?
Failed with the below error:
```vim-go: iferr not found. Installing github.com/koron/iferr to folder /usr/local/bin
Error detected while processing function <SNR>68_GoInstallBinaries[87]..go#util#Exec[10]..go#path#CheckBinPath:
line   13:
E117: Unknown function: go#config#SearchBinPathFirst
E15: Invalid expression: go#config#SearchBinPathFirst()
Error detected while processing function <SNR>68_GoInstallBinaries:
line   87:
E714: List required
Error detected while processing function <SNR>68_GoInstallBinaries[94]..go#util#Exec[10]..go#path#CheckBinPath:
line   13:
E117: Unknown function: go#config#SearchBinPathFirst
E15: Invalid expression: go#config#SearchBinPathFirst()
Error detected while processing function <SNR>68_GoInstallBinaries:
line   94:
E714: List required
vim-go: gocode-gomod not found. Installing github.com/stamblerre/gocode to folder /usr/local/bin
Error detected while processing function <SNR>68_GoInstallBinaries[87]..go#util#Exec[10]..go#path#CheckBinPath:
line   13:
E117: Unknown function: go#config#SearchBinPathFirst
E15: Invalid expression: go#config#SearchBinPathFirst()
Error detected while processing function <SNR>68_GoInstallBinaries:
line   87:
E714: List required
Error detected while processing function <SNR>68_GoInstallBinaries[94]..go#util#Exec[10]..go#path#CheckBinPath:
line   13:
E117: Unknown function: go#config#SearchBinPathFirst
E15: Invalid expression: go#config#SearchBinPathFirst()
Error detected while processing function <SNR>68_GoInstallBinaries:
line   94:
E714: List required
vim-go: installing finished!
```

### Configuration (**MUST** fill this out):

* vim-go version:
latest

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
Nothing special settings for vim-go

* Vim version (first three lines from `:version`):
VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov 29 2018 04:51:04)
macOS version
Included patches: 1-550
Compiled by Homebrew

* Go version (`go version`):
go version go1.11 darwin/amd64

* Go environment (`go env`):
GOARCH="amd64"
GOBIN="/usr/local/bin"
GOCACHE="/Users/chao/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/eschao/Code/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/6m/h6z2s9nx37j0bhqz2wpl1tr40000gn/T/go-build755618184=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by yml** [comment] 2018-12-05 12:09
Just saving a go file seems to also trigger a very similar error about `E117: Unknown function: go#config#SearchBinPathFirst`.

```
Error detected while processing function <SNR>29_fmt_autosave[3]..go#fmt#Format[41]..go#fmt#run[5]..go#util#Exec[10]..go#path#CheckBinPath:
line   13:                                                                                                                                                                                            
E117: Unknown function: go#config#SearchBinPathFirst
E15: Invalid expression: go#config#SearchBinPathFirst()
Error detected while processing function <SNR>29_fmt_autosave[3]..go#fmt#Format:
line   41:
"main.go" 79L, 1495C written
```

**Comment by yml** [comment] 2018-12-05 12:17
In fact this is similar to #2045 it seems to be caused by vim-poliglot.

The steps below fix the issue for me:

```
cd ~/.config/nvim/plugged/vim-polyglot && ./build
```

**Comment by bhcleek** [comment] 2018-12-05 23:11
This is a duplicate of #2045.

**Closed by bhcleek** 2018-12-05 23:11 UTC

**Comment by eschao** [comment] 2018-12-06 01:09
@yml Thanks, I thought I didn't install polyglot plugin since I did't see it in my vim config, but actually I can find it in the vim plugin folder, I'll try your solution.
