### ISSUE TITLE
E117: Unknown function: go#config#CodeCompletionEnabled

### ISSUE THREAD

**Issue by zhangjingqiang** [fatih/vim-go#2272] opened 2019-05-05 23:56 UTC
### What did you do? (required: The issue will be **closed** when not provided)

Installed `vim-go` with plug vim manager.

### What did you expect to happen?

Use all the `vim-go` features without any issue.

### What happened instead?

When open a go file, got this message at the bottom:

```
"config/config.go" 169L, 3854C                                                                                    
Error detected while processing /home/user/.vim/plugged/vim-go/ftplugin/go.vim:                              
line   28:                                                                                                        
E117: Unknown function: go#config#CodeCompletionEnabled                                                           
Press ENTER or type command to continue
```

### Configuration (**MUST** fill this out):

Default config in the `/home/user/.vim/plugged/vim-go/ftplugin/go.vim` file:
```
 28 if go#config#CodeCompletionEnabled()                                                                          
 29   " Set autocompletion                                                                                        
 30   setlocal omnifunc=go#complete#Complete                                                                      
 31   if !go#util#has_job()                                                                                       
 32     setlocal omnifunc=go#complete#GocodeComplete                                                              
 33   endif                                                                                                       
 34 endif
```

#### vim-go version:

Don't know how to check version. But this line has been put into the `~/.vimrc` file:

```
Plug 'fatih/vim-go', {'do': ':GoInstallBinaries'}
```

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
482 " go                                                                                                          
483 " vim-go                                                                                                      
484 " run :GoBuild or :GoTestCompile based on the go file                                                         
485 function! s:build_go_files()                                                                                  
486   let l:file = expand('%')                                                                                    
487   if l:file =~# '^\f\+_test\.go$'                                                                             
488     call go#test#Test(0, 1)                                                                                   
489   elseif l:file =~# '^\f\+\.go$'                                                                              
490     call go#cmd#Build(0)                                                                                      
491   endif                                                                                                       
492 endfunction                                                                                                   
493                                                                                                               
494 let g:go_list_type = "quickfix"                                                                               
495 let g:go_fmt_command = "goimports"                                                                            
496 let g:go_fmt_fail_silently = 1                                                                                
497                                                                                                               
498 let g:go_highlight_types = 1                                                                                  
499 let g:go_highlight_fields = 1                                                                                 
500 let g:go_highlight_functions = 1                                                                              
501 let g:go_highlight_methods = 1                                                                                
502 let g:go_highlight_operators = 1                                                                              
503 let g:go_highlight_build_constraints = 1                                                                      
504 let g:go_highlight_structs = 1                                                                                
505 let g:go_highlight_generate_tags = 1                                                                          
506 let g:go_highlight_space_tab_error = 0                                                                        
507 let g:go_highlight_array_whitespace_error = 0                                                                 
508 let g:go_highlight_trailing_whitespace_error = 0                                                              
509 let g:go_highlight_extra_types = 1                                                                            
510                                                                                                               
511 autocmd BufNewFile,BufRead *.go setlocal noexpandtab tabstop=4 shiftwidth=4 softtabstop=4                     
512                                                                                                               
513 augroup completion_preview_close                                                                              
514   autocmd!                                                                                                    
515   if v:version > 703 || v:version == 703 && has('patch598')                                                   
516     autocmd CompleteDone * if !&previewwindow && &completeopt =~ 'preview' | silent! pclose | endif           
517   endif                                                                                                       
518 augroup END                                                                                                   
519                                                                                                               
520 augroup go                                                                                                    
521                                                                                                               
522   au!                                                                                                         
523   au Filetype go command! -bang A call go#alternate#Switch(<bang>0, 'edit')                                   
524   au Filetype go command! -bang AV call go#alternate#Switch(<bang>0, 'vsplit')                                
525   au Filetype go command! -bang AS call go#alternate#Switch(<bang>0, 'split')                                 
526   au Filetype go command! -bang AT call go#alternate#Switch(<bang>0, 'tabe')                                  
527                                                                                                               
528   au FileType go nmap <Leader>dd <Plug>(go-def-vertical)                                                      
529   au FileType go nmap <Leader>dv <Plug>(go-doc-vertical)                                                      
530   au FileType go nmap <Leader>db <Plug>(go-doc-browser)                                                       
531                                                                                                               
532   au FileType go nmap <leader>r  <Plug>(go-run)                                                               
533   au FileType go nmap <leader>t  <Plug>(go-test)                                                              
534   au FileType go nmap <Leader>gt <Plug>(go-coverage-toggle)                                                   
535   au FileType go nmap <Leader>i <Plug>(go-info)                                                               
536   au FileType go nmap <silent> <Leader>l <Plug>(go-metalinter)                                                
537   au FileType go nmap <C-g> :GoDecls<cr>                                                                      
538   au FileType go nmap <leader>dr :GoDeclsDir<cr>                                                              
539   au FileType go imap <C-g> <esc>:<C-u>GoDecls<cr>                                                            
540   au FileType go imap <leader>dr <esc>:<C-u>GoDeclsDir<cr>                                                    
541   au FileType go nmap <leader>rb :<C-u>call <SID>build_go_files()<CR>                                         
542                                                                                                               
543 augroup END
</pre></details>

#### Vim version (first three lines from `:version`):

8.1

####  Go version (`go version`):

go version go1.12.4 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/user/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build203912205=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

**Comment by bhcleek** [comment] 2019-05-06 00:02
Are you using vim-polyglot?

**Comment by zhangjingqiang** [comment] 2019-05-06 01:24
> Are you using vim-polyglot?

Yes, I'm using it.

~/.vimrc
```
Plug 'sheerun/vim-polyglot'
```

Plugins
```
- vim-polyglot: Already installed
```

**Comment by bhcleek** [comment] 2019-05-06 01:28
The issue is with polyglot, not with vim-go. This is a duplicate of https://github.com/fatih/vim-go/issues/2262

I've added an entry to the vim-go FAQ to cover this case: https://github.com/fatih/vim-go/blob/master/doc/vim-go.txt#L2186-L2190

**Closed by bhcleek** 2019-05-06 01:28 UTC
