### ISSUE TITLE
Debugger breaks when stepping inside interface method call

### ISSUE THREAD

**Issue by aarzilli** [fatih/vim-go#2336] opened 2019-06-04 09:28 UTC
### What did you do? (required: The issue will be **closed** when not provided)

Set a breakpoint on the main function of https://github.com/aarzilli/delve_client_testing/blob/master/21autogen/main.go, started the debugger, used :GoDebugStep a bunch of times.

### What did you expect to happen?

End up inside main.IfaceImpl.Method.

### What happened instead?

Stuck inside an empty buffer.

#### vim-go version:

1.20

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>

</pre></details>

#### Vim version (first three lines from `:version`):

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled May 27 2019 13:46:23)
Included patches: 1-1408
Modified by jonathon.fernyhough@york.ac.uk
```

#### Go version (`go version`):

go version go1.12.4 linux/amd64

#### Go environment
not relevant

**Comment by bhcleek** [comment] 2020-08-21 04:26
I am unable to duplicate this with the current version of vim-go. There have been several improvements to vim-go and to delve since this issue was originally created; it's possible that any root cause was resolved by the many changes since this issue was reported.

**Closed by bhcleek** 2020-08-21 04:26 UTC
