### ISSUE TITLE
File names in GoMetalinter output are not recognized by vim when g:go_metalinter_command is a full commandline

### ISSUE THREAD

**Issue by orlangure** [fatih/vim-go#2707] opened 2020-02-10 13:56 UTC
When I run gometalinter, the warnings are put into quickfix list, but the file 6s are not recognized by vim, preventing me from being able to jump to the problematic spot.

Any warning reproduces the issue with the following configuration:

```
  let g:go_metalinter_command='golangci-lint run
              \ --enable-all
              \ -D dupl
              \ -D gomnd
              \ ./...'
```

```
|| compress.go:29:2: only one cuddle assignment allowed before if statement (wsl)
|| 	if err != nil {
|| 	^
```

I believe this is because of my custom configuration which enables all linters except gomnd and dupl, and runs everything on all child packages.

I use Go 1.13.6, and latest vim-go, gopls and golangci-lint versions (from master).

**Comment by bhcleek** [comment] 2020-02-10 14:36
@orlangure The problem is that you're using a completely custom command for `g:go_metalinter_command`. I can probably get a fix in, but as-is, what you're doing isn't supported. From [vim-go's help](https://github.com/fatih/vim-go/blob/master/doc/vim-go.txt#L1594-L1603):
> Valid options are `golangci-lint` and `gopls`.

I'll see if I can get a reasonable fix in place soon, though.

**Comment by bhcleek** [comment] 2020-02-10 14:52
@orlangure does #2707 resolve the issue for you?

**Comment by orlangure** [comment] 2020-02-10 14:56
@bhcleek Yes, it does, thank you!

**Comment by bhcleek** [comment] 2020-02-10 14:59
Cool. I'll merge it soon after I merge #2706

**Comment by flw-cn** [comment] 2020-02-11 14:19
Please DONT CLOSE this issue prematurely.
Because I encountered exactly the same problem, except that the parameter I added was `--exclude-use-default=true`. Please see here for the previous discussion(and that issue has been closed):
https://github.com/fatih/vim-go/pull/2708#issuecomment-584466924

**Comment by bhcleek** [comment] 2020-02-11 14:58
@flw-cn please use the feature on master to leverage the golangci-lint file. If you'd like to specify more support only reading `exclude-use-default` from the config file, then we can do that by moving  https://github.com/fatih/vim-go/blob/master/autoload/go/lint.vim#L321 down three lines, though, honestly, I'm a little reluctant for reasons outlined in https://github.com/golangci/golangci-lint/issues/456.

I'm closing this for now. Feel free to open an issue where we can discuss the merits of not doing `https://github.com/fatih/vim-go/blob/master/autoload/go/lint.vim#L321` when the linter list is empty.

**Closed by bhcleek** 2020-02-11 14:58 UTC
