### ISSUE TITLE
:GoVet does not refresh its message

### ISSUE THREAD

**Issue by winkee01** [fatih/vim-go#2645] opened 2020-01-07 11:43 UTC
### What did you do? (required: The issue will be **closed** when not provided)
hello.go is opened,  vim does not display syntax error, so I type :GoVet to run the syntax check, it says "vim-go: calling vet...", and stuck there(maybe not because syntax messages are displayed correctly, but this message never updates).

vim open hello.go, then do `:GoVet`, the calling message "vim-go: calling vet..." is never redrawn or updated.

### What did you expect to happen?
"vim-go: calling vet..." be updated to things like "Succeed", or cleared screen.

### What happened instead?
no redraw, no refresh

<img width="477" alt="vimgo_govet" src="https://user-images.githubusercontent.com/49930785/71893164-c85a6480-3185-11ea-8ed9-8d95b06e0e58.png">

### Configuration (**MUST** fill this out):
default configuration

#### vim-go version:
latest

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
Plug 'fatih/vim-go', { 'for': 'go' }
</pre></details>

#### Vim version (first three lines from `:version`):

vim8.2
#### Go version (`go version`):

go version go1.13.3 darwin/amd64
#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOOS="darwin"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls 0.2.2
</pre></details>

**Comment by juniway** [comment] 2020-01-08 04:56
Hi, thanks for the job, but the problem is still there.

**Comment by juniway** [comment] 2020-01-08 04:58
<img width="409" alt="callingvet" src="https://user-images.githubusercontent.com/3980841/71951601-90e7c880-3216-11ea-9aa8-eb00b5f6cdac.png">

**Comment by winkee01** [comment] 2020-01-08 05:00
thanks for the work, but the problem is still there
<img width="409" alt="callingvet" src="https://user-images.githubusercontent.com/49930785/71951677-cc829280-3216-11ea-9097-3c2c96d37683.png">

**Comment by bhcleek** [comment] 2020-01-08 17:11
I get a prompt for to hit Enter, and then the message disappears. The vimrc you

**Comment by bhcleek** [comment] 2020-01-09 01:58
I've removed the previous fix for this in #2649, because it doesn't work well and causes the user to have to unnecessarily hit enter when there are errors and `g:go_echo_command_info` is set.

Since you're using Vim 8.2, I think you may generally prefer to use `go#statusline#Show` and to add `let g:go_echo_command_info=0` to your vimrc. It will provide for a nicer experience.

Here's an example of using `go#statusline#Show` from my vimrc: https://github.com/bhcleek/vim/blob/master/vimrc#L90-L106

**Comment by winkee01** [comment] 2020-01-09 06:01
disable echo go command info works, but now :GoVet won't dissappear, I think it might be a bug of VIM.

**Comment by bhcleek** [comment] 2020-01-09 17:39
I suspect you can duplicate this by running executing `:echom test`; under what conditions will the `test` disappear?

**Comment by winkee01** [comment] 2020-01-10 08:31
So all I test is a file has a minor syntax error.

Here is what I get
1) GoVet won't automatically execute, which means I cannot get the error info in the quickfix window. 

2) When I execute :GoVet manually, error information is correctly shown but the display of ":GoVet" won't disappear, which is annoying because it takes a line height of the display area.

3) When I execute :echom test, an error shows "E121: Undefined variable: test". an acceptable behavior.

4) When I execute :GoErrorCheck, the window will load a new file(template go file) to replace my original file(buffer). I can only ctrl + o to get back to my original file which has syntax error.

**Comment by bhcleek** [comment] 2020-01-10 17:00
> When I execute :GoVet manually, error information is correctly shown but the display of ":GoVet" won't disappear, which is annoying because it takes a line height of the display area.

Your `cmdheight` value may be relevant. What is it?

> When I execute :echom test, an error shows "E121: Undefined variable: test". an acceptable behavior.

That should be `:echom "test"`

Without a more complete vimrc, it's difficult for me to tell what may be the cause of some of these issues. Have you actually tried duplicating this issue with the vimrc you provided in the original report?

**Comment by winkee01** [comment] 2020-01-11 01:39
ok, "test" will not disappear until the screen is redrawn, for example, ctrl-f to scroll down the page to forcibly redraw the screen.

**Comment by bhcleek** [comment] 2020-01-12 21:55
This isn't a bug, it's by design in Vim. Messages are not cleared until the screen is redrawn.

**Closed by bhcleek** 2020-01-12 21:55 UTC

**Comment by winkee01** [comment] 2020-01-13 05:40
No, this is different from the Issue I created, my issue is the :GoVet are not cleared, not the message generated by :GoVet.

In another word :echom "test" creates a mesage "test" on the bottom of the screen, it keep displaying until redrawn, but the command itself, which is :echom "test", should be cleared immediately.

**Comment by winkee01** [comment] 2020-01-13 05:41
:GoVet doesn't disappear, please test.

**Comment by winkee01** [comment] 2020-01-16 09:06
since you closed this issue, do I need to open a new issue in regard to the problem 4? which is:

4. When I execute :GoErrorCheck, the window will load a new file(template go file) to replace my original file(buffer). I can only ctrl + o to get back to my original file which has syntax error.

**Comment by bhcleek** [comment] 2020-01-17 15:52
Yes, please; that's a completely separate issue from this issue's intent.
