### ISSUE TITLE
c-x c-o error

### ISSUE THREAD

**Issue by it512** [fatih/vim-go#3643] opened 2024-02-22 08:22 UTC
<img width="1228" alt="image" src="https://github.com/vim/vim/assets/17774530/81cb2d00-fd82-4c23-938b-672396b08ee9">

**Comment by it512** [comment] 2024-02-22 08:23
vim version : 9.1.125

**Comment by it512** [comment] 2024-02-22 09:20
https://github.com/vim/vim/issues/14073

**Comment by it512** [comment] 2024-02-22 12:17
<img width="941" alt="image" src="https://github.com/fatih/vim-go/assets/17774530/70330184-338c-448a-b277-f5ca6d51d7df">

https://github.com/vim/vim/issues/14073
@fatih 

thank you! plz see

**Comment by bhcleek** [comment] 2024-02-22 16:39
The `win_gotoid` call locations that were referenced in vim/vim#14073 as being causes is most likely a correct analysis. Specifically, [this](https://github.com/fatih/vim-go/blob/0e975560df38be387cca1d7d33df7a4744091303/autoload/go/lsp.vim#L192) looks like a likely candidate.

However, given that they've [proposed a patch](https://github.com/vim/vim/issues/14073#issuecomment-1959284019) and [submitted a patch](https://github.com/vim/vim/pull/14074), you've confirmed it resolves the problem in Vim, and that this only affects Vim versions >= [9.1.0119](https://github.com/vim/vim/pull/14074) and less than whatever version the [patch](https://github.com/vim/vim/pull/14074) makes it into, I don't consider this high priority.

I'll look into using `win_execute`, but that may be more complicated than it first appears, and I'm less than enthusiastic about pursuing that course of action, as they've also indicated they that perhaps `textlock` checking should be added to it.

**Comment by Shane-XB-Qian** [comment] 2024-02-22 18:46
> The `win_gotoid` call locations that were referenced in vim/vim#14073 as being causes is most likely a correct analysis. Specifically, [this](https://github.com/fatih/vim-go/blob/0e975560df38be387cca1d7d33df7a4744091303/autoload/go/lsp.vim#L192) looks like a likely candidate.
> 
> However, given that they've [proposed a patch](https://github.com/vim/vim/issues/14073#issuecomment-1959284019) and [submitted a patch](https://github.com/vim/vim/pull/14074), you've confirmed it resolves the problem in Vim, and that this only affects Vim versions >= [9.1.0119](https://github.com/vim/vim/pull/14074) and less than whatever version the [patch](https://github.com/vim/vim/pull/14074) makes it into, I don't consider this high priority.
> 
> I'll look into using `win_execute`, but that may be more complicated than it first appears, and I'm less than enthusiastic about pursuing that course of action, as they've also indicated they that perhaps `textlock` checking should be added to it.

i felt some kinds of bad feeling was happening there,
this plugin lucky have you here, but some classic vim plugins had lost maintainer,
then not sure who would tune/adjust such things for them.. :thinking:

-- 
shane.xb.qian

**Comment by seandewar** [comment] 2024-02-22 19:09
The patch in question has now been included upstream as [v9.1.0128](https://github.com/vim/vim/commit/2a65e739447949a7aee966ce8a3b75521b2a79ea).

> I'll look into using win_execute, but that may be more complicated than it first appears, and I'm less than enthusiastic about pursuing that course of action, as they've also indicated they that perhaps textlock checking should be added to it.

That's mostly just me musing out loud. If there exists ways to close windows (or specifically, the "saved" curwin) during textlock from win_execute, it'd likely be better to just patch those holes out.

Anyway, provided that this plugin does not attempt `win_gotoid` to a different window during textlock, there should be no more problems.

**Comment by bhcleek** [comment] 2024-02-23 15:54
> i felt some kinds of bad feeling was happening there

Please be assured that there are no ill feelings here.

> That's mostly just me musing out loud. 

Thank you for clarifying.

**Comment by bhcleek** [comment] 2024-02-25 15:47
There are a number of cases where the current window when the response handler is called is expected to be the window that initiated the request. Therefore, I don't think `win_execute` can be easily swapped in here. Vim-go could check the window id and only attempt to change the window if the window to be changed to is different. Vim-go could also potentially track state and avoid attempts to change the window when one of the conditions that requires textlock is active.

Given that the fix to return early when changing the window to the current window has already landed in Vim, and that fix handles the most common cases appropriately without putting additional burden on plugin authors, I'm closing this.

Thank you for the clear bug report, the fast turnaround in Vim, and the discussion.

**Closed by bhcleek** 2024-02-25 15:47 UTC
