### ISSUE TITLE
is there anyway do not open doc preview window when autocompletion ?

### ISSUE THREAD

**Issue by imroc** [fatih/vim-go#1106] opened 2016-11-21 06:00 UTC
whenever I choose a function from the autocompletion plugin,it will open a doc preview window on the top, I close it `<C-w>k<C-w>c` every time,so I map my key as : `au Filetype go nmap <leader>e <C-w>k<C-w>c`  to close it conveniently,but I don't want it open,anyway can stop it?

**Comment by fatih** [comment] 2016-11-22 04:14
This is a duplicate of https://github.com/fatih/vim-go/issues/912  It's a Vim feature. Add `set completeopt-=preview` to fix it. Thanks

**Closed by fatih** 2016-11-22 04:14 UTC

**Comment by imroc** [comment] 2016-11-22 09:45
thank you very much
