### ISSUE TITLE
:GoRun report "go run: no go files listed

### ISSUE THREAD

**Issue by todaygood** [fatih/vim-go#1520] opened 2017-10-18 11:42 UTC
### What did you do? (required. The issue will be **closed** when not provided.)
:GoRun report "go run: no go files listed
 
### What did you expect to happen?
:GoRun work
### What happened instead?
":!go run %" , ":GoRun %" works well.

### Configuration

* vim version (major, minor, and included patches from `:version`):
7.4
* vim-go version:
github latest
* go version (`go version`):
go1.8.3 linux/amd64
* operating system:
centos7
* `vimrc` you used to reproduce:

[vimrc.txt](https://github.com/fatih/vim-go/files/1394428/vimrc.txt)

**Comment by fatih** [comment] 2017-10-18 20:44
Can you please update your Vim version. It's very old and might cause problems. Also `:GoRun` works fine. Let me know once you upgraded your Vim version. Thanks.

**Comment by todaygood** [comment] 2017-10-18 23:20
I have upgraded vim version, but the issue still is existed.

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 18 2017 15:30:22)
Included patches: 1-1203

**Comment by bhcleek** [comment] 2017-10-19 00:07
I was able to duplicate this. 

@todaygood, after `:GoRun` fails, what does `:messages` output?

**Comment by todaygood** [comment] 2017-10-19 06:27
:messages output "Messages maintainer: Bram Moolenaar <Bram@vim.org>"

**Comment by henter** [comment] 2017-10-19 06:33
same issue occured

**Comment by bhcleek** [comment] 2017-10-19 06:44
I've only seen this when I have multiple files in a directory with different package names. Otherwise, I have been unable to find a case where it fails.

Closing this for now. If you can provide instructions to reliably reproduce this, please file another issue.

**Closed by bhcleek** 2017-10-19 06:44 UTC

**Comment by Carlodf** [comment] 2018-01-19 20:19
Can we have at list some guidance on how to debug this issue or what operation to perform to provide more useful information. I appreciate it is not a critical issue since there are ways to work around it, but it is still a shame since you produced a really nice a neat tool and would be awesome if we could get this issue fixed. I am experiencing the same issue.
:GoRun puts vim in foreground and in the shell I get: "go run: no file listed".
:messages doesn't show any message
It used to work just fine for me before, than all of the sudden I started getting this weird behavior.
Any suggestion about were could I add some log lines and get a better understanding of what is going wrong? or just maybe get back to you with more useful info?

Thank you very much for this awesome tool and your hard work anyway! :)
