### ISSUE TITLE
Not an editor command:GoDebugNext

### ISSUE THREAD

**Issue by FelixStarship** [fatih/vim-go#3425] opened 2022-06-14 10:21 UTC
go version
go version go1.17.9 linux/amd64
-----------------------------------------
vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 01 2022 09:16:32)
----------------------------------------------------------------------------------------------

**Comment by FelixStarship** [comment] 2022-06-14 11:03
.vimrc
-----------------------
set nocompatible
syntax on
filetype off
call plug#begin('~/.vim/plugged')
Plug 'morhetz/gruvbox'
Plug 'preservim/nerdtree'
Plug 'fatih/vim-go'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'mhinz/vim-startify'
Plug 'ycm-core/YouCompleteMe'
Plug 'ryanoasis/vim-devicons'
filetype plugin indent on
call plug#end()
set nu
set encoding=utf-8
autocmd vimenter * ++nested colorscheme gruvbox
set bg=dark
map <F3> :NERDTreeMirror<CR>
map <F3> :NERDTreeToggle<CR>
let g:ycm_global_ycm_extra_conf='~/.vim/plugged/YouCompleteMe/third_party/ycmd/ycm/.ycm_extra_conf.py'
let g:ycm_key_invoke_completion = '<c-z>'

**Comment by bhcleek** [comment] 2022-06-14 17:15
Closing due to absence of description of what the user did.

**Comment by FelixStarship** [comment] 2022-06-15 01:53
@bhcleek Not an editor command:GoDebugNext

**Comment by FelixStarship** [comment] 2022-06-15 01:54
Why should I close it? I described my problem. I can't use the command：GoDebugNext

**Comment by bhcleek** [comment] 2022-06-15 06:17
Please describe some basic steps to reproduce the problem you're seeing. I have no idea what you've done or why you'd expect `:GoDebugnext` to be a command that you _can_ use.

**Closed** 2022-06-17 14:01 UTC
