### ISSUE TITLE
really slow when switching to insert mode for the first time

### ISSUE THREAD

**Issue by magicalbanana** [fatih/vim-go#1482] opened 2017-09-28 02:01 UTC
### Behavior

So, when opening a new vim/NeoVim instance and opening a `go` file, when switching to insert mode, it's really really really slow to the point it freezes.

### Steps to reproduce:
I think it'll be faster if my vim config was used.

1. git clone this to `~/.config/nvim`, https://github.com/meinekonfig/vim
2. run `.do/select bundle`
3. open any `go` file
4. insert mode

### Configuration

Add here your current configuration and additional information that might be
useful, such as:

* `vimrc` you used to reproduce
https://github.com/meinekonfig/vim
* vim version: Vim 8 or NeoVim (NVIM v0.2.0)
* vim-go version: 
* go version: 1.9

***profile***
```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
    8  66.486497   0.000280  deoplete#util#exists_omnifunc()
    1  66.486026   0.000645  go#complete#Complete()
    1  66.485381   0.000381  <SNR>442_gocodeAutocomplete()
    5  66.478834  66.478638  go#util#System()
    1  66.301986   0.000252  <SNR>442_gocodeCommand()
 6429   5.291604   0.180842  airline#extensions#branch#get_head()
 6429   5.110762   0.201238  airline#extensions#branch#head()
 6429   3.742539   1.258097  <SNR>283_update_branch()
 6429   2.110070   0.407919  <SNR>283_update_git_branch()
    1   1.748691   0.000120  go#util#env()
    1   1.748567   0.000040  go#util#goroot()
 6429   1.702151   0.135917  fugitive#head()
 6429   1.400023   0.756870  airline#extensions#hunks#get_hunks()
 6429   1.262632   0.323186  <SNR>146_repo_head()
 6429   1.213237   1.172938  airline#check_mode()
 6429   1.166985   1.042234  <SNR>283_update_untracked()
12858   1.165439   0.691836  airline#extensions#ale#get()
 6429   0.963651   0.840175  airline#extensions#whitespace#check()
 6429   0.682524   0.062713  airline#extensions#ale#get_warning()
45003   0.673539             airline#util#append()

FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
    5  66.478834  66.478638  go#util#System()
 6429   3.742539   1.258097  <SNR>283_update_branch()
 6429   1.213237   1.172938  airline#check_mode()
 6429   1.166985   1.042234  <SNR>283_update_untracked()
 6429   0.963651   0.840175  airline#extensions#whitespace#check()
 6429   1.400023   0.756870  airline#extensions#hunks#get_hunks()
12858   1.165439   0.691836  airline#extensions#ale#get()
45003              0.673539  airline#util#append()
12858              0.527124  <SNR>146_repo()
 6429   0.582119   0.463118  <SNR>146_repo_head_ref()
 6379   0.553211   0.458231  <SNR>96_do_complete()
57861              0.440362  airline#util#wrap()
 6429   2.110070   0.407919  <SNR>283_update_git_branch()
 6429              0.374372  <SNR>283_update_hg_branch()
12858              0.325959  airline#util#shorten()
 6429   1.262632   0.323186  <SNR>146_repo_head()
12858              0.308546  <SNR>322_GetCounts()
 6429              0.274419  airline#parts#spell()
 6429   0.643153   0.247263  <SNR>279_get_hunks()
 6429              0.223807  airline#parts#ffenc()
```

Any help would be much appreciated.

**Comment by romeovs** [comment] 2017-09-28 11:28
I have the same issue

**Comment by Carpetsmoker** [comment] 2017-09-28 14:22
Not sure why we need two issues for this? You also reported it in #1418.

To repeat my comment there:

> Your Vim config is rather large. Could you try to reproduce this with a more minimal setup? See [How do I debug my vimrc file?](https://vi.stackexchange.com/q/2003/51) for some tips on that.
>
> That being said, Vim-go uses [gocode](https://github.com/nsf/gocode) for completion; this starts a background daemon for caching. The first time it's often quite slow (especially with a large GOPATH), but after that it should be very fast.

You just came back with "it doesn't work", which isn't really all that helpful...

To be clear:

1. When reporting issues please provide a **small** vimrc to reproduce, not a large repository where I need to run scripts to even get it to run. This is also mentioned in the template when creating an issue.

2. You also didn't provide any information about what kind of Go files you're loading. Is it a simple example, or a huge project? Like I said, it can be normal for `gocode` to be slow the first time since the gocode daemon needs to start and compile stuff (depending on what's in the GOPATH/pkg` directory).

You can test this by using `ps axu | grep go`, which will show any potential `compile` processes that `gocode` may have started.

Running `go build -i` or `go install` should mitigate some of that.

You can also test this by setting `GOPATH` to something like `~/testgo` and creating a simple file.

**Comment by magicalbanana** [comment] 2017-09-28 15:30
@Carpetsmoker sorry.

1. Hmm, I'll try to do the small `vimrc` but I'm trying to debug this issue as it is with my config.
2. It's just a standard go file, at first I tried it with a small project, but even with a single file, it still lags when inserting for the first time (it does get fast after that).

**Comment by magicalbanana** [comment] 2017-09-28 15:36
Hmm, I did the `ps aux | grep go` and found something interesting, I am seeing one package being installed more than once. 

``
$ ps aux | grep go
kgan             65275   0.4  0.0 556618736   6968 s001  S+   10:32AM   0:00.02 go install github.com/humaniq/errgo
kgan             65375   0.0  0.0  2490484     12 s001  S+   10:32AM   0:00.00 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -cc1 -triple x86_64-apple-macosx10.12.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name trivial.c -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fno-strict-return -masm-verbose -munwind-tables -target-cpu penryn -target-linker-version 302.3 -dwarf-column-info -debugger-tuning=lldb -coverage-notes-file /var/folders/5s/by2v_q812vlbmns09hpgd19c000lgb/T/go-build679229575/trivial.gcno -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0 -fdebug-compilation-dir /var/folders/5s/by2v_q812vlbmns09hpgd19c000lgb/T/go-build679229575 -fdebug-prefix-map=a=b -ferror-limit 19 -fmessage-length 0 -stack-protector 1 -fblocks -fobjc-runtime=macosx-10.12.0 -fencode-extended-block-signature -fmax-type-align=16 -fdiagnostics-show-option -o trivial.o -x c trivial.c
kgan             65374   0.0  0.0  2490484     12 s001  S+   10:32AM   0:00.00 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -cc1 -triple x86_64-apple-macosx10.12.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name trivial.c -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fno-strict-return -masm-verbose -munwind-tables -target-cpu penryn -target-linker-version 302.3 -dwarf-column-info -debugger-tuning=lldb -coverage-notes-file /var/folders/5s/by2v_q812vlbmns09hpgd19c000lgb/T/go-build682415133/trivial.gcno -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0 -fdebug-compilation-dir /var/folders/5s/by2v_q812vlbmns09hpgd19c000lgb/T/go-build682415133 -fdebug-prefix-map=a=b -ferror-limit 19 -fmessage-length 0 -stack-protector 1 -fblocks -fobjc-runtime=macosx-10.12.0 -fencode-extended-block-signature -fmax-type-align=16 -fdiagnostics-show-option -o trivial.o -x c trivial.c
kgan             65373   0.0  0.0  2490484     12 s001  S+   10:32AM   0:00.00 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -cc1 -triple x86_64-apple-macosx10.12.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name trivial.c -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fno-strict-return -masm-verbose -munwind-tables -target-cpu penryn -target-linker-version 302.3 -dwarf-column-info -debugger-tuning=lldb -coverage-notes-file /var/folders/5s/by2v_q812vlbmns09hpgd19c000lgb/T/go-build887612034/trivial.gcno -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0 -fdebug-compilation-dir /var/folders/5s/by2v_q812vlbmns09hpgd19c000lgb/T/go-build887612034 -fdebug-prefix-map=a=b -ferror-limit 19 -fmessage-length 0 -stack-protector 1 -fblocks -fobjc-runtime=macosx-10.12.0 -fencode-extended-block-signature -fmax-type-align=16 -fdiagnostics-show-option  trivial.o -x c trivial.c
kgan             65372   0.0  0.0  2490484     12 s001  S+   10:32AM   0:00.00 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -cc1 -triple x86_64-apple-macosx10.12.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name trivial.c -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fno-strict-return -masm-verbose -munwind-tables -target-cpu penryn -target-linker-version 302.3 -dwarf-column-info -debugger-tuning=lldb -coverage-notes-file /var/folders/5s/by2v_q812vlbmns09hpgd19c000lgb/T/go-build470106326/trivial.gcno -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0 -fdebug-compilation-dir /var/folders/5s/by2v_q812vlbmns09hpgd19c000lgb/T/go-build470106326 -fdebug-prefix-map=a=b -ferror-limit 19 -fmessage-length 0 -stack-protector 1 -fblocks -fobjc-runtime=macosx-10.12.0 -fencode-extended-block-signature -fmax-type-align=16 -fdiagnostics-show-option -o trivial.o -x c trivial.c
kgan             65371   0.0  0.0  2490484     12 s001  S+   10:32AM   0:00.00 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -cc1 -triple x86_64-apple-macosx10.12.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name trivial.c -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fno-strict-return -masm-verbose -munwind-tables -target-cpu penryn -target-linker-version 302.3 -dwarf-column-info -debugger-tuning=lldb -coverage-notes-file /var/folders/5s/by2v_q812vlbmns09hpgd19c000lgb/T/go-build428177845/trivial.gcno -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0 -fdebug-compilation-dir /var/folders/5s/by2v_q812vlbmns09hpgd19c000lgb/T/go-build428177845 -fdebug-prefix-map=a=b -ferror-limit 19 -fmessage-length 0 -stack-protector 1 -fblocks -fobjc-runtime=macosx-10.12.0 -fencode-extended-block-signature -fmax-type-align=16 -fdiagnostics-show-option -o trivial.o -x c trivial.c
kgan             65370   0.0  0.0  2490484     16 s001  S+   10:32AM   0:00.00 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -cc1 -triple x86_64-apple-macosx10.12.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name trivial.c -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fno-strict-return -masm-verbose -munwind-tables -target-cpu penryn -target-linker-version 302.3 -dwarf-column-info -debugger-tuning=lldb -coverage-notes-file /var/folders/5s/by2v_q812vlbmns09hpgd19c000lgb/T/go-build617514607/trivial.gcno -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0 -fdebug-compilation-dir /var/folders/5s/by2v_q812vlbmns09hpgd19c000lgb/T/go-build617514607 -fdebug-prefix-map=a=b -ferror-limit 19 -fmessage-length 0 -stack-protector 1 -fblocks -fobjc-runtime=macosx-10.12.0 -fencode-extended-block-signature -fmax-type-align=16 -fdiagnostics-show-option -o trivial.o -x c trivial.c
kgan             65369   0.0  0.0  2490484     12 s001  S+   10:32AM   0:00.00 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -cc1 -triple x86_64-apple-macosx10.12.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name trivial.c -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fno-strict-return -masm-verbose -munwind-tables -target-cpu penryn -target-linker-version 302.3 -dwarf-column-info -debugger-tuning=lldb -coverage-notes-file /var/folders/5s/by2v_q812vlbmns09hpgd19c000lgb/T/go-build291168829/trivial.gcno -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0 -fdebug-compilation-dir /var/folders/5s/by2v_q812vlbmns09hpgd19c000lgb/T/go-build291168829 -fdebug-prefix-map=a=b -ferror-limit 19 -fmessage-length 0 -stack-protector 1 -fblocks -fobjc-runtime=macosx-10.12.0 -fencode-extended-block-signature -fmax-type-align=16 -fdiagnostics-show-option -o trivial.o -x c trivial.c
kgan             65368   0.0  0.0  2490484     12 s001  S+   10:32AM   0:00.00 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -cc1 -triple x86_64-apple-macosx10.12.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name trivial.c -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fno-strict-return -masm-verbose -munwind-tables -target-cpu penryn -target-linker-version 302.3 -dwarf-column-info -debugger-tuning=lldb -coverage-notes-file /var/folders/5s/by2v_q812vlbmns09hpgd19c000lgb/T/go-build615075611/trivial.gcno -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0 -fdebug-compilation-dir /var/folders/5s/by2v_q812vlbmns09hpgd19c000lgb/T/go-build615075611 -fdebug-prefix-map=a=b -ferror-limit 19 -fmessage-length 0 -stack-protector 1 -fblocks -fobjc-runtime=macosx-10.12.0 -fencode-extended-block-signature -fmax-type-align=16 -fdiagnostics-show-option -o trivial.o -x c trivial.c
kgan             65367   0.0  0.0  2490484     12 s001  S+   10:32AM   0:00.00 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -cc1 -triple x86_64-apple-macosx10.12.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name trivial.c -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fno-strict-return -masm-verbose -munwind-tables -target-cpu penryn -target-linker-version 302.3 -dwarf-column-info -debugger-tuning=lldb -coverage-notes-file /var/folders/5s/by2v_q812vlbmns09hpgd19c000lgb/T/go-build206774190/trivial.gcno -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0 -fdebug-compilation-dir /var/folders/5s/by2v_q812vlbmns09hpgd19c000lgb/T/go-build206774190 -fdebug-prefix-map=a=b -ferror-limit 19 -fmessage-length 0 -stack-protector 1 -fblocks -fobjc-runtime=macosx-10.12.0 -fencode-extended-block-signature -fmax-type-align=16 -fdiagnostics-show-option -o trivial.o -x c trivial.c
kgan             65366   0.0  0.0  2490484     12 s001  S+   10:32AM   0:00.00 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -cc1 -triple x86_64-apple-macosx10.12.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name trivial.c -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fno-strict-return -masm-verbose -munwind-tables -target-cpu penryn -target-linker-version 302.3 -dwarf-column-info -debugger-tuning=lldb -coverage-notes-file /var/folders/5s/by2v_q812vlbmns09hpgd19c000lgb/T/go-build244656107/trivial.gcno -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0 -fdebug-compilation-dir /var/folders/5s/by2v_q812vlbmns09hpgd19c000lgb/T/go-build244656107 -fdebug-prefix-map=a=b -ferror-limit 19 -fmessage-length 0 -stack-protector 1 -fblocks -fobjc-runtime=macosx-10.12.0 -fencode-extended-block-signature -fmax-type-align=16 -fdiagnostics-show-option -o trivial.o -x c trivial.c
kgan             65365   0.0  0.0  2490484     12 s001  S+   10:32AM   0:00.00 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -cc1 -triple x86_64-apple-macosx10.12.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name trivial.c -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fno-strict-return -masm-verbose -munwind-tables -target-cpu penryn -target-linker-version 302.3 -dwarf-column-info -debugger-tuning=lldb -coverage-notes-file /var/folders/5s/by2v_q812vlbmns09hpgd19c000lgb/T/go-build150900591/trivial.gcno -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0 -fdebug-compilation-dir /var/folders/5s/by2v_q812vlbmns09hpgd19c000lgb/T/go-build150900591 -fdebug-prefix-map=a=b -ferror-limit 19 -fmessage-length 0 -stack-protector 1 -fblocks -fobjc-runtime=macosx-10.12.0 -fencode-extended-block-signature -fmax-type-align=16 -fdiagnostics-show-option -o trivial.o -x c trivial.c
kgan             65308   0.0  0.0 556619760   6900 s001  S+   10:32AM   0:00.02 go install github.com/humaniq/errgo
kgan             65307   0.0  0.0 556618736   6868 s001  S+   10:32AM   0:00.02 go install github.com/humaniq/errgo
kgan             65306   0.0  0.0 556620144   6928 s001  S+   10:32AM   0:00.02 go install github.com/humaniq/errgo
kgan             65305   0.0  0.0 556627696   6876 s001  S+   10:32AM   0:00.02 go install github.com/humaniq/errgo
kgan             65304   0.0  0.0 556620784   6908 s001  S+   10:32AM   0:00.02 go install github.com/humaniq/errgo
kgan             65303   0.0  0.0 556619760   6872 s001  S+   10:32AM   0:00.02 go install github.com/humaniq/errgo
kgan             65302   0.0  0.0 556618480   6864 s001  S+   10:32AM   0:00.01 go install github.com/humaniq/errgo
kgan             65301   0.0  0.0 556627952   6876 s001  S+   10:32AM   0:00.02 go install github.com/humaniq/errgo
kgan             65300   0.0  0.0 556627196   6880 s001  S+   10:32AM   0:00.01 go install github.com/humaniq/errgo
kgan             65299   0.0  0.0 556628720   6888 s001  S+   10:32AM   0:00.02 go install github.com/humaniq/errgo
kgan             65298   0.0  0.0 556618480   6800 s001  S+   10:32AM   0:00.02 go install github.com/humaniq/errgo
kgan             65297   0.0  0.0 556627696   6812 s001  S+   10:32AM   0:00.02 go install github.com/humaniq/errgo
kgan             65296   0.0  0.0 556618480   6860 s001  S+   10:32AM   0:00.02 go install github.com/humaniq/errgo
kgan             65295   0.0  0.0 556631152   6924 s001  S+   10:32AM   0:00.02 go install github.com/humaniq/errgo
kgan             65294   0.0  0.0 556620784   6892 s001  S+   10:32AM   0:00.01 go install github.com/humaniq/errgo
kgan             65293   0.0  0.0 556628976   6892 s001  S+   10:32AM   0:00.02 go install github.com/humaniq/errgo
kgan             65292   0.0  0.0 556618736   6860 s001  S+   10:32AM   0:00.02 go install github.com/humaniq/errgo
kgan             65291   0.0  0.0 556617456   6848 s001  S+   10:32AM   0:00.02 go install github.com/humaniq/errgo
kgan             65290   0.0  0.0 556618480   6832 s001  S+   10:32AM   0:00.02 go install github.com/humaniq/errgo
kgan             65289   0.0  0.0 556630000   6900 s001  S+   10:32AM   0:00.02 go install github.com/humaniq/errgo
kgan             65288   0.0  0.0 556618480   6864 s001  S+   10:32AM   0:00.02 go install github.com/humaniq/errgo
kgan             65287   0.0  0.0 556619760   6980 s001  S+   10:32AM   0:00.02 go install github.com/humaniq/errgo
kgan             65286   0.0  0.0 556619504   6840 s001  S+   10:32AM   0:00.02 go install github.com/humaniq/errgo
kgan             65285   0.0  0.0 556618736   6860 s001  S+   10:32AM   0:00.02 go install github.com/humaniq/errgo
kgan             65284   0.0  0.0 556619760   6872 s001  S+   10:32AM   0:00.02 go install github.com/humaniq/errgo
kgan             65283   0.0  0.0 556617456   6792 s001  S+   10:32AM   0:00.02 go install github.com/humaniq/errgo
kgan             65282   0.0  0.0 556618480   6880 s001  S+   10:32AM   0:00.02 go install github.com/humaniq/errgo
kgan             65281   0.0  0.0 556628976   6884 s001  S+   10:32AM   0:00.02 go install github.com/humaniq/errgo
kgan             65280   0.0  0.0 556619760   6944 s001  S+   10:32AM   0:00.02 go install github.com/humaniq/errgo
kgan             65279   0.0  0.0 556637936   6912 s001  S+   10:32AM   0:00.02 go install github.com/humaniq/errgo
kgan             65278   0.0  0.0 556620784   6888 s001  S+   10:32AM   0:00.02 go install github.com/humaniq/errgo
kgan             65277   0.0  0.0 556618480   6784 s001  S+   10:32AM   0:00.02 go install github.com/humaniq/errgo
kgan             65276   0.0  0.0 556617456   6880 s001  S+   10:32AM   0:00.02 go install github.com/humaniq/errgo
kgan             65274   0.0  0.0 556618480   6884 s001  S+   10:32AM   0:00.02 go install github.com/humaniq/errgo
kgan             65273   0.0  0.0 556619760   6888 s001  S+   10:32AM   0:00.02 go install github.com/humaniq/errgo
kgan             65272   0.0  0.0 556617456   6868 s001  S+   10:32AM   0:00.02 go install github.com/humaniq/errgo
kgan             65266   0.0  0.0 556617068   7108 s001  S+   10:32AM   0:00.01 /Users/kgan/src/golang/gocode/bin/gocode -sock unix -in=/var/folders/5s/by2v_q812vlbmns09hpgd19c000lgb/T/nvimzs6pdg/10 -f=vim autocomplete /Users/kgan/src/golang/gocode/src/github.com/humaniq/tapatybe/ds/account_account.go 999
kgan             65243   0.0  0.1 556651436  14872 s001  S+   10:32AM   0:01.23 /Users/kgan/src/golang/gocode/bin/gocode -s -sock unix -addr 127.0.0.1:37373
kgan             43864   0.0  0.2  2731988  30532   ??  S    10:06PM   0:26.39 /Applications/ExpanDrive.app/Contents/SharedSupport/exfs.app/Contents/MacOS/exfs host=googledrive.com username=momo -f -olocal -oauto_cache -odaemon_timeout=30 -ovolname=Google Drive - momo exfs=true name=Google Drive - momo type=gdrive id=v70a8tcj
kgan              4515   0.0  0.0  2483420   3772   ??  S     1:46PM   0:00.03 /Applications/Google Chrome.app/Contents/Versions/61.0.3163.100/Google Chrome Framework.framework/Helpers/crashpad_handler --monitor-self-annotation=ptype=crashpad-handler --database=/Users/kgan/Library/Application Support/Google/Chrome/Crashpad --metrics-dir=/Users/kgan/Library/Application Support/Google/Chrome --url=https://clients2.google.com/cr/report --annotation=channel= --annotation=plat=OS X --annotation=prod=Chrome_Mac --annotation=ver=61.0.3163.100 --handshake-fd=8
kgan             65417   0.0  0.0  2423556     40 s002  S+   10:32AM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn go
```

**Comment by Shougo** [comment] 2017-09-29 02:04
@magicalbanana Hm.  I think you can disable gocode omnifunc in `after/ftplugin/go.vim`

```vim
setlocal omnifunc=
```

**Comment by Shougo** [comment] 2017-10-01 13:00
I have fixed the problem in deoplete.

**Comment by Carpetsmoker** [comment] 2017-10-04 21:28
Fixed in https://github.com/Shougo/deoplete.nvim/commit/60bed29fb33cf32a3946509c3e983c2f4a239d40

**Closed by Carpetsmoker** 2017-10-04 21:28 UTC
