### ISSUE TITLE
Error detect: vim-go: function <SNR>183_on_stdout[1]..<SNR>183_neocb[58]..311[10]..314[3]..315[2]..316, line 52: Vim(if):E716: key not present in Dictionary: version == l:version

### ISSUE THREAD

**Issue by xuantungmta** [fatih/vim-go#2755] opened 2020-03-03 08:51 UTC
I use init.vim file in NeoVim, init.vim file is created by [sebdah/dotfiles](https://github.com/sebdah/dotfiles/blob/master/config/nvim/init.vim)

**Comment by bhcleek** [comment] 2020-03-03 14:04
Duplicate of https://github.com/fatih/vim-go/issues/2748

**Closed by bhcleek** 2020-03-03 14:04 UTC
Labels: duplicate
