### ISSUE TITLE
While running `:GoDoc` I get the error `missing required -pos flag`

### ISSUE THREAD

**Issue by trstringer** [fatih/vim-go#1778] opened 2018-04-08 01:19 UTC
### What did you do? (required. The issue will be **closed** when not provided.)

While my cursor (in normal mode) is over a function name, I ran `:GoDoc`.

### What did you expect to happen?

I expected the godoc to run successfully and show me the doc for the particular function.

### What happened instead?

I received the error: `vim-go: missing required -pos flag`

### Configuration (**MUST** fill this out):

* vim-go version: commit 37fa8bc6447eacc36eefe7bea35a9813f333e30a

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc): [My .vimrc](https://github.com/trstringer/dotfiles/blob/master/.vimrc)

* Vim version (first three lines from `:version`): 

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar  6 2018 08:24:35)
Included patches: 1-1573

* Go version (`go version`): `go version go1.10.1 linux/amd64`

* Go environment (`go env`):

GOARCH="amd64"
GOBIN=""
GOCACHE="/home/trstringer/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/trstringer/go"
GORACE=""
GOROOT="/usr/lib/golang"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build121352919=/tmp/go-build -gno-record-gcc-switches"

**Comment by bhcleek** [comment] 2018-04-08 02:00
Please try latest master. This was just fixed...

**Comment by Carpetsmoker** [comment] 2018-04-08 02:02
Also duplicate of #1767

**Closed by Carpetsmoker** 2018-04-08 02:02 UTC
