### ISSUE TITLE
setting let g:go_def_mapping_enabled = 0 doesn't disable gd command

### ISSUE THREAD

**Issue by oryband** [fatih/vim-go#386] opened 2015-04-14 07:33 UTC
```vim
" Set this in my .vimrc,
" but pressing `gd` in a go file still goes to definition.
let g:go_def_mapping_enabled = 0
```

**Comment by fatih** [comment] 2015-04-15 07:35
Hi @oryband. Thanks for opening this and the other PR's. I'm currently busy, however I'm going to look at it in my spare time as soon as possible.

**Comment by fatih** [comment] 2015-04-21 11:27
I've double checked and this is indeed working. Please execute `:nmap` and see to what `gd` is mapped after you add the setting above in your `vimrc`. For example in my case there is no `gd` listed after adding it to my vimrc.

**Comment by fatih** [comment] 2015-04-29 21:14
Ping

**Comment by oryband** [comment] 2015-04-30 07:09
hey @fatih  I'll get to it in the following days, please hold the line until then :)

**Comment by fatih** [comment] 2015-05-08 20:26
@oryband I'll close this issue as it works as intended.

**Closed by fatih** 2015-05-08 20:26 UTC

**Comment by k-i-k-ichi** [comment] 2018-06-13 07:59
I have the exact same bug, delete all files in .vim/views resolved this bug for me.
