### ISSUE TITLE
Feature request: expose escaping information

### ISSUE THREAD

**Issue by empijei** [fatih/vim-go#2749] opened 2020-02-28 06:45 UTC
As of Go 1.14 escape analysis info can be outputted as json: https://golang.org/doc/go1.14#compiler

Please consider adding a setting to expose this information in vim-go.

Running the compiler with `go build -gcflags="-m -l -json 0,out" the/package` will give useful machine readable info on potential optimization points.

**Comment by bhcleek** [comment] 2020-02-29 15:53
Closing, because this is effectively a duplicate of #2039

**Closed by bhcleek** 2020-02-29 15:53 UTC
Labels: feature
