### ISSUE TITLE
Packages in vendor folder are not detected

### ISSUE THREAD

**Issue by mgartner** [fatih/vim-go#2036] opened 2018-10-30 18:23 UTC
I see lint errors in vim-go because it can't find packages that have been installed with dep to `vendor/`. The error message is `cannot find package "github.com/some/package" in any of:`.

I've verified my `$GOPATH` is correct, so that's not the issue.

The only remedy is to run `go get` on those packages, which places packages in `$GOPATH/src`, but that's a tedious workaround.

Here's an example:

![image](https://user-images.githubusercontent.com/1128750/47743309-fe27c300-dc3b-11e8-9bcc-06502aabdf0b.png)

**Comment by bhcleek** [comment] 2018-10-31 02:42
I'm unable to duplicate the problem you've describe. Do you have a package that we could test with?

**Comment by mgartner** [comment] 2018-10-31 19:19
What's weird is it only happens with the first "unknown" package listed:

![image](https://user-images.githubusercontent.com/1128750/47813037-25979200-dd07-11e8-910e-a7ae10e81219.png)

![image](https://user-images.githubusercontent.com/1128750/47813070-347e4480-dd07-11e8-81b8-c60ffd1b4fb1.png)

**Comment by bhcleek** [comment] 2018-11-02 21:52
@mgartner do you have a repo I can test with that demonstrates this problem?

**Comment by bhcleek** [comment] 2018-11-16 04:40
Closing due to lack of feedback. @mgartner if you can provide a repo that we can test with that demonstrates the problem, I'll gladly re-open this.

**Comment by mgartner** [comment] 2018-11-30 02:34
@bhcleek it happens in every repo that has dependencies. For example, in https://github.com/stretchr/testify/blob/master/mock/mock.go:

![image](https://user-images.githubusercontent.com/1128750/49264951-29e9c480-f405-11e8-8074-6f429a6eac3c.png)

Keep in mind that I'm able to build, run, and test these repos fine. It's only vim-go that thinks something is wrong.

Here's the output of my `go env`:

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/marcus/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/marcus/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10.3/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/qf/w407q1hx4cl65b_kdv_dnvp80000gn/T/go-build543346251=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by bhcleek** [comment] 2018-11-30 07:14
What happens if you run `golint` on a package from the commandline?

**Comment by mgartner** [comment] 2018-11-30 18:01
I seemed to fix it for some repositories. It looks like I had a version of go installed with brew, and then later started using goenv. I ran `brew uninstall dep; brew uninstall go` and that seemed to fix all the incorrect warnings in the testify repo that I was see this on.

However, it persists in some of my private repositories still. I'll keep trying some things, but maybe this progress is an important clue.

**Comment by bhcleek** [comment] 2018-11-30 22:39
Should I close this issue, or do you think the problem is vim-go related somehow?

**Comment by mgartner** [comment] 2018-12-01 00:02
Not sure. vim-go is the only thing that complains, so I'm at a loss for how to debug this.

**Comment by bhcleek** [comment] 2018-12-01 01:56
From within vim, what does `!echo $PATH` show you? What about `echo $GOPATH`? (notice that there is a `!` on the first and not on the second...)

**Comment by bhcleek** [comment] 2019-01-02 21:02
closed for lack of feedback.

**Comment by mgartner** [comment] 2019-01-02 21:34
Sorry.

```
:!echo $PATH
/Users/marcus/.rvm/gems/jruby-1.7.19/bin:/Users/marcus/.rvm/gems/jruby-1.7.19@global/bin:/Users/marcus/.rvm/rubies/jruby-1.7.19/bin:/Users/marcus/.nodenv/shims:/Users/marcus/.goenv/shims:/Users/marcus/.asdf/bin:/Users/marcus/.asdf/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/
opt/X11/bin:/Users/marcus/.rvm/gems/jruby-1.7.19/bin:/Users/marcus/.rvm/gems/jruby-1.7.19@global/bin:/Users/marcus/.rvm/rubies/jruby-1.7.19/bin:/Users/marcus/.nodenv/shims:/Users/marcus/.goenv/shims:/Users/marcus/.asdf/bin:/Users/marcus/.asdf/shims:/Users/marcus/go/bin:/Users/marcus
/.rvm/bin:/Users/marcus/go/bin
```

```
:echo $GOPATH
/Users/marcus/go
```

**Comment by bhcleek** [comment] 2019-02-11 01:49
Closing due to lack of feedback

**Closed by bhcleek** 2019-02-11 01:49 UTC

**Comment by jawang35** [comment] 2019-08-06 00:40
I had this exact problem and came across this issue. For me it was that I had symlinked the repository into my `$GOPATH`. @mgartner not sure if that's what was causing the issue for you but if anyone else runs into the same problem and comes across this issue hopefully this helps.

**Comment by aabbtree77** [comment] 2020-11-23 00:04
I had one similar issue, and the problem was easy to see, but I could mention it just in case.

Let the package A depend on the package B'. A is outside $GOPATH, B' is inside A/vendor. There is a different version of B', called B, which is already installed inside $GOPATH. In this case, vim-go picks up B, not B'. If A is installed correctly inside $GOPATH, vim-go chooses its vendor package B' instead of B.

This is relevant when working with modules/outside $GOPATH, some vendor-related dangers/peculiarities there.
