### ISSUE TITLE
bug: NVIM opens new buffers when `log.Print*` contains filename

### ISSUE THREAD

**Issue by marcofeltmann** [fatih/vim-go#3495] opened 2023-02-02 20:27 UTC
### What did you do? 

Given the following Sample:

```go
package main

import (
	"log"
	"os"
)

func main() {
	logger := log.New(os.Stdout, "prefix:", log.Ldate|log.Ltime|log.Lshortfile)
	logger.Println("Some Output with File")
}
```

Running via `:GoRun` opens a buffer containing the log output like 

```
prefix:2023/02/02 20:02:50 main.go|10| Some Output with File
```

Hit `enter` to finish that run.

### What did you expect to happen?

The focus returns to the buffer with the currently opened `main.go` so I can continue to work on my project.

### What happened instead?

NVIM opens a buffer at `prefix:2023/02/02 20:02:50 main.go` which does not exist, thus it puts the common template into the buffer.

One cannot save the file because according to NVIM 

```
"E212. Can't open file for writing: no such file or directory"
```

Because of the `Ltime` flag every new second creates a new "file" loaded into a new buffer, so it somewhat floods the NVIM buffers.

### Configuration

Somewhat annoying and cumbersome providing all that stuff as it doesn't seem to have anything to do with the issue, but yeah.

#### vim-go version:

```
commit 9e64fc1ab60b2e97d39410482b64289dbbaf4eda (HEAD -> master, origin/master, origin/HEAD)
```

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim
let g:go_fmt_command = "goimports"
let g:go_textobj_enabled = 1
let g:go_auto_type_info = 1
let g:go_highlight_trailing_whitespace_error = 1
let g:go_highlight_extra_types = 0
let g:go_list_type = "quickfix"
let g:go_echo_command_info = 1
let g:go_def_mode='gopls'
let g:go_info_mode='gopls'
let g:go_referrers_mode = 'gopls'
let g:go_gopls_complete_unimported = 1
let g:go_metalinter_command= 'golangci-lint'
let g:go_metalinter_enabled= ["govet", "errcheck", "ineffassign", "gosimple", "staticcheck"]
let g:go_doc_popup_window = 1

set makeprg=/run/current-system/sw/bin/go\ build
```
</details>

#### Vim version (first three lines from `:version`):

```
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
```

#### Go version (`go version`):

```
go version go1.19.4 linux/amd64
```

#### Go environment
<details><summary>go env</summary>

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/mafe/.cache/go-build"
GOENV="/home/mafe/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/mafe/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/mafe/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/nix/store/qqvaig40jcbqa9g005wxaaxhzy9xp99c-go-1.19.4/share/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/nix/store/qqvaig40jcbqa9g005wxaaxhzy9xp99c-go-1.19.4/share/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build416933838=/tmp/go-build -gno-record-gcc-switches"
```
</details>

#### gopls version

```
golang.org/x/tools/gopls v0.11.0
    golang.org/x/tools/gopls@v0.11.0 h1:/nvKHdTtePQmrv9XN3gIUN9MOdUrKzO/dcqgbG6x8EY=
```

**Comment by bhcleek** [comment] 2023-02-02 22:03
Duplicate of #3085. #3086 fixes this; I'll merge it soon.

**Closed by bhcleek** 2023-02-02 22:03 UTC
Labels: duplicate
