### ISSUE TITLE
GoDef doesn't work (vim 7.4/vim-go master)

### ISSUE THREAD

**Issue by evverx** [fatih/vim-go#1107] opened 2016-11-21 07:35 UTC
`GoDef` produces:
```
vim-go: searching declaration ...
Error detected while processing function go#def#Jump[66]..<SNR>63_def_job:
line    1:
E488: Trailing characters
E126: Missing :endfunction
```

* vim version
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun  2 2016 10:02:17)
Included patches: 1-1868
Modified by <bugzilla@redhat.com>
Compiled by <bugzilla@redhat.com>
```
* vim-go: 59c56f0903a1ed1136
* go: 
go version go1.6.3 linux/amd64
go version go1.7.3 linux/amd64

`vim-go (v1.9)` works fine

**Comment by evverx** [comment] 2016-11-21 07:47
@fatih , I'm not sure

Actually, I read https://github.com/fatih/vim-go/commit/59c56f0903a1ed1136856acefee2d014574d28f0
> Backwards compatible with Vim 7.4.xx. If you see any problems, please open an issue.

but
> Master branch is supposed to be a development branch. So stuff here can break and change

should I close this issue?

**Comment by fatih** [comment] 2016-11-21 16:54
Thanks for opening the bug report. Part of merging to master is to see these kind of issues and fixes it until we release the stable release. I'm going to fix it while I'm back home (I'm currently on travel to home)

**Comment by fatih** [comment] 2016-11-21 16:55
No do not close, I appreciate you opened it. I'll fix it soon :)

**Comment by fatih** [comment] 2016-11-22 04:00
I couldn't reproduce it on `non-async` version with Vim `8.0`. (disabled async and tested it) I need to find a way to re install vim 7.4.x on Mac.

**Comment by fatih** [comment] 2016-11-22 04:03
I've tried with version  7.4.2364 and it still works. You need to give me more info. Right now it seems like it's bug local to your setup somehow.

**Comment by fatih** [comment] 2016-11-22 04:19
Seems like this is a duplicate: https://github.com/fatih/vim-go/issues/1105 I've even used patch `7.4.1655` but it just works for me. Still trying to understand what the problem is.

**Comment by fatih** [comment] 2016-11-22 04:26
@evverx I think your vim version is has `job` support somehow. Because the message `vim-go: searching declaration ...` only happens if `job` is enabled. Is there are a way you can `downgrade` to a version with less patches, say around `1600` or just upgrade to the new one? At least we can confirm it. Meanwhile I'm going to add some checks to enable `job` only if a certain patch is included and if Vim 8 is being used.

**Comment by evverx** [comment] 2016-11-22 06:10
@fatih ,
>  vim-go: searching declaration ... only happens if job is enabled

Indeed. `vim --version` shows:
```
+job
```
I'm bisecting:
* `v7.4.1273` works fine
* `v7.4.1274` doesn't work (Add job_start(), job_status() and job_stop().)
* `v7.4.2367` works fine

I'll try to find the first working version :-)

**Comment by evverx** [comment] 2016-11-22 07:20
@fatih, `vim7.4.2120` is the first good version. `2120` works but sometimes produces:
```
vim-go: FAILED
Error detected while processing function 266[34]..267:
line   21:
E716: Key not present in Dictionary: bang
E15: Invalid expression: !empty(errors) && !self.bang
```

**Comment by fatih** [comment] 2016-11-22 13:04
This is fixed now in master with PR: https://github.com/fatih/vim-go/pull/1114. I've disabled `+job` entirely for `7.4.x` version of vim as it's not working well there. If you want to use the latest `+job` features you should use at least `8.0.0087`. Thanks for opening this!

**Closed by fatih** 2016-11-22 13:04 UTC

**Comment by evverx** [comment] 2016-11-22 13:36
@fatih , many thanks!

> If you want to use the latest +job features you should use at least 8.0.0087

You're right. And I wonder why `Fedora` and `Ubuntu` ship the `vim7.4`-package with `+job`.
