### ISSUE TITLE
neovim GoBuild errors

### ISSUE THREAD

**Issue by nhooyr** [fatih/vim-go#1172] opened 2017-01-07 23:09 UTC
### Behavior

I just ran `:GoBuild` in a package with errors and I get

```
vim-go: building dispatched ...
E118: Too many arguments for function: <SNR>121_on_stderr
vim-go: FAILED
Error detected while processing function <SNR>121_on_exit:
line   31:
E684: list index out of range: 0
Error detected while processing function <SNR>121_on_exit:
line   31:
E116: Invalid arguments for function go#util#EchoError
```

**Comment by fatih** [comment] 2017-01-08 08:08
Can you send a patch if you now what the problem is? I don't have time to look soon. Thanks

**Comment by jasdel** [comment] 2017-01-15 08:01
Ran into this issue my self also. I think something in a recent update of nvim is causing this issue. I've reverted vim-go back a few versions and reproduced similar errors while keeping nvim constant.

**Comment by fatih** [comment] 2017-04-02 01:50
Closing as I have limited information. @nhooyr please send a PR next time :)

**Closed by fatih** 2017-04-02 01:50 UTC

**Comment by nhooyr** [comment] 2017-04-02 02:20
I haven't been programming in go for a while but it looks like someone created a fix?

https://github.com/andviro/vim-go/commit/537a0491fb5b2e005768bfc4dbfc76d2120f792e
