### ISSUE TITLE
Unexpected formatting behaviour 

### ISSUE THREAD

**Issue by Gnoale** [fatih/vim-go#3045] opened 2020-10-09 09:22 UTC
### What did you do? (required: The issue will be **closed** when not provided)

I am trying to edit a source file inside my $GOPATH for debugging purpose (an external library installed through go mod)

I have 2 issues :

- First : 
Whenever I added a `fmt.Println` statement in the code, on saving, the statement where systematically removed.
I expected that the plugin will add a "fmt" import as it does with my other source files. 
I don't know if that could be related to the fact I am editing an external lib in the gopath ?

- Second :
Now, in am stuck with am obvious typo in the code which keeps getting reformatted when I fix it

```
package ldap

import (
	"errors"

	ber "github.com/go-asn1-ber/asn1-ber"
)
...

type request interface {
	appe	ndTo(*ber.Packet) error
}
```
 
1. fix the line to `appendTo(*ber.Packet) error` 
2. write the file
3. the line is rewritten as `appe	ndTo(*ber.Packet) error`

### What did you expect to happen?

I should be able to fix the typo and save the file
I should be able to insert fmt statement inside the file without them being removed

### Configuration (**MUST** fill this out):

I don't know what to provide, I didn't configured anything beside installing the required modules with `:GoInstallBinaries`

#### vim-go version:
v1.22

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
execute pathogen#infect()

set ffs=unix,dos
set encoding=utf8

" Use ONE clipboard : the system + register
set clipboard=unnamedplus

syntax enable
set background=dark
set nu

set t_Co=256
set term=xterm-256color

colorscheme dracula
set bs=2

" 1 tab == n spaces
set expandtab
set shiftwidth=2
set tabstop=2
set softtabstop=2
		
" Linebreak on 100 characters
set lbr
"set tw=100

"set hlsearch
set incsearch
set ignorecase
set autoindent

filetype plugin indent on
set mouse=a

" hell bell
set noerrorbells visualbell t_vb=
autocmd GUIEnter * set visualbell t_vb=
set noswapfile
</pre></details>

#### Vim version (first three lines from `:version`):
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 18 2020 18:29:15)
Included patches: 1-1453
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
```

#### Go version (`go version`):
go version go1.14 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/guillaumenoale/.cache/go-build"
GOENV="/home/guillaumenoale/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/guillaumenoale/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build803169877=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version

version master, built in $GOPATH mode

**Comment by bhcleek** [comment] 2020-10-09 16:45
I believe this is already fixed in a later vim-go version. Please try upgrading your vim-go to either the latest release, [v1.24](https://github.com/fatih/vim-go/releases/tag/v1.24), or the latest on master.

**Comment by Gnoale** [comment] 2020-10-09 16:54
I pulled latest from master, and updated the modules.
It works fine in my working repository, however, I reproduce the issue of editing a source file from a package in my gopath : when saving the line disappear :? 
But maybe that's expected as you're not really supposed to hack files inside this repository as they are read only by default...

**Comment by bhcleek** [comment] 2020-10-09 17:14
I'm not quite sure how to duplicate the problem you're describing. Can you clarify how I could attempt to duplicate this?

**Comment by pedromss** [comment] 2020-10-09 20:38
@Gnoale I'm using vim-go 1.24 and I can edit and save files with no problem inside the go path. Packages that I've installed with `go get`.  My setup is different than yours, neovim instead of vim and my vimrc is very full, but the point I want to make is that you should be able to edit `*.go` files in you `GOPATH/src` dir, vim-go doesn't stop me from doing that.

**Comment by Gnoale** [comment] 2020-10-12 07:35
@bhcleek you can edit a file inside the module cache path `/go/pkg/mod/` (I just learned it's called like that) 
change the file permission you want to edit to 666 (it should be 444 by default)
Insert a `fmt.Println("test")` statement inside any function
write the file (the statement get removed in my case)

**Comment by Gnoale** [comment] 2020-10-12 08:08
also, I tried to set the cache to rw as explained [here](https://golang.org/ref/mod#module-cache) to check if it change something `go env -w GOFLAGS=-modcacherw`
after cleaning `go clean -modcache`, the files are still read only, I'm not sure why...
```
~/go/pkg$ ll mod/github.com/go-ldap/ldap/v3@v3.2.3/
total 272
drwx------ 2 guillaumenoale guillaumenoale  4096 Oct 12 09:58 ./
drwxrwxr-x 3 guillaumenoale guillaumenoale  4096 Oct 12 09:58 ../
-r--r--r-- 1 guillaumenoale guillaumenoale  2587 Oct 12 09:58 add.go
-r--r--r-- 1 guillaumenoale guillaumenoale 17228 Oct 12 09:58 bind.go
-r--r--r-- 1 guillaumenoale guillaumenoale   740 Oct 12 09:58 client.go
-r--r--r-- 1 guillaumenoale guillaumenoale  1758 Oct 12 09:58 compare.go
...
```
**But** now, I can insert my print statement (still, I have to change the file permission of course) and it works as expected !
so maybe that's related

**Comment by bhcleek** [comment] 2020-10-14 21:17
Yes, vim-go cannot magically write files that are not writeable. However, I'd expect Vim to show you an error when you attempt to write a readonly file.

**Comment by Gnoale** [comment] 2020-10-15 07:10
I'm not talking about magic since I changed the file permission **before** writing to it, in both cases (with or without modcacherw)

**Comment by bhcleek** [comment] 2020-10-15 15:31
Your section in the original report about your vimrc doesn't indicate that you have any of vim-go's options set. Is that accurate? If so, then you're using `gofmt` for formatting and all vim-go does is shell out to format and then re-read the file into your buffer 🤔

**Comment by Gnoale** [comment] 2020-10-15 15:58
Exactly, except that since the update I added `let g:go_imports_autosave = 1` because it is not default anymore.

**Comment by bhcleek** [comment] 2020-10-15 16:33
You don't need to enable `g:go_imports_autosave` unless `g:go_fmt_command` is set to `gopls`. Instead, you can `let g:go_fmt_command='goimports` and it will be both format and adjust imports on saving even when `g:go_imports_autosave` is disabled.

**Comment by bhcleek** [comment] 2020-10-16 18:55
I can duplicate the issue you're seeing with `gofmt` at the commandline. That's not totally surprising; the module source cache is not intended to be edited. Unfortunately, `gofmt` doesn't show any errors when you try formatting a file in the module cache.

In any case, I don't think there's anything that vim-go can do about this.

**Comment by bhcleek** [comment] 2020-10-17 02:03
In general, if you want to see what vim-go is running, you can `let g:go_debug = ['shell-commands']`, do the operation, and see the command and arguments that it ran. You can then run the command manually on the command line to see if the problem is with vim-go or with the tool to which it delegates. Commands are run in the directory that contains the file for the active buffer.

**Closed by bhcleek** 2020-10-17 02:03 UTC

**Comment by Gnoale** [comment] 2020-10-19 08:24
Thanks :+1:
