### ISSUE TITLE
GoBuild shows incorrect paths due to fix for #399

### ISSUE THREAD

**Issue by gavrie** [fatih/vim-go#407] opened 2015-04-30 16:07 UTC
Starting with commit 0d1e8c945481128ec7e17b51780a85af5046224d, which says it fixes #399, when running GoBuild the paths in the error window are wrong and remove all subdirectories inside the current project -- i.e. it thinks the file resides directly in $GOPATH. This prevents jumping to the error since the path doesn't match the actual file path.

**Comment by fatih** [comment] 2015-04-30 16:22
Did you try https://github.com/fatih/vim-go/pull/405?

**Comment by gavrie** [comment] 2015-04-30 16:30
I tried it now, and it fixes the issue.

**Comment by gavrie** [comment] 2015-04-30 17:32
I rejoiced too early. Even with this commit, it still fails when running GoTestCompile :-(

**Comment by fatih** [comment] 2015-04-30 21:40
It's impossible, because they all share the same function. Please provide a test case with code that shows the error you're seeing.

**Comment by fatih** [comment] 2015-05-03 10:37
Hi @gavrie. We had another issue with :GoInstall and there was a compatibility problem with GoTestX output and others. This is fixed with #410. Can you please try it? If it doesn't work please provide an instruction how to reproduce it.

**Comment by gavrie** [comment] 2015-05-03 13:20
I tried it and this fix works perfectly.

**Comment by fatih** [comment] 2015-05-03 13:22
Awesome :+1: Thanks for the feedback @gavrie. This issue will be closed once I merge #410. I'm waiting for the other issues response.

**Comment by gavrie** [comment] 2015-05-03 13:27
@fatih, thank _you_ for an awesome Go work environment in Vim!

**Comment by fatih** [comment] 2015-05-08 20:20
This is now closed with the fix #410

**Closed** 2015-05-08 20:19 UTC
