### ISSUE TITLE
Saving files very slow due to gofmt

### ISSUE THREAD

**Issue by gbbr** [fatih/vim-go#482] opened 2015-07-10 07:02 UTC
When using the `gofmt` "_on save_" option it can sometimes take up to 5 seconds when saving a file. This seems to only occur when the file is part of a large project within the current working directory.

Does `gofmt` _on save_ run only on the current file or does it run on the whole tree? It seems to me like the later but I'm not familiar with the implementation. Is there anyway to keep this option but at the same time improve the speed?

**Comment by fatih** [comment] 2015-07-10 07:09
Hi @gbbr 

This is a duplicate of #459. Can you please have a look at it and also post your profile.log? I would appreciate it.

As for your question, it's per file rather than project. For me `gofmt` on save is instantaneous, however there are cases (here #459 and #476) which shows that it's slow for some people. 

You might change `fmt.vim` to the old commit (https://github.com/fatih/vim-go/commit/99a1732e40e3f064300d544eebd4153dbc3c60c7), but this is not breaking the layout when the same file is open in two different views (windows). Also I'm not sure this would make it faster, but give it a try.

Thanks

**Closed by fatih** 2015-07-10 07:09 UTC

**Comment by gbbr** [comment] 2015-07-10 17:04
Hi @fatih 

Thanks for the prompt reply. I'm not exactly sure why it's slower in one file but faster in another.

The slow file has 256 lines and here is the *full* profile: http://pastebin.com/gkBRPS8Y (just search for "fmt")
A much faster file has 5825 lines: http://pastebin.com/ithy8F16

It's odd that the significantly faster file is the larger one. The only difference between them that I can think of is that the file with 256 lines is part of a project with thousands of files, while the other one is part of a much smaller one.

It's not *extremely* slow, but it would be nicer if it were equally fast on all files :)

Thanks!
