### ISSUE TITLE
"-- More --" on write

### ISSUE THREAD

**Issue by spf13** [fatih/vim-go#217] opened 2014-10-30 23:03 UTC
Whenever I save a go file it appears to read it in a less style buffer prompting me for "-- More --". It also doesn't seem to work properly with the formatting / importing. All other aspects of the plugin seem to be working fine.  

Manually running :GoFmt or :GoImports has the exact same effect. 

Not really sure what is causing it or even where to start debugging it.

**Comment by andrewaustin** [comment] 2015-01-03 03:24
I also have this problem on Ubuntu 14.04.1 using Go 1.4 and vim 7.4 (installed via the vim-nox package). 

Unlike @mtchavez this is a fresh install of Go, so I only have fresh binaries as a result of ```:GoInstallBinaries```. I tried running ```:GoUpdateBinaries``` just to be safe though, but this did not work.

My .vimrc is tiny:

```
execute pathogen#infect()
syntax on
set nu
filetype plugin indent on
Helptags
let g:go_fmt_command = "goimports"
```

Removing ```let g:go_fmt_command = "goimports"``` from my .vimrc fixed the issue. I tried running ```go get golang.org/x/tools/cmd/goimports``` but still had the same issue.

**Comment by paytonrules** [comment] 2015-01-11 16:42
Since upgrading from go 1.3.3 to go 1.4 I get the problem above, plus numerous others. What I had to do was make sure 1.3.3 was missing from my system, cleanout all the installed binaries for gocode, godoc, etc. and reinstall them using :GoInstallBinaries. Doing it manually did not work.

**Comment by dewyze** [comment] 2015-01-12 19:02
I have tried many of the solutions here, completely blown away Go and reinstall, updated binaries, and am having the same issues. Interestingly, I have two machines that have the same dotfiles and this is only happening on one. I am using native Mac terminal.

**Comment by fatih** [comment] 2015-01-12 19:04
@dewyze do they also have the same Vim version? I wonder if it's happening only for a specific version.

**Comment by dewyze** [comment] 2015-01-12 19:11
I am going to look into that later tonight, I am only have one currently with me. And it is only when using: `let g:go_fmt_command = "goimports"`

**Comment by dewyze** [comment] 2015-01-13 04:36
I had two different versions of this Plugin on both computers, I used `vim -V` to figure out what was being called and realized that in order for it to work it was passing -1 to [here](https://github.com/fatih/vim-go/blob/master/autoload/go/fmt.vim#L76).

**Comment by pzduniak** [comment] 2015-01-13 16:42
Same issue using Cygwin.

**Comment by vessenes** [comment] 2015-01-16 00:13
I too had this problem on Ubuntu 14.04 after upgrading to go 1.4.

I had to do two things to fix it: first, I (or a script?) had linked `/usr/local/go/bin/go` to `/usr/bin`. I had to remove that link, and update my GOBIN and PATH in my .bashrc to point to the right place. 

Then I ran :GoInstallBinaries inside vim. The error messages there are a little troubling, by the way. Installs actually failing look a lot like Downloads failing and installs succeeding. 

At any rate, I now have back my old vim-go, thanks!

**Comment by vessenes** [comment] 2015-01-16 00:42
Updating to note that I installed https://github.com/fatih/vim-go/pull/286 and things seem to be back to normal, including QuickFix.

**Comment by fatih** [comment] 2015-01-19 11:04
Can every one pull the latest master and try it again? It seems some of the problems was caused due the  absent of goimports binary. We now check for it and also prompt a warning to install it.

**Comment by casimir** [comment] 2015-01-19 18:17
I used it a few hour on Linux, no problem at all. On OSX on the other side I have this behaviour: all good on the first `:w` but on the seconde one (every time) I get the following screenshot. I have `let g:go_fmt_command = 'goimports'` in my `.vimrc`.

![image](https://cloud.githubusercontent.com/assets/879004/5805388/b03a70b0-a00e-11e4-95f3-f359b38bbc57.png)

I'm not sure if this is related to binaries existence looking at the errors. Either way the bug is the same.

Linux: Archlinux (up to date), Vim and Go from official repo
OSX: Yosemite (10.10.1), Vim is the one shipped with the OS and Go installed with `brew`

NB: Now that I think of it, all were fine before upgrading to Go 1.4.1. Before that it was a fresh install.

**Comment by rtfb** [comment] 2015-01-19 20:22
Still repro the original problem.

Another data point: if I `let g:go_fmt_command = 'goimports'` in `.vimrc`, the problem goes away, I can save the file, but `goimports` doesn't seem to have been run. Furthermore, even if I `let g:go_fmt_command = 'gofmt'`, I can save the file, but formatting isn't restored. (And yes, I did a sanity check: both `goimports` and `gofmt` work as expected from command line :-))

More details about my box, in case it helps:
```
$ which goimports 
/home/rtfb/sw/gopkgs/bin/goimports
$ which gofmt
/home/rtfb/hacking/go/bin/gofmt
$ go version
go version go1.4 linux/amd64
$ echo $GOPATH 
/home/rtfb/sw/gopkgs
$ echo $GOBIN
/home/rtfb/sw/gopkgs/bin
$ echo $GOROOT 
/home/rtfb/hacking/go
```

**Comment by casimir** [comment] 2015-01-19 21:50
Maybe related https://github.com/neovim/neovim/issues/1432.

**Comment by casimir** [comment] 2015-01-23 10:17
I feel terrible, it looks like the problem was actually me. I had unit tests running on every write and one test deleting the temp directory. My bad.

**Comment by BenjaminRH** [comment] 2015-02-04 11:48
I've got this problem too

**Comment by mathicalee** [comment] 2015-02-06 21:19
I had the same issue described here, and I tried installing vim by compiling the source code, removed .vimrc and all plugins and installed everything from scratch, but it didn't help. But found that executing 'go fmt' on shell did not work, because the bin directory of go was not in my PATH. I wanted to choose my go version with update-alternatives before, and that resulted that only my go execute file was in the PATH and nothing else. After putting back the bin directory of go to PATH, it works! I hope this would help.

**Comment by obscuren** [comment] 2015-03-30 09:41
I had the same issue and it appeared that my `shell` wasn't set (running `GoFmt` manually gave an error message). Setting it so something meaningful like `set shell=/bin/zsh` fixed the issue.

**Comment by fatih** [comment] 2015-04-04 16:40
This problem/issue is grown to something that is not manageable anymore. I'm not sure even if it's reproducible (it's not for me of course). I think either their is a version mismatch between certain Vim versions or this is completely out of vim-go's domain. Because there is little to nothing I can do here right now and everyone reporting something else that fixes their problems I believe this is not related to vim-go anymore.  I'm closing this issue due it's long history (6 months) and due it's non manageable content. If anybody feels this needs to be reopened I'm ok with, but please read all comments again and decide afterwards if it's really something that can be solved (which I don't believe, explained above why). Thanks for everyone contributing to this issue.

**Closed by fatih** 2015-04-04 16:40 UTC
Labels: bug

**Comment by mbsulliv** [comment] 2016-03-15 15:48
I believe I can speak to the nature of this problem when using vim-go on cygwin.  I'm using goimports as my format command and what vim attempts to execute is `goimports -w  /tmp/vDU9qNa/1`.  That file exists but the command as written fails because the Windows version of goimports (the version compiled by go on Windows) expects drive letter qualified paths.  If I rewrite the command as `goimports -w C:/cygwin-1.7.31-3/tmp/vDU9qNa/1`, it works.

This is a constant source of problems when interacting with Windows executables from bash within cygwin.  There's even a tool call cygpath that comes with cygwin that converts between unix-like and Windows-like paths.  If I rewrite the command as `goimports -w  $(cygpath -m /tmp/vDU9qNa/1)`, it also works.

**Comment by jzelinskie** [comment] 2016-03-19 07:22
Same exact issue as @mbsulliv. Did you ever find a workaround?

**Comment by mbsulliv** [comment] 2016-03-19 13:13
I did.  I temporarily modified the `system()` command in `autoload/go/fmt.vim` to prepend the missing portion of the file path.  For example: `let out = system(command . " C:/cygwin-1.7.31-3" . l:tmpname)`.

**Comment by jzelinskie** [comment] 2016-03-19 21:50
Awesome! I got things working now. Thanks @mbsulliv

**Comment by drewvanstone** [comment] 2016-04-20 01:40
This behavior seems to happen whenever the go* tools fail for any reason. I was getting this issue on Mac OSX El Capitan. I'd installed the go* tools with `:GoBinariesIstall` and they were properly on my path, but when manually executed, I'd get this error:

```
[11:31:27] bin  ❯ ./golint
fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x35ca60, 0x21)
        /usr/local/Cellar/go/1.6.1/libexec/src/runtime/panic.go:530 +0x90 fp=0x7fff5fbfeb40 sp=0x7fff5fbfeb28
runtime.goenvs()
        /usr/local/Cellar/go/1.6.1/libexec/src/runtime/os1_darwin.go:76 +0x8d fp=0x7fff5fbfeb68 sp=0x7fff5fbfeb40
runtime.schedinit()
        /usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:440 +0xa7 fp=0x7fff5fbfebb0 sp=0x7fff5fbfeb68
runtime.rt0_go(0x7fff5fbfebe8, 0x1, 0x7fff5fbfebe8, 0x0, 0x0, 0x1, 0x7fff5fbfee68, 0x0, 0x7fff5fbfee71, 0x603070, ...)
        /usr/local/Cellar/go/1.6.1/libexec/src/runtime/asm_amd64.s:138 +0x132 fp=0x7fff5fbfebb8 sp=0x7fff5fbfebb0
```

This is a known issue with Websense, which my company has installed on each laptop. Here's the issue: https://groups.google.com/forum/#!topic/golang-nuts/HtcZc3wO-rw

This Websense issue also raised it's ugly head after Go 1.4, which may explain why other's have had this issue around that time too.

At this point, I've uninstalled go-vim until I can get Websense uninstalled.

**Comment by renier** [comment] 2016-11-30 21:19
I was using goreturns (latest version), and I was seeing this problem. Switched to goimports (latest version) and the problem dissappeared. Go figure?
