### ISSUE TITLE
GoInfo not reporting type information

### ISSUE THREAD

**Issue by pennz** [fatih/vim-go#1927] opened 2018-08-26 09:38 UTC
### What did you do? (required. The issue will be **closed** when not provided.)
Install neo-vim and updated vim-go to the newest commit 0aa956f504154fe380d8066e8683893415d5039a.

### What did you expect to happen?
GoInfo can work fine.

### What happened instead?
GoInfo cannot work. And it reports the following message when I tried to run GoInfo
```sh
Error detected while processing function <SNR>16_auto_type_info:
line    3:
E119: Not enough arguments for function: go#tool#Info
```
After reset vim-go to 3d8f9d24a568879c705c69a10bb3b636bf9ab120, it works fine. I did not do the bisec, 3d8f9d24a568879c705c69a10bb3b636bf9ab120 is just a commit works fine for me.

### Configuration (**MUST** fill this out):

* vim-go version: 
0aa956f504154fe380d8066e8683893415d5039a

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
```sh 
set nocompatible			
call plug#begin('~/.vim/plugged')
Plug 'fatih/vim-go', { 'tag': '*' }
Plug 'AndrewRadev/splitjoin.vim'
Plug 'SirVer/ultisnips'
call plug#end()

set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'vim-go'
call vundle#end()
filetype plugin indent on

let mapleader = ","

map <C-n> :cnext<CR>
map <C-m> :cprevious<CR>


let g:go_fmt_command = "goimports"
let g:go_autodetect_gopath = 1
let g:go_list_type = "quickfix"

let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_generate_tags = 1

let g:go_metalinter_autosave = 1
let g:go_metalinter_autosave_enabled = ['vet', 'golint']
let g:go_metalinter_deadline = "5s"

let g:go_auto_type_info = 1
let g:go_auto_sameids = 1

let g:go_decls_includes = "func,type"
nmap <C-g> :GoDecls<cr>
nmap <C-G> :GoDeclsDir<cr>
imap <C-g> <esc>:<C-u>GoDeclsDir<cr>

augroup go
  autocmd!

  autocmd BufNewFile,BufRead *.go setlocal noexpandtab tabstop=4 shiftwidth=4

  autocmd FileType go nmap <leader>b :<C-u>call <SID>build_go_files()<CR>

  autocmd FileType go nmap <leader>t  <Plug>(go-test)

  autocmd FileType go nmap <leader>r  <Plug>(go-run)

  autocmd FileType go nmap <Leader>d <Plug>(go-doc)

  autocmd FileType go nmap <Leader>c <Plug>(go-coverage-toggle)

  autocmd FileType go nmap <Leader>i <Plug>(go-info)

  autocmd FileType go nmap <Leader>l <Plug>(go-metalinter)

  autocmd FileType go nmap <Leader>v <Plug>(go-def-vertical)
  autocmd FileType go nmap <Leader>s <Plug>(go-def-split)

  autocmd Filetype go command! -bang A call go#alternate#Switch(<bang>0, 'edit')
  autocmd Filetype go command! -bang AV call go#alternate#Switch(<bang>0, 'vsplit')
  autocmd Filetype go command! -bang AS call go#alternate#Switch(<bang>0, 'split')
  autocmd Filetype go command! -bang AT call go#alternate#Switch(<bang>0, 'tabe')
augroup END

function! s:build_go_files()
  let l:file = expand('%')
  if l:file =~# '^\f\+_test\.go$'
    call go#test#Test(0, 1)
  elseif l:file =~# '^\f\+\.go$'
    call go#cmd#Build(0)
  endif
endfunction
```
* Vim version (first three lines from `:version`):
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5

* Go version (`go version`):
go version go1.10.1 darwin/amd64

* Go environment (`go env`):
```sh
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/vincent/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/vincent/works/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/kl/jmjcrkxs61df9pgkps1h607m0000gn/T/go-build911026632=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by bhcleek** [comment] 2018-08-26 16:03
I can confirm this is happening. Strangely, re-sourcing `ftplugin/go/commands.vim` seems to fix it.

**Comment by bhcleek** [comment] 2018-08-26 16:12
It was happening on my system due to the way I have it setup for development. You may have two copies of vim-go's `ftplugin/go/commands.vim` on your system. Can you please run `verbose command`? Was `GoInfo` last set from where you you have vim-go installed?

**Comment by pennz** [comment] 2018-08-27 12:29
```verbose command``` show 
```
...
!   GoImportAs  *                    customlist    call go#import#SwitchImport(1, <f-args>, '<bang>')
        Last set from ~/.vim/plugged/vim-go/ftplugin/go/commands.vim
    GoImports   0                                  call go#fmt#Format(1)
        Last set from ~/.vim/plugged/vim-go/ftplugin/go/commands.vim
    GoInfo      0                                  call go#tool#Info()
        Last set from ~/.vim/plugged/vim-go/ftplugin/go/commands.vim
!   GoInstall   *                                  call go#cmd#Install(<bang>0, <f-args>)
        Last set from ~/.vim/plugged/vim-go/ftplugin/go/commands.vim
...
```
---
> Was GoInfo last set from where you you have vim-go installed?

I have not set GoInfo before vim-go is installed. But I have 
- moved from vim to neovim
- reinstalled vim-go, moving it to .vim/bundle then moving it back to .vim/plugged

And there indeed are two vim-go.
```
$ find . -name "vim-go"                                                                                                                                           
./plugged/vim-go
./pack/plugins/start/vim-go
```
---
After removed them all and used ```Plugin 'fatih/vim-go'``` to load vim-go, the GoInfo will not report error but it won't show anything. And in the ```verbose command```, it shows 
```
    GoInfo      0                                  call go#tool#Info()
        Last set from ~/.vim/bundle/vim-go/ftplugin/go/commands.vim
```
Other Go commands work fine.

**Comment by bhcleek** [comment] 2018-08-27 20:43
@pennz I'm unable to duplicate the problem you're seeing. However, there's a PR waiting to be approved that may resolve this for you. Can you see if you still have the same problem with https://github.com/fatih/vim-go/pull/1926 ?

**Comment by pennz** [comment] 2018-08-28 12:26
@bhcleek The #1926 won't help. Besides, after pathing the pull to master b6381dd48f3983dccd3955247fd1060fd1b48c06 . I got this error:
```
Error detected while processing function <SNR>84_auto_type_info:
line    3:
E118: Too many arguments for function: go#tool#Info
```
And if I run GoInfo via comand, I got this error message:
```
Error detected while processing /Users/vincent/.vim/plugged/vim-polyglot/autoload/go/config.vim:
line  426:
E122: Function go#config#FoldEnable already exists, add ! to replace it
Error detected while processing function go#tool#Info[3]..go#complete#Info[2]..<SNR>176_async_info[41]..<SNR>176_gocodeCommand:
line   16:
E117: Unknown function: go#config#GocodeProposeSource
E15: Invalid expression: go#config#GocodeProposeSource()
Error detected while processing function go#tool#Info[3]..go#complete#Info[2]..<SNR>176_async_info[54]..go#job#Start:
line   28:
E475: Invalid argument: expected String or List
```
It seems ```go#config#FoldEnable``` is defined in vim-polyglot too.
Other commands like GoDoc works fine, still.

GoInfo in ```verbose command``` ( yes, I moved to vim-plugin as plugin manager and confirmed there is only one vim-go in .vim folder)
```
    GoInfo      0                                  call go#tool#Info()
        Last set from ~/.vim/plugged/vim-go/ftplugin/go/commands.vim
```
The log I got by running ```nvim -V20vim-go-log``` is uploaded to dropbox: [vim-go-log](https://www.dropbox.com/s/yurvqdo6fjel8kh/vim-go-log?dl=0)

**Comment by bhcleek** [comment] 2018-08-28 14:52
vim-polyglot is introducing older versions of vim-go code into your environment; please try to duplicate the problem without any other plugins loaded.

**Comment by bhcleek** [comment] 2018-08-29 14:40
@pennz prior to 4fdc5901468cb5aea6b89a80cab00d1bf16e101e, `mdempsky/gocode` wasn't fully compatible with vim-go. Please:
* close vim
* update to vim-go's latest master
* open vim and run `:GoUpdateBinaries`

and then try again. Note, however, that mdempsky/gocode does _not_ autobuild_ your packages, so you're trying to run `:GoInfo` to get information about an identifier from a package that is not installed (e.g. `go install $TARGETPKG` from the commandline or `:GoInstall` from within the target package's source using vim-go) in the package's  to your `$GOPATH/pkg` directory, mdempsky/gocode will not be be able to find it and therefore will not output anything....

**Comment by pennz** [comment] 2018-08-29 23:05
@bhcleek Thanks.

Now it works better after following your steps and runing ```go install -i $TARGETPKG```, but now some issues can be seen about GoInfo:

If I am editing this code,
```
 22 type DokodemoDoor struct {
 23     policyManager core.PolicyManager
 24     config        *Config
 25     address       net.Address
 26     port          net.Port
 27 }
```
1. when the cursor is at letter 'd' in ```type DokodemoDoor struct {```, GoInfo will feedback "vim-go: type Dokod invalid type".
2. even he cursor is at letter 'r' in ```type DokodemoDoor struct {```, GoInfo will feedback "vim-go: type DokodemoDoor invalid type".

[The log is here](https://www.dropbox.com/s/uigzf24ijn7on88/vim-go-log-invalid-type?dl=0)

**Comment by bhcleek** [comment] 2018-08-30 00:57
@pennz it sounds like your original issue is resolved. I'm going to close this, but feel free to open a new issue to promote your most recent comment to a new issue.

To debug your issue, you can run
```
gocode close
gocode -s -debug
```
And then analyze the output to see if you can identify the problem.

Also, note that without using source mode in mdempsky/gocode, its results will be based on the package as it was last installed, so if you edit your source without installing, you may not see the info you expect.

**Closed by bhcleek** 2018-08-30 00:57 UTC

**Comment by bikbah** [comment] 2018-09-05 11:10
> I've just upgraded vim-go and I'm getting the same error: Not enough arguments for function: go#tool#Info.

Have the same issue.
